import type { BuildingArchetypeShardEntry } from './types'

export const BUILDING_ARCHETYPE_ENTRIES_H_L = {
  hammam: {
    label: 'Hammam',
    description: 'A building primarily serving steam bathing ritual.',
    functions: ['care'],
    manifestationOf: 'bathhouse',
    searchTerms: ['steam', 'bath', 'islamic'],
  },
  harbourmaster_office: {
    label: 'Harbourmaster Office',
    description: 'A building primarily serving port administration.',
    functions: ['governance', 'transport_support'],
    searchTerms: ['port', 'harbor', 'shipping'],
  },
  healers_house: {
    label: 'Healers House',
    description: 'A building primarily serving dwelling.',
    functions: ['dwelling'],
    searchTerms: ['healer', 'medicine', 'clinic'],
  },
  hermitage: {
    label: 'Hermitage',
    description: 'A building primarily serving solitary devotion dwelling.',
    functions: ['dwelling', 'worship'],
    searchTerms: ['solitary', 'monk', 'retreat'],
  },
  hof: {
    label: 'Hof',
    description: 'A building primarily serving worship.',
    functions: ['food_drink_social', 'worship'],
    manifestationOf: 'temple',
    searchTerms: ['norse', 'hall', 'feasting'],
  },
  hospice: {
    label: 'Hospice',
    description: 'A building primarily serving terminal/traveler care.',
    functions: ['lodging', 'care'],
    searchTerms: ['palliative', 'traveler', 'care'],
  },
  hospital: {
    label: 'Hospital',
    description: 'A building primarily serving inpatient care.',
    functions: ['care'],
    searchTerms: ['medical', 'patients', 'healing'],
    specializationTerms: ['clinic'],
  },
  house: {
    label: 'House',
    description: 'A private dwelling.',
    functions: ['dwelling'],
    searchTerms: ['dwelling', 'home', 'residence'],
    specializationTerms: [
      'cave dwelling',
      'cottage',
      'farmhouse',
      'rectory',
      'townhouse',
      'tree dwelling',
    ],
  },
  houseboat: {
    label: 'Houseboat',
    description: 'A building primarily serving dwelling.',
    functions: ['dwelling'],
    manifestationOf: 'house',
    searchTerms: ['floating', 'boat', 'waterborne'],
  },
  hunting_lodge: {
    label: 'Hunting Lodge',
    description: 'A building primarily serving dwelling (seasonal leisure).',
    functions: ['dwelling'],
    searchTerms: ['hunting', 'seasonal', 'wilderness'],
  },
  igloo: {
    label: 'Igloo',
    description: 'A building primarily serving dwelling.',
    functions: ['dwelling'],
    manifestationOf: 'house',
    searchTerms: ['snow', 'dome', 'inuit'],
  },
  inn: {
    label: 'Inn',
    description: 'A lodging house that also serves food and drink.',
    functions: ['lodging', 'food_drink_social'],
    searchTerms: ['traveler', 'lodging', 'guest'],
    specializationTerms: ['ferry house', 'roadside inn'],
  },
  insula: {
    label: 'Insula',
    description: 'A building primarily serving dwelling (multi).',
    functions: ['dwelling', 'retail'],
    manifestationOf: 'apartment_building',
    searchTerms: ['roman', 'apartment', 'urban'],
  },
  keep: {
    label: 'Keep',
    description: 'A building primarily serving last-refuge stronghold.',
    functions: ['dwelling'],
    searchTerms: ['stronghold', 'castle', 'refuge'],
  },
  kiva: {
    label: 'Kiva',
    description: 'A building primarily serving worship (rite).',
    functions: ['worship'],
    searchTerms: ['pueblo', 'ceremony', 'ritual'],
  },
  lazaretto: {
    label: 'Lazaretto',
    description: 'A building primarily serving quarantine isolation.',
    functions: ['care'],
    searchTerms: ['quarantine', 'plague', 'isolation'],
  },
  library: {
    label: 'Library',
    description: 'A building for study and curated records.',
    functions: ['knowledge'],
    searchTerms: ['books', 'study', 'scholarship'],
  },
  lighthouse: {
    label: 'Lighthouse',
    description: 'A building primarily serving navigation signal.',
    functions: ['defense_watch', 'dwelling'],
    searchTerms: ['navigation', 'coast', 'beacon'],
  },
  longhouse: {
    label: 'Longhouse',
    description: 'A building primarily serving communal dwelling.',
    functions: ['dwelling', 'assembly'],
    manifestationOf: 'house',
    searchTerms: ['communal', 'viking', 'hall'],
  },
} as const satisfies Record<string, BuildingArchetypeShardEntry>
