export type { EntityReplacementCurrentSnapshot as RelationshipDrawerCurrentEntitySnapshot } from '../entity-replacement/entity-replacement-current-entity'
export {
  ENTITY_REPLACEMENT_CURRENT_UNAVAILABLE_MESSAGE as RELATIONSHIP_DRAWER_CURRENT_ENDPOINT_UNAVAILABLE_MESSAGE,
  ENTITY_REPLACEMENT_UNAVAILABLE_LOCATION_HEADING as RELATIONSHIP_DRAWER_UNAVAILABLE_LOCATION_HEADING,
  ENTITY_REPLACEMENT_UNAVAILABLE_ORGANIZATION_HEADING as RELATIONSHIP_DRAWER_UNAVAILABLE_ORGANIZATION_HEADING,
} from '../entity-replacement/entity-replacement-current-entity'
