packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@swc/core': true
  esbuild: true
  mongodb-memory-server: true
  sharp: true

minimumReleaseAgeExclude:
  - '@types/node@25.9.2'

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - mongodb-memory-server
  - sharp
  - unrs-resolver
