import { generateNarrative } from '@rpg/character-narrative-core'
import type { NarrativeCollection } from '@rpg/contracts/character-narrative'

import type { FoundationCompositionReviewCase } from './foundation-composition-review.fixture'

function quote(value: string) {
  return value.replaceAll('\n', ' ').replaceAll('"', '\\"')
}

export function renderFoundationCompositionReviewReport(
  collection: NarrativeCollection,
  cases: readonly FoundationCompositionReviewCase[],
): string {
  const sections: string[] = []

  for (const reviewCase of cases) {
    const result = generateNarrative({
      collection,
      context: reviewCase.context,
      seed: reviewCase.seed,
    })
    if (!result.ok) throw new Error(`${reviewCase.name}: ${result.reason}`)

    sections.push(`## ${reviewCase.name}

- Seed: \`${reviewCase.seed}\`
- Alignment: \`${reviewCase.context.alignment ?? 'missing'}\`
- Theme: \`${result.plan.theme}\`
- Used complete fallback: \`${result.usedFallback}\`
- Fragment IDs: ${result.fragmentIds.map((id) => `\`${id}\``).join(', ')}

### Traits

${result.narrative.personalityTraits.map((text) => `- “${quote(text)}”`).join('\n')}

### Ideal

- “${quote(result.narrative.ideals[0]!)}”

### Bond

- “${quote(result.narrative.bonds[0]!)}”

### Flaw

- “${quote(result.narrative.flaws[0]!)}”

### Story

${result.narrative.backstoryParagraphs.map((text, index) => `${index + 1}. “${quote(text)}”`).join('\n')}
`)
  }

  return `# Foundation composition review

Generated from collection revision \`${collection.revision}\`. Do not edit this file
directly. Regenerate it with:

\`\`\`bash
pnpm --filter @rpg/character-narrative-integrations review:foundation
\`\`\`

Review the stable cases below against the
[authoring standard](authoring.md). At least 65% of selected fragments should be
externally actionable: another character can challenge, threaten, demand, expose,
or help complete the hook, or the fragment supplies a repeatable response to a
recognizable trigger. Reject retrospective morals, placeholder nouns, completed
arcs, and visible class/species template machinery. Automated tests validate
structure; this artifact exists for the required editorial comparison.

${sections.join('\n')}
`
}
