export {
  formatResolutionApplicationPattern,
  formatResolutionDamage,
  formatResolutionDamageRoll,
  formatResolutionEffectsApplicationLabel,
  formatResolutionHealing,
  formatResolutionMethod,
  formatResolutionOutcomeLine,
  formatResolutionOutcomes,
  formatResolutionProjectilesPreview,
  formatResolutionRange,
  formatResolutionSummary,
  formatResolutionSummarySections,
  formatResolutionTarget,
  formatResolutionTargetFromParts,
  formatResolutionTargetProximityPhrase,
  formatResolutionTemporaryHitPoints,
  findResolutionDamageEffects,
  findResolutionHealingEffects,
  findResolutionTemporaryHitPointsEffects,
  type SpellResolutionSummarySection,
} from './format'
export {
  ARCANE_HAND_RESOLUTION,
  CHILL_TOUCH_RESOLUTION,
  CURE_WOUNDS_RESOLUTION,
  ELDRITCH_BLAST_RESOLUTION,
  FALSE_LIFE_RESOLUTION,
  ICE_KNIFE_RESOLUTION,
  INFlict_WOUNDS_RESOLUTION,
  MAGIC_MISSILE_RESOLUTION,
  SPELL_RESOLUTION_FIXTURES,
} from './fixtures'
export {
  deriveResolutionModelingStatus,
  getResolutionModelingStatusLabel,
  RESOLUTION_MODELING_STATUS,
  RESOLUTION_MODELING_STATUS_LABELS,
  type ResolutionModelingStatus,
} from './modeling-status'
export {
  SPELL_RESOLUTION_PRIMARY_DAMAGE_EFFECT_ID,
  SPELL_RESOLUTION_PRIMARY_HEALING_EFFECT_ID,
  SPELL_RESOLUTION_PRIMARY_TEMPORARY_HIT_POINTS_EFFECT_ID,
  spellApplicationPatternFixedCountSchema,
  spellApplicationPatternProjectilesSchema,
  spellApplicationPatternSchema,
  spellApplicationPatternUnitLabelSchema,
  spellResolutionApplicationSchema,
  spellResolutionDamageEffectSchema,
  spellResolutionEffectIdSchema,
  spellResolutionEffectSchema,
  spellResolutionHealingEffectSchema,
  spellResolutionMethodSchema,
  spellResolutionOutcomeSchema,
  spellResolutionRangeSchema,
  spellResolutionSchema,
  spellResolutionTargetProximitySchema,
  spellResolutionTargetSchema,
  spellResolutionTemporaryHitPointsEffectSchema,
  validateSpellResolutionReferences,
  type SpellApplicationPattern,
  type SpellApplicationPatternFixedCount,
  type SpellApplicationPatternProjectiles,
  type SpellApplicationPatternUnitLabel,
  type SpellResolution,
  type SpellResolutionApplication,
  type SpellResolutionDamageEffect,
  type SpellResolutionEffect,
  type SpellResolutionEffectId,
  type SpellResolutionHealingEffect,
  type SpellResolutionMethod,
  type SpellResolutionOutcome,
  type SpellResolutionRange,
  type SpellResolutionTarget,
  type SpellResolutionTargetProximity,
  type SpellResolutionTemporaryHitPointsEffect,
} from './schema'
export {
  getSpellApplicationPatternKindLabel,
  getSpellResolutionApplicationAmountLabel,
  getSpellResolutionAttackTypeLabel,
  getSpellResolutionOutcomeResultLabel,
  getSpellResolutionProximityKindLabel,
  getSpellResolutionRangeKindLabel,
  getSpellResolutionTargetKindLabel,
  SPELL_APPLICATION_PATTERN_APPLICATION_MODES,
  SPELL_APPLICATION_PATTERN_COUNT_TYPES,
  SPELL_APPLICATION_PATTERN_KIND_ENTRIES,
  SPELL_APPLICATION_PATTERN_KINDS,
  SPELL_RESOLUTION_APPLICATION_AMOUNT_ENTRIES,
  SPELL_RESOLUTION_APPLICATION_AMOUNTS,
  SPELL_RESOLUTION_ATTACK_TYPE_ENTRIES,
  SPELL_RESOLUTION_ATTACK_TYPES,
  SPELL_RESOLUTION_OUTCOME_RESULT_ENTRIES,
  SPELL_RESOLUTION_OUTCOME_RESULTS,
  SPELL_RESOLUTION_OUTCOME_RESULTS_BY_METHOD,
  SPELL_RESOLUTION_PROXIMITY_KIND_ENTRIES,
  SPELL_RESOLUTION_PROXIMITY_KINDS,
  SPELL_RESOLUTION_RANGE_KIND_ENTRIES,
  SPELL_RESOLUTION_RANGE_KINDS,
  SPELL_RESOLUTION_TARGET_KIND_ENTRIES,
  SPELL_RESOLUTION_TARGET_KINDS,
  type SpellApplicationPatternApplicationMode,
  type SpellApplicationPatternCountType,
  type SpellApplicationPatternKind,
  type SpellResolutionApplicationAmount,
  type SpellResolutionAttackType,
  type SpellResolutionOutcomeResult,
  type SpellResolutionProximityKind,
  type SpellResolutionRangeKind,
  type SpellResolutionTargetKind,
} from './vocab'
export { spellResolutionValidationMessages } from './validation-messages'
export {
  deriveDefaultEffectRecipient,
  isResolutionTargetConfigured,
  type EffectRecipient,
} from './effect-context'
export {
  formatResolutionAvailabilityReason,
  type ResolutionAvailabilityTone,
} from './availability-reasons'
export {
  applyMethodOptionPatch,
  applyResolutionStructuralCleanup,
  buildIncompatibleSelectionClearPatch,
  getApplicationPatternAvailability,
  getEffectKindAvailability,
  getMethodAvailability,
  planResolutionChange,
  resolutionChangeRequiresConfirm,
  RESOLUTION_METHOD_OPTIONS,
  toMethodOption,
} from './selection-policy'
export type {
  IncompatibleSelection,
  OptionAvailability,
  ResolutionApplicationPatternFormKind,
  ResolutionAvailabilityReason,
  ResolutionChangePlan,
  ResolutionChangeRequest,
  ResolutionEffectKind,
  ResolutionEffectRef,
  ResolutionMethodOption,
  ResolutionPatch,
  ResolutionSelectionField,
  ResolutionSelectionState,
  ResolutionWarning,
  ResolutionWarningCode,
} from './selection-types'
