import type { TermAuditConfig } from './src/types'

export const VOCAB_TERM_AUDIT_CONFIG = {
  ignore: [
    '**/node_modules/**',
    '**/dist/**',
    '**/coverage/**',
    '**/generated/**',
    '**/*.json',
    '**/*.snap',
  ],
  contextual: [
    {
      target: 'content-type:classes',
      path: 'packages/contracts/src/rpg/content/lib/content-type-terms.ts',
      reason: 'Canonical catalog content-type term registry',
      owner: 'contracts',
    },
    {
      target: 'content-type:classes',
      path: 'packages/contracts/src/rpg/vocab/**/*.ts',
      reason: 'Field taxonomy and game-rule vocabulary, not catalog chrome',
      owner: 'contracts',
    },
    {
      target: 'content-type:classes',
      path: 'apps/bench/**',
      reason: 'Bench fixture copy; not player-facing catalog chrome',
      owner: 'bench',
    },
    {
      target: 'content-type:classes',
      path: 'apps/dashboard/src/features/campaign/lib/rules/mechanics/mechanics-form-fields.ts',
      reason: 'Armor class (AC) mechanic label, not catalog class content type',
      owner: 'dashboard',
    },
    {
      target: 'content-type:classes',
      path: 'apps/dashboard/src/features/campaign/lib/rules/character-configuration/starting-wealth-form-fields.ts',
      reason: 'Domain-specific starting-wealth option copy',
      owner: 'dashboard',
    },
    {
      target: 'content-type:classes',
      path: 'apps/dashboard/src/features/content/lib/forms/grants/grant-form-fields.ts',
      reason: 'Feat-choice and class-progression grant copy owned by grant vocabulary',
      owner: 'dashboard',
    },
    {
      target: 'content-type:classes',
      path: 'apps/dashboard/src/features/content/classes/lib/character-creation/class-starting-equipment-form-values.ts',
      reason: 'Named starting package label (Standard Equipment), not parent catalog chrome',
      owner: 'dashboard',
    },
    {
      target: 'content-type:classes',
      path: 'apps/dashboard/src/features/character/lib/equipment-step.fixtures.ts',
      reason: 'Named starting package fixture label (Standard Equipment)',
      owner: 'dashboard',
    },
    {
      target: 'content-type:classes',
      path: 'packages/ui/src/components/ui/rich-text-link-picker.client.tsx',
      reason: 'Storybook defaults; dashboard passes term-derived options',
      owner: 'ui',
    },
    {
      target: 'content-type:spells',
      path: 'packages/contracts/src/rpg/content/lib/content-type-terms.ts',
      reason: 'Canonical catalog content-type term registry',
      owner: 'contracts',
    },
    {
      target: 'content-type:spells',
      path: 'packages/contracts/src/rpg/vocab/spell/**',
      reason: 'Spell field taxonomy and resolution vocabulary, not catalog chrome',
      owner: 'contracts',
    },
    {
      target: 'content-type:spells',
      path: 'packages/contracts/src/rpg/content/spell/**/*.ts',
      reason: 'Spell resolution and effect vocabulary, not catalog chrome',
      owner: 'contracts',
    },
    {
      target: 'content-type:spells',
      path: 'apps/dashboard/src/features/character/components/spells/picker/spell-picker-drawer.client.tsx',
      reason: 'Spell picker workflow chrome, not catalog collection label',
      owner: 'dashboard',
    },
    {
      target: 'content-type:spells',
      path: 'apps/dashboard/src/features/character/components/builder/steps/spells/spellcasting-summary-card.client.tsx',
      reason: 'Spellcasting mechanic labels (save DC, attack, slots), not catalog chrome',
      owner: 'dashboard',
    },
    {
      target: 'content-type:spells',
      path: 'apps/dashboard/src/features/content/classes/lib/class-spellcasting-form-fields.ts',
      reason: 'Class spellcasting progression domain copy',
      owner: 'dashboard',
    },
    {
      target: 'content-type:spells',
      path: 'apps/dashboard/src/features/content/lib/forms/grants/grant-form-fields.ts',
      reason: 'Spell grant and slot-casting domain copy',
      owner: 'dashboard',
    },
    {
      target: 'content-type:spells',
      path: 'apps/dashboard/src/features/content/spells/lib/effects/effect-template-registry.ts',
      reason: 'Spell effect template taxonomy label',
      owner: 'dashboard',
    },
    {
      target: 'content-type:spells',
      path: 'apps/dashboard/src/features/content/spells/resolution/lib/form/resolution-form-labels.ts',
      reason: 'Spell resolution mechanic labels',
      owner: 'dashboard',
    },
    {
      target: 'content-type:spells',
      path: 'packages/ui/src/components/ui/rich-text-link-picker.client.tsx',
      reason: 'Storybook defaults; dashboard passes term-derived options',
      owner: 'ui',
    },
    {
      target: 'content-type:feats',
      path: 'packages/contracts/src/rpg/content/lib/content-type-terms.ts',
      reason: 'Canonical catalog content-type term registry',
      owner: 'contracts',
    },
    {
      target: 'content-type:feats',
      path: 'packages/contracts/src/rpg/vocab/feat.ts',
      reason: 'Feat field taxonomy vocabulary, not catalog chrome',
      owner: 'contracts',
    },
    {
      target: 'content-type:feats',
      path: 'apps/dashboard/src/features/content/lib/forms/grants/grant-form-fields.ts',
      reason: 'Feat-choice grant eligibility copy owned by grant vocabulary',
      owner: 'dashboard',
    },
    {
      target: 'content-type:feats',
      path: 'packages/ui/src/components/ui/rich-text-link-picker.client.tsx',
      reason: 'Storybook defaults; dashboard passes term-derived options',
      owner: 'ui',
    },
    {
      target: 'content-type:equipment',
      path: 'packages/contracts/src/rpg/content/lib/content-type-terms.ts',
      reason: 'Canonical catalog content-type term registry',
      owner: 'contracts',
    },
    {
      target: 'content-type:equipment',
      path: 'packages/contracts/src/rpg/vocab/equipment/**',
      reason: 'Equipment family/kind/category vocabulary, not parent catalog chrome',
      owner: 'contracts',
    },
    {
      target: 'content-type:equipment',
      path: 'apps/dashboard/src/features/content/equipment/lib/shared/equipment-family-paths.ts',
      reason: 'Equipment family labels; parent equipment term does not substitute here',
      owner: 'dashboard',
    },
    {
      target: 'content-type:equipment',
      path: 'apps/dashboard/src/features/content/equipment/hooks/use-equipment-family-overview.ts',
      reason: 'Family-scoped create labels derived from family headings',
      owner: 'dashboard',
    },
    {
      target: 'content-type:equipment',
      path: 'apps/dashboard/src/features/content/lib/forms/grants/equipment-grant-form-fields.ts',
      reason: 'Equipment kind/category pool filters use equipment taxonomy labels',
      owner: 'dashboard',
    },
    {
      target: 'content-type:equipment',
      path: 'apps/dashboard/src/features/content/classes/lib/character-creation/class-starting-equipment-form-values.ts',
      reason: 'Named starting package label (Standard Equipment), not parent catalog chrome',
      owner: 'dashboard',
    },
    {
      target: 'content-type:equipment',
      path: 'apps/dashboard/src/features/character/lib/equipment-step.fixtures.ts',
      reason: 'Named starting package fixture label (Standard Equipment)',
      owner: 'dashboard',
    },
    {
      target: 'vocab-set:creature-types',
      path: 'packages/contracts/src/rpg/vocab/creature-type.ts',
      reason: 'Vocabulary option-set registry, not a direct term audit target surface',
      owner: 'contracts',
    },
  ],
} as const satisfies TermAuditConfig
