/** @generated by tools/scripts/generate-organization-membership-title-data.mjs — do not edit by hand. */

import type { GameTermEntry } from '../types'

export const ORGANIZATION_MEMBERSHIP_TITLE_ENTRIES = {
  abbot: {
    label: 'Abbot',
    description: 'Head of a monastic community who governs the house and its religious life.',
  },
  accountant: {
    label: 'Accountant',
    description:
      'Officer who maintains ledgers, reconciles accounts, and tracks financial records.',
  },
  acolyte: {
    label: 'Acolyte',
    description: 'Junior attendant in religious service, training for fuller clerical duties.',
  },
  actor: {
    label: 'Actor',
    description: 'Performer who portrays roles in staged productions.',
  },
  adept: {
    label: 'Adept',
    description:
      'Practitioner with proven skill in a specialized magical or devotional discipline.',
  },
  administrator: {
    label: 'Administrator',
    description: 'Officer who manages day-to-day operations, records, and internal procedures.',
  },
  admiral: {
    label: 'Admiral',
    description: 'Flag officer who commands fleet operations and naval strategy.',
  },
  adventurer: {
    label: 'Adventurer',
    description: 'Member who takes contracts for exploration, combat, and treasure recovery.',
  },
  agent: {
    label: 'Agent',
    description: "Representative who acts on the organization's behalf in the field or abroad.",
  },
  analyst: {
    label: 'Analyst',
    description: 'Specialist who evaluates intelligence, data, or reports to inform decisions.',
  },
  apprentice: {
    label: 'Apprentice',
    description: 'Trainee learning a trade or craft under supervision before full membership.',
  },
  archdruid: {
    label: 'Archdruid',
    description: "Supreme guardian of a circle's sacred groves, rites, and natural law.",
  },
  archivist: {
    label: 'Archivist',
    description:
      'Curator responsible for preserving, cataloging, and accessing records and collections.',
  },
  archmage: {
    label: 'Archmage',
    description: 'Preeminent mage who leads arcane study, policy, and high ritual.',
  },
  artisan: {
    label: 'Artisan',
    description: 'Skilled craft worker who produces goods to guild or company standards.',
  },
  assassin: {
    label: 'Assassin',
    description: 'Operative trained to eliminate targets discreetly on assignment.',
  },
  banker: {
    label: 'Banker',
    description: 'Officer who manages deposits, lending, credit, and client accounts.',
  },
  benefactor: {
    label: 'Benefactor',
    description: "Patron who provides funding or resources to support the organization's mission.",
  },
  boatswain: {
    label: 'Boatswain',
    description: 'Petty officer responsible for deck crew, rigging, and shipboard discipline.',
  },
  bodyguard: {
    label: 'Bodyguard',
    description: 'Protector assigned to shield clients, principals, or VIPs from harm.',
  },
  boss: {
    label: 'Boss',
    description: "Top leader who holds final authority over the group's operations and territory.",
  },
  bounty_hunter: {
    label: 'Bounty Hunter',
    description: 'Hunter who pursues fugitives or marks for capture or elimination for pay.',
  },
  brewer: {
    label: 'Brewer',
    description: 'Worker who produces beer or ale through mashing, fermentation, and conditioning.',
  },
  brewmaster: {
    label: 'Brewmaster',
    description: 'Master brewer who directs recipes, quality, and production standards.',
  },
  broker: {
    label: 'Broker',
    description: 'Middleman who negotiates deals, routes goods, or connects buyers and sellers.',
  },
  brother: {
    label: 'Brother',
    description: 'Male vowed member of a religious or fraternal order.',
  },
  buyer: {
    label: 'Buyer',
    description: 'Agent who purchases stolen or fenced goods for resale or laundering.',
  },
  cabin_hand: {
    label: 'Cabin Hand',
    description: 'Junior sailor who tends cabins, mess, and basic shipboard chores.',
  },
  captain: {
    label: 'Captain',
    description:
      'Officer who commands a unit, vessel, or detachment and answers for its performance.',
  },
  caravan_master: {
    label: 'Caravan Master',
    description: 'Leader responsible for route planning, contracts, and safe passage of a caravan.',
  },
  carpenter: {
    label: 'Carpenter',
    description: 'Craft worker who builds and repairs wooden structures, frames, and fittings.',
  },
  cartographer: {
    label: 'Cartographer',
    description: 'Specialist who maps terrain, routes, and geographic features.',
  },
  case_officer: {
    label: 'Case Officer',
    description: 'Handler who manages agents and operations for a specific intelligence case.',
  },
  cashier: {
    label: 'Cashier',
    description: 'Officer who handles daily transactions, till balances, and customer payments.',
  },
  cellarer: {
    label: 'Cellarer',
    description: 'Steward of stored ale, wine, and provisions in cellars and vaults.',
  },
  chair: {
    label: 'Chair',
    description: 'Presiding officer who leads meetings and represents the body in formal business.',
  },
  chancellor: {
    label: 'Chancellor',
    description: 'Chief academic or ceremonial head who sets institutional policy and public face.',
  },
  chief_cartographer: {
    label: 'Chief Cartographer',
    description: 'Senior mapper who directs cartographic work and chart standards.',
  },
  chief_surveyor: {
    label: 'Chief Surveyor',
    description: 'Senior surveyor who oversees measurement, boundaries, and field teams.',
  },
  cleric: {
    label: 'Cleric',
    description:
      'Ordained or dedicated religious functionary who performs rites and pastoral duties.',
  },
  clerk: {
    label: 'Clerk',
    description: 'Record keeper who handles correspondence, filings, and administrative paperwork.',
  },
  collector: {
    label: 'Collector',
    description: 'Enforcer who gathers protection payments, debts, or tribute on assignment.',
  },
  commander: {
    label: 'Commander',
    description: 'Senior officer who directs forces, missions, or major operational units.',
  },
  commissioner: {
    label: 'Commissioner',
    description: 'Senior appointee who oversees a bureau, district, or policy portfolio.',
  },
  commodore: {
    label: 'Commodore',
    description: 'Flag officer who commands squadrons or grouped naval formations.',
  },
  company_manager: {
    label: 'Company Manager',
    description: 'Executive who runs troupe scheduling, budgets, and business affairs.',
  },
  congregant: {
    label: 'Congregant',
    description: 'Lay worshiper affiliated with the congregation without clerical office.',
  },
  constable: {
    label: 'Constable',
    description: 'Law officer who patrols, arrests, and maintains order on assigned beats.',
  },
  cooper: {
    label: 'Cooper',
    description: 'Craft worker who builds and repairs barrels, casks, and wooden vessels.',
  },
  coordinator: {
    label: 'Coordinator',
    description: 'Organizer who schedules volunteers, resources, and cross-team activities.',
  },
  councillor: {
    label: 'Councillor',
    description: 'Elected or appointed member of a governing council.',
  },
  courier: {
    label: 'Courier',
    description: 'Messenger who carries letters, packages, or sensitive items between parties.',
  },
  crew: {
    label: 'Crew',
    description:
      'Rank-and-file sailors or workers who operate a ship or enterprise under officers.',
  },
  cutpurse: {
    label: 'Cutpurse',
    description: 'Pickpocket or thief skilled at lifting coin and valuables in crowds.',
  },
  deacon: {
    label: 'Deacon',
    description: 'Ministerial assistant who supports worship, charity, and parish logistics.',
  },
  dean: {
    label: 'Dean',
    description: 'Academic head who oversees a faculty, college, or major teaching division.',
  },
  delegate: {
    label: 'Delegate',
    description: 'Representative sent to speak or vote on behalf of a constituency or chapter.',
  },
  deputy_director: {
    label: 'Deputy Director',
    description: 'Second-in-command who acts for the director and manages senior staff.',
  },
  detective: {
    label: 'Detective',
    description: 'Investigator who gathers evidence and builds cases on crimes and conspiracies.',
  },
  devotee: {
    label: 'Devotee',
    description:
      "Committed follower who serves the cult's rites and hierarchy without senior rank.",
  },
  director: {
    label: 'Director',
    description: 'Executive who sets strategy and oversees departments or the whole organization.',
  },
  dispatcher: {
    label: 'Dispatcher',
    description: 'Coordinator who assigns routes, loads, and timing for shipments or crews.',
  },
  driver: {
    label: 'Driver',
    description: 'Operator who steers wagons, teams, or vehicles along assigned routes.',
  },
  drover: {
    label: 'Drover',
    description: 'Handler who moves livestock along trails and markets under contract.',
  },
  druid: {
    label: 'Druid',
    description:
      'Nature priest who tends sacred sites, seasonal rites, and the balance of the wild.',
  },
  elder: {
    label: 'Elder',
    description: 'Senior member respected for experience, counsel, and community authority.',
  },
  elder_druid: {
    label: 'Elder Druid',
    description: 'Veteran druid who guides rituals, training, and circle traditions.',
  },
  enforcer: {
    label: 'Enforcer',
    description: 'Strong-arm who compels compliance through intimidation or violence.',
  },
  engineer: {
    label: 'Engineer',
    description:
      'Technical officer who plans works, machinery, and underground or structural operations.',
  },
  engraver: {
    label: 'Engraver',
    description: 'Specialist who cuts plates, dies, and seals used in forgery or mint work.',
  },
  examiner: {
    label: 'Examiner',
    description: 'Officer who inspects testimony, documents, or suspects in formal inquiries.',
  },
  explorer: {
    label: 'Explorer',
    description: 'Member who leads or joins expeditions into unknown or hazardous territory.',
  },
  factor: {
    label: 'Factor',
    description: "Commercial agent who negotiates trade, credit, and goods on the house's account.",
  },
  farm_manager: {
    label: 'Farm Manager',
    description: 'Supervisor who runs daily farm operations, labor, and crop plans.',
  },
  farmer: {
    label: 'Farmer',
    description: 'Member who cultivates land and brings produce to the cooperative.',
  },
  fellow: {
    label: 'Fellow',
    description: 'Senior associate recognized for contribution, tenure, or scholarly standing.',
  },
  fence: {
    label: 'Fence',
    description: 'Receiver who buys stolen goods for resale while hiding their origin.',
  },
  fixer: {
    label: 'Fixer',
    description: 'Connector who arranges deals, alibis, bribes, or logistical workarounds.',
  },
  foreman: {
    label: 'Foreman',
    description: 'Supervisor who directs crews, enforces quotas, and reports to management.',
  },
  forger: {
    label: 'Forger',
    description: 'Counterfeiter who produces false documents, coin, or credentials.',
  },
  general: {
    label: 'General',
    description: 'Highest field commander responsible for campaign strategy and army disposition.',
  },
  grand_inquisitor: {
    label: 'Grand Inquisitor',
    description: 'Supreme judge of heresy and doctrine who leads the inquisition.',
  },
  grand_master: {
    label: 'Grand Master',
    description: 'Head of an order who holds supreme authority over its rule and missions.',
  },
  grandmaster: {
    label: 'Grandmaster',
    description:
      'Supreme leader of a secret or martial order, setting doctrine and elite assignments.',
  },
  grower: {
    label: 'Grower',
    description: 'Producer who raises crops or specialty plants for the cooperative.',
  },
  guard: {
    label: 'Guard',
    description: 'Security member who protects sites, convoys, or principals on assignment.',
  },
  guide: {
    label: 'Guide',
    description: 'Pathfinder who leads travelers safely through wilderness or trade routes.',
  },
  guild_steward: {
    label: 'Guild Steward',
    description: 'Guild officer who manages funds, hall affairs, and member disputes.',
  },
  guildmaster: {
    label: 'Guildmaster',
    description: 'Elected or ruling head of a guild who speaks for its craft and membership.',
  },
  gunner: {
    label: 'Gunner',
    description:
      'Artillerist or deck fighter responsible for cannon, siege weapons, or heavy arms.',
  },
  handler: {
    label: 'Handler',
    description: 'Controller who directs field agents, assets, and operational cover.',
  },
  healer: {
    label: 'Healer',
    description: 'Practitioner who treats injuries and illness through medicine or sacred care.',
  },
  hierophant: {
    label: 'Hierophant',
    description: 'Interpreter of mysteries who leads esoteric rites and hidden doctrine.',
  },
  high_inquisitor: {
    label: 'High Inquisitor',
    description: 'Senior inquisitor who supervises tribunals and pursuit of heresy.',
  },
  high_priest: {
    label: 'High Priest',
    description: 'Chief priest who presides over major rites and spiritual authority.',
  },
  hospitaller: {
    label: 'Hospitaller',
    description: 'Caregiver who tends the sick, wounded, and pilgrims in hospital service.',
  },
  huntmaster: {
    label: 'Huntmaster',
    description: 'Leader who assigns hunts, tracks quarries, and trains bounty teams.',
  },
  informant: {
    label: 'Informant',
    description: 'Source who provides intelligence covertly, often for payment or protection.',
  },
  initiate: {
    label: 'Initiate',
    description: 'New member undergoing probation or training before full standing.',
  },
  inquisitor: {
    label: 'Inquisitor',
    description: 'Investigator of heresy, treason, or doctrinal crime with judicial power.',
  },
  inspector: {
    label: 'Inspector',
    description: 'Official who audits compliance, standards, and conduct in the field.',
  },
  instructor: {
    label: 'Instructor',
    description: 'Teacher who delivers lessons, drills, or practical training to students.',
  },
  interrogator: {
    label: 'Interrogator',
    description: 'Specialist who extracts confessions and intelligence through questioning.',
  },
  investigator: {
    label: 'Investigator',
    description: 'Officer who examines crimes, leads inquiries, and builds cases.',
  },
  journeyman: {
    label: 'Journeyman',
    description: 'Qualified craft worker who may travel and take paid jobs between mastership.',
  },
  keeper: {
    label: 'Keeper',
    description: 'Guardian responsible for sacred places, relics, or stored knowledge.',
  },
  knight: {
    label: 'Knight',
    description: "Armored warrior sworn to the order's code, missions, and chain of command.",
  },
  knight_captain: {
    label: 'Knight Captain',
    description: 'Knight who commands a lance, squad, or detachment of brother knights.',
  },
  knight_commander: {
    label: 'Knight Commander',
    description: 'Senior knight who leads multiple companies or a major commandery.',
  },
  laborer: {
    label: 'Laborer',
    description: 'Unskilled or general worker who performs heavy or manual tasks.',
  },
  lay_worker: {
    label: 'Lay Worker',
    description: 'Non-ordained helper who supports missions through practical service.',
  },
  lead_actor: {
    label: 'Lead Actor',
    description: 'Principal performer who carries starring roles in productions.',
  },
  lecturer: {
    label: 'Lecturer',
    description: 'Academic who teaches courses and presents material to students.',
  },
  lieutenant: {
    label: 'Lieutenant',
    description: 'Deputy commander who leads subunits and executes orders from superiors.',
  },
  logger: {
    label: 'Logger',
    description: 'Worker who fells timber and prepares logs for transport or milling.',
  },
  lookout: {
    label: 'Lookout',
    description: 'Sentinel who watches for threats, law enforcement, or rival gangs.',
  },
  mage: {
    label: 'Mage',
    description: 'Practitioner of arcane arts who studies or applies structured spellcraft.',
  },
  manager: {
    label: 'Manager',
    description: 'Supervisor who runs a site, team, or business line day to day.',
  },
  marine: {
    label: 'Marine',
    description: 'Soldier embarked for naval service, boarding actions, and ship defense.',
  },
  marshal: {
    label: 'Marshal',
    description: 'Senior officer who enforces discipline, law, or military order across a command.',
  },
  master: {
    label: 'Master',
    description: 'Senior practitioner or lodge officer with authority over craft or chapter work.',
  },
  master_artisan: {
    label: 'Master Artisan',
    description: "Recognized expert whose work sets the guild's quality benchmark.",
  },
  master_assassin: {
    label: 'Master Assassin',
    description: 'Elite killer who trains operatives and takes the most sensitive contracts.',
  },
  master_fence: {
    label: 'Master Fence',
    description: 'Senior receiver who runs laundering networks and sets prices for stolen goods.',
  },
  master_forger: {
    label: 'Master Forger',
    description: 'Lead counterfeiter who designs plates, inks, and false instruments.',
  },
  master_healer: {
    label: 'Master Healer',
    description: 'Chief healer who sets medical practice, training, and hospital standards.',
  },
  master_thief: {
    label: 'Master Thief',
    description: 'Elite thief who plans scores and mentors apprentices in the guild.',
  },
  matriarch: {
    label: 'Matriarch',
    description: 'Female head of a merchant house who holds familial and commercial authority.',
  },
  member: {
    label: 'Member',
    description: 'Rank-and-file participant with full standing but no formal office.',
  },
  mercenary: {
    label: 'Mercenary',
    description: 'Paid fighter who sells martial service by contract rather than oath alone.',
  },
  merchant: {
    label: 'Merchant',
    description: 'Trader who buys, sells, and negotiates goods across markets.',
  },
  militiaman: {
    label: 'Militiaman',
    description: 'Part-time or local fighter mustered for community defense.',
  },
  mine_captain: {
    label: 'Mine Captain',
    description: 'Officer who commands underground operations and mine safety.',
  },
  miner: {
    label: 'Miner',
    description: 'Worker who extracts ore, stone, or gems from tunnels and pits.',
  },
  minister: {
    label: 'Minister',
    description: 'Senior political or religious officer who leads policy or pastoral care.',
  },
  mission_director: {
    label: 'Mission Director',
    description: 'Executive who plans missions, funding, and field deployments abroad.',
  },
  missionary: {
    label: 'Missionary',
    description: 'Envoy who spreads faith, aid, or doctrine in foreign communities.',
  },
  musician: {
    label: 'Musician',
    description: 'Performer who provides music for productions or ceremonies.',
  },
  navigator: {
    label: 'Navigator',
    description: 'Specialist who charts courses, reads stars, and guides vessels.',
  },
  novice: {
    label: 'Novice',
    description: 'Postulant in early religious training before taking vows or full duties.',
  },
  officer: {
    label: 'Officer',
    description:
      'Appointed official who executes policy, commands staff, or holds portfolio duties.',
  },
  operative: {
    label: 'Operative',
    description: 'Field agent who carries out covert tasks, theft, or intelligence work.',
  },
  oracle: {
    label: 'Oracle',
    description: 'Seer who interprets omens and speaks prophetic counsel to the cult.',
  },
  organizer: {
    label: 'Organizer',
    description: 'Activist who recruits, mobilizes members, and runs campaigns or chapters.',
  },
  party_leader: {
    label: 'Party Leader',
    description: 'Head of a political party who sets platform and electoral strategy.',
  },
  passer: {
    label: 'Passer',
    description: 'Runner who puts forged currency or documents into circulation.',
  },
  patriarch: {
    label: 'Patriarch',
    description: 'Male head of a merchant house who holds familial and commercial authority.',
  },
  physician: {
    label: 'Physician',
    description: 'Medical doctor who diagnoses illness and directs treatment.',
  },
  pirate: {
    label: 'Pirate',
    description: "Sea raider who attacks merchant traffic for plunder under the crew's banner.",
  },
  playwright: {
    label: 'Playwright',
    description: 'Writer who authors scripts and dramatic works for the troupe.',
  },
  preacher: {
    label: 'Preacher',
    description: 'Speaker who delivers sermons and evangelizes in the field.',
  },
  president: {
    label: 'President',
    description: 'Elected or appointed head who chairs governance and external representation.',
  },
  priest: {
    label: 'Priest',
    description: 'Religious minister who leads worship, sacraments, and pastoral care.',
  },
  printer: {
    label: 'Printer',
    description: 'Worker who runs presses to produce false bills, pamphlets, or documents.',
  },
  prior: {
    label: 'Prior',
    description: 'Deputy abbot or second who manages daily monastic administration.',
  },
  professor: {
    label: 'Professor',
    description: 'Senior academic who teaches advanced subjects and mentors scholars.',
  },
  proprietor: {
    label: 'Proprietor',
    description: 'Owner who holds ultimate authority over the business and its assets.',
  },
  prospector: {
    label: 'Prospector',
    description: 'Scout who searches for new veins, claims, or profitable dig sites.',
  },
  quartermaster: {
    label: 'Quartermaster',
    description: 'Officer responsible for supplies, stores, equipment, and logistics.',
  },
  recruit: {
    label: 'Recruit',
    description: 'New enlistee in basic training before earning full member standing.',
  },
  rector: {
    label: 'Rector',
    description: 'Chief executive of an academic institution who governs faculty and affairs.',
  },
  representative: {
    label: 'Representative',
    description: 'Member who speaks or votes for a district, chapter, or constituency.',
  },
  research_director: {
    label: 'Research Director',
    description: 'Leader who sets research agendas, grants, and scholarly programs.',
  },
  researcher: {
    label: 'Researcher',
    description: 'Scholar or scientist who conducts systematic inquiry and publishes findings.',
  },
  rigger: {
    label: 'Rigger',
    description: 'Worker who handles ropes, masts, rigging, and heavy lifting on ships or yards.',
  },
  ringleader: {
    label: 'Ringleader',
    description: 'Criminal chief who orchestrates schemes and commands the network.',
  },
  runner: {
    label: 'Runner',
    description: 'Courier or errand agent who moves messages, goods, or payments quickly.',
  },
  sailing_master: {
    label: 'Sailing Master',
    description: 'Senior warrant officer who navigates, drives the ship, and advises the captain.',
  },
  sailor: {
    label: 'Sailor',
    description: "Seafarer who works decks, lines, and watches under ship's officers.",
  },
  sawyer: {
    label: 'Sawyer',
    description: 'Worker who saws logs into lumber at mill or camp.',
  },
  scholar: {
    label: 'Scholar',
    description: 'Learned member devoted to study, commentary, and academic discourse.',
  },
  scout: {
    label: 'Scout',
    description: 'Skilled observer who reconnoiters terrain, enemies, or opportunities ahead.',
  },
  secretary: {
    label: 'Secretary',
    description: 'Officer who maintains minutes, correspondence, and organizational records.',
  },
  security_chief: {
    label: 'Security Chief',
    description: 'Head of protective services who designs security posture and teams.',
  },
  senator: {
    label: 'Senator',
    description: 'Senior legislator who deliberates and votes in a governing senate.',
  },
  sergeant: {
    label: 'Sergeant',
    description: 'Noncommissioned officer who leads small teams and enforces discipline.',
  },
  shipping_master: {
    label: 'Shipping Master',
    description: 'Executive who oversees fleets, cargoes, and maritime contracts.',
  },
  shipwright: {
    label: 'Shipwright',
    description: 'Craft worker who builds and repairs hulls, decks, and fittings.',
  },
  shipwright_master: {
    label: 'Shipwright Master',
    description: 'Master shipbuilder who directs design, yard standards, and major refits.',
  },
  shop_steward: {
    label: 'Shop Steward',
    description: 'Union representative who advocates for workers on the shop floor.',
  },
  sister: {
    label: 'Sister',
    description: 'Female vowed member of a religious or fraternal order.',
  },
  smuggler: {
    label: 'Smuggler',
    description: 'Contraband runner who moves illegal goods past customs and patrols.',
  },
  soldier: {
    label: 'Soldier',
    description: 'Enlisted fighter who serves in the rank and file of a military unit.',
  },
  speaker: {
    label: 'Speaker',
    description: 'Presiding officer who conducts legislative sessions and maintains order.',
  },
  spymaster: {
    label: 'Spymaster',
    description: 'Intelligence chief who directs networks, handlers, and covert collection.',
  },
  squire: {
    label: 'Squire',
    description: "Knight's attendant training in arms, service, and knightly conduct.",
  },
  stagehand: {
    label: 'Stagehand',
    description: 'Crew member who shifts sets, props, and backstage logistics.',
  },
  steward: {
    label: 'Steward',
    description: 'Officer who manages property, provisions, treasury, or household affairs.',
  },
  student: {
    label: 'Student',
    description: 'Learner enrolled in courses who has not yet earned full academic standing.',
  },
  supervisor: {
    label: 'Supervisor',
    description: 'Overseer who monitors shifts, quality, and adherence to procedures.',
  },
  surgeon: {
    label: 'Surgeon',
    description: 'Physician specialized in operative treatment of wounds and illness.',
  },
  surveyor: {
    label: 'Surveyor',
    description: 'Measurer who maps land, claims, timber stands, or construction sites.',
  },
  teamster: {
    label: 'Teamster',
    description: 'Driver who hauls loads with draft animals or heavy wagons.',
  },
  timber_master: {
    label: 'Timber Master',
    description: 'Forestry officer who plans cuts, quotas, and timber sales.',
  },
  tracker: {
    label: 'Tracker',
    description: 'Hunter who follows trails and signs to locate people or beasts.',
  },
  translator: {
    label: 'Translator',
    description: 'Linguist who converts speech and texts for missions abroad.',
  },
  treasurer: {
    label: 'Treasurer',
    description: 'Officer responsible for funds, budgets, collections, and disbursements.',
  },
  trustee: {
    label: 'Trustee',
    description: 'Fiduciary who oversees endowment, governance, and charitable compliance.',
  },
  veteran: {
    label: 'Veteran',
    description: 'Experienced member recognized for surviving many contracts or campaigns.',
  },
  volunteer: {
    label: 'Volunteer',
    description: "Unpaid helper who contributes time to the organization's programs.",
  },
  warden: {
    label: 'Warden',
    description: 'Guardian who protects a site, order house, or sacred boundary.',
  },
  watch_commander: {
    label: 'Watch Commander',
    description: 'Officer who commands city watch posts, patrols, and emergency response.',
  },
  yardmaster: {
    label: 'Yardmaster',
    description: 'Supervisor who schedules work, materials, and labor in a shipyard.',
  },
} as const satisfies Record<string, GameTermEntry>

export type OrganizationMembershipTitleId = keyof typeof ORGANIZATION_MEMBERSHIP_TITLE_ENTRIES
