/** @generated by tools/scripts/generate-organization-membership-title-data.mjs — do not edit by hand. */

import type { OrganizationMembershipTitleId } from './membership-title-entries'
import type { NpcAuthoringTemplateId } from './npc-authoring-template'

export type OrganizationPresetMembershipTitleRef = {
  readonly titleId: OrganizationMembershipTitleId
  readonly priority: number
  readonly npcRecommendation?: {
    readonly templateId: NpcAuthoringTemplateId
    readonly level: number
  }
}

export const ORGANIZATION_PRESET_MEMBERSHIP_TITLE_REFS = {
  academy: [
    {
      titleId: 'chancellor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'rector',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    { titleId: 'dean', priority: 40, npcRecommendation: { templateId: 'administrator', level: 4 } },
    { titleId: 'professor', priority: 30, npcRecommendation: { templateId: 'scholar', level: 4 } },
    { titleId: 'instructor', priority: 30, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'researcher', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'scholar', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'student', priority: 10, npcRecommendation: { templateId: 'scholar', level: 0 } },
  ],
  adventurers_guild: [
    {
      titleId: 'guildmaster',
      priority: 50,
      npcRecommendation: { templateId: 'martial_commander', level: 8 },
    },
    {
      titleId: 'captain',
      priority: 40,
      npcRecommendation: { templateId: 'martial_officer', level: 6 },
    },
    {
      titleId: 'quartermaster',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'veteran',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 5 },
    },
    {
      titleId: 'adventurer',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 3 },
    },
    { titleId: 'scout', priority: 20, npcRecommendation: { templateId: 'scout', level: 3 } },
    {
      titleId: 'member',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 2 },
    },
    { titleId: 'recruit', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  army: [
    {
      titleId: 'general',
      priority: 50,
      npcRecommendation: { templateId: 'martial_commander', level: 14 },
    },
    {
      titleId: 'marshal',
      priority: 50,
      npcRecommendation: { templateId: 'martial_commander', level: 13 },
    },
    {
      titleId: 'commander',
      priority: 40,
      npcRecommendation: { templateId: 'martial_commander', level: 10 },
    },
    {
      titleId: 'captain',
      priority: 40,
      npcRecommendation: { templateId: 'martial_officer', level: 6 },
    },
    {
      titleId: 'lieutenant',
      priority: 30,
      npcRecommendation: { templateId: 'martial_officer', level: 6 },
    },
    {
      titleId: 'sergeant',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 4 },
    },
    { titleId: 'soldier', priority: 10, npcRecommendation: { templateId: 'guard', level: 2 } },
    { titleId: 'recruit', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  bank: [
    {
      titleId: 'treasurer',
      priority: 50,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    { titleId: 'banker', priority: 40, npcRecommendation: { templateId: 'merchant', level: 2 } },
    {
      titleId: 'manager',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'cashier',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 0 },
    },
    {
      titleId: 'accountant',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 1 },
    },
    {
      titleId: 'clerk',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 0 },
    },
  ],
  church: [
    {
      titleId: 'high_priest',
      priority: 50,
      npcRecommendation: { templateId: 'divine_practitioner', level: 10 },
    },
    {
      titleId: 'priest',
      priority: 40,
      npcRecommendation: { templateId: 'divine_practitioner', level: 5 },
    },
    {
      titleId: 'elder',
      priority: 40,
      npcRecommendation: { templateId: 'divine_practitioner', level: 6 },
    },
    {
      titleId: 'minister',
      priority: 30,
      npcRecommendation: { templateId: 'divine_practitioner', level: 4 },
    },
    {
      titleId: 'deacon',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'cleric',
      priority: 20,
      npcRecommendation: { templateId: 'divine_practitioner', level: 3 },
    },
    {
      titleId: 'acolyte',
      priority: 10,
      npcRecommendation: { templateId: 'divine_practitioner', level: 1 },
    },
    {
      titleId: 'congregant',
      priority: 10,
      npcRecommendation: { templateId: 'civilian', level: 0 },
    },
  ],
  city_council: [
    { titleId: 'chair', priority: 50, npcRecommendation: { templateId: 'civic_leader', level: 0 } },
    {
      titleId: 'speaker',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'councillor',
      priority: 30,
      npcRecommendation: { templateId: 'civilian', level: 0 },
    },
    {
      titleId: 'senator',
      priority: 30,
      npcRecommendation: { templateId: 'civic_leader', level: 4 },
    },
    {
      titleId: 'representative',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 1 },
    },
    {
      titleId: 'delegate',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 1 },
    },
    {
      titleId: 'clerk',
      priority: 10,
      npcRecommendation: { templateId: 'administrator', level: 0 },
    },
  ],
  city_watch: [
    {
      titleId: 'watch_commander',
      priority: 50,
      npcRecommendation: { templateId: 'martial_commander', level: 9 },
    },
    {
      titleId: 'captain',
      priority: 40,
      npcRecommendation: { templateId: 'martial_officer', level: 6 },
    },
    {
      titleId: 'marshal',
      priority: 40,
      npcRecommendation: { templateId: 'martial_commander', level: 10 },
    },
    {
      titleId: 'lieutenant',
      priority: 30,
      npcRecommendation: { templateId: 'martial_officer', level: 5 },
    },
    {
      titleId: 'sergeant',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 4 },
    },
    {
      titleId: 'investigator',
      priority: 20,
      npcRecommendation: { templateId: 'investigator', level: 4 },
    },
    {
      titleId: 'detective',
      priority: 20,
      npcRecommendation: { templateId: 'investigator', level: 5 },
    },
    { titleId: 'constable', priority: 10, npcRecommendation: { templateId: 'guard', level: 2 } },
  ],
  craft_guild: [
    {
      titleId: 'guildmaster',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 8 },
    },
    {
      titleId: 'master_artisan',
      priority: 40,
      npcRecommendation: { templateId: 'artisan', level: 5 },
    },
    {
      titleId: 'guild_steward',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    { titleId: 'journeyman', priority: 30, npcRecommendation: { templateId: 'artisan', level: 2 } },
    { titleId: 'artisan', priority: 20, npcRecommendation: { templateId: 'artisan', level: 2 } },
    { titleId: 'member', priority: 20, npcRecommendation: { templateId: 'civilian', level: 0 } },
    { titleId: 'apprentice', priority: 10, npcRecommendation: { templateId: 'artisan', level: 1 } },
  ],
  gang: [
    {
      titleId: 'boss',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 8 },
    },
    {
      titleId: 'lieutenant',
      priority: 40,
      npcRecommendation: { templateId: 'covert_operator', level: 6 },
    },
    {
      titleId: 'enforcer',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 5 },
    },
    { titleId: 'lookout', priority: 20, npcRecommendation: { templateId: 'scout', level: 2 } },
    {
      titleId: 'runner',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    {
      titleId: 'member',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 2 },
    },
    { titleId: 'recruit', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  government_ministry: [
    {
      titleId: 'minister',
      priority: 50,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    {
      titleId: 'secretary',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'commissioner',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    {
      titleId: 'director',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    {
      titleId: 'administrator',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'inspector',
      priority: 20,
      npcRecommendation: { templateId: 'investigator', level: 4 },
    },
    {
      titleId: 'officer',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'clerk',
      priority: 10,
      npcRecommendation: { templateId: 'administrator', level: 0 },
    },
  ],
  knightly_order: [
    {
      titleId: 'grand_master',
      priority: 50,
      npcRecommendation: { templateId: 'martial_commander', level: 12 },
    },
    {
      titleId: 'knight_commander',
      priority: 40,
      npcRecommendation: { templateId: 'martial_commander', level: 10 },
    },
    {
      titleId: 'knight_captain',
      priority: 40,
      npcRecommendation: { templateId: 'martial_officer', level: 7 },
    },
    {
      titleId: 'knight',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 5 },
    },
    {
      titleId: 'sergeant',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 4 },
    },
    { titleId: 'squire', priority: 10, npcRecommendation: { templateId: 'guard', level: 2 } },
    { titleId: 'initiate', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  mercenary_company: [
    {
      titleId: 'captain',
      priority: 50,
      npcRecommendation: { templateId: 'martial_officer', level: 7 },
    },
    {
      titleId: 'commander',
      priority: 40,
      npcRecommendation: { templateId: 'martial_commander', level: 9 },
    },
    {
      titleId: 'lieutenant',
      priority: 30,
      npcRecommendation: { templateId: 'martial_officer', level: 5 },
    },
    {
      titleId: 'sergeant',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 4 },
    },
    {
      titleId: 'mercenary',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 4 },
    },
    { titleId: 'scout', priority: 20, npcRecommendation: { templateId: 'scout', level: 3 } },
    { titleId: 'recruit', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  mutual_aid_society: [
    {
      titleId: 'president',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    { titleId: 'chair', priority: 40, npcRecommendation: { templateId: 'civic_leader', level: 0 } },
    {
      titleId: 'steward',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'coordinator',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 1 },
    },
    { titleId: 'volunteer', priority: 20, npcRecommendation: { templateId: 'civilian', level: 0 } },
    { titleId: 'member', priority: 20, npcRecommendation: { templateId: 'civilian', level: 0 } },
    {
      titleId: 'benefactor',
      priority: 20,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
  ],
  political_party: [
    {
      titleId: 'party_leader',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 8 },
    },
    { titleId: 'chair', priority: 40, npcRecommendation: { templateId: 'civic_leader', level: 0 } },
    {
      titleId: 'secretary',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'organizer',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'representative',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 1 },
    },
    {
      titleId: 'delegate',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 1 },
    },
    { titleId: 'member', priority: 10, npcRecommendation: { templateId: 'civilian', level: 0 } },
  ],
  religious_order: [
    {
      titleId: 'grand_master',
      priority: 50,
      npcRecommendation: { templateId: 'divine_practitioner', level: 12 },
    },
    {
      titleId: 'prior',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    {
      titleId: 'abbot',
      priority: 40,
      npcRecommendation: { templateId: 'divine_practitioner', level: 8 },
    },
    {
      titleId: 'elder',
      priority: 30,
      npcRecommendation: { templateId: 'divine_practitioner', level: 5 },
    },
    { titleId: 'brother', priority: 20, npcRecommendation: { templateId: 'civilian', level: 0 } },
    { titleId: 'sister', priority: 20, npcRecommendation: { templateId: 'civilian', level: 0 } },
    {
      titleId: 'novice',
      priority: 10,
      npcRecommendation: { templateId: 'divine_practitioner', level: 1 },
    },
    {
      titleId: 'initiate',
      priority: 10,
      npcRecommendation: { templateId: 'divine_practitioner', level: 1 },
    },
  ],
  scholarly_society: [
    {
      titleId: 'president',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    { titleId: 'chair', priority: 40, npcRecommendation: { templateId: 'civic_leader', level: 0 } },
    {
      titleId: 'research_director',
      priority: 40,
      npcRecommendation: { templateId: 'civilian', level: 0 },
    },
    { titleId: 'researcher', priority: 30, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'scholar', priority: 30, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'archivist', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'fellow', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'member', priority: 10, npcRecommendation: { templateId: 'civilian', level: 0 } },
  ],
  shipping_company: [
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'shipping_master',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 4 },
    },
    {
      titleId: 'captain',
      priority: 40,
      npcRecommendation: { templateId: 'maritime_officer', level: 6 },
    },
    {
      titleId: 'dispatcher',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'navigator',
      priority: 30,
      npcRecommendation: { templateId: 'technical_specialist', level: 4 },
    },
    {
      titleId: 'courier',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    { titleId: 'crew', priority: 20, npcRecommendation: { templateId: 'maritime_crew', level: 2 } },
    {
      titleId: 'clerk',
      priority: 10,
      npcRecommendation: { templateId: 'administrator', level: 0 },
    },
  ],
  smuggling_ring: [
    {
      titleId: 'ringleader',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 8 },
    },
    {
      titleId: 'lieutenant',
      priority: 40,
      npcRecommendation: { templateId: 'covert_operator', level: 6 },
    },
    {
      titleId: 'smuggler',
      priority: 30,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    {
      titleId: 'fixer',
      priority: 30,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    {
      titleId: 'courier',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    {
      titleId: 'runner',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    { titleId: 'lookout', priority: 10, npcRecommendation: { templateId: 'scout', level: 2 } },
  ],
  thieves_guild: [
    {
      titleId: 'guildmaster',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 9 },
    },
    {
      titleId: 'master_thief',
      priority: 40,
      npcRecommendation: { templateId: 'covert_operator', level: 9 },
    },
    {
      titleId: 'lieutenant',
      priority: 40,
      npcRecommendation: { templateId: 'covert_operator', level: 6 },
    },
    {
      titleId: 'enforcer',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 5 },
    },
    {
      titleId: 'operative',
      priority: 30,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    {
      titleId: 'cutpurse',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 2 },
    },
    {
      titleId: 'member',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 2 },
    },
    {
      titleId: 'apprentice',
      priority: 10,
      npcRecommendation: { templateId: 'covert_operator', level: 1 },
    },
  ],
  trading_company: [
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'director',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    { titleId: 'factor', priority: 40, npcRecommendation: { templateId: 'merchant', level: 3 } },
    { titleId: 'merchant', priority: 30, npcRecommendation: { templateId: 'merchant', level: 0 } },
    {
      titleId: 'manager',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    { titleId: 'agent', priority: 20, npcRecommendation: { templateId: 'merchant', level: 2 } },
    {
      titleId: 'clerk',
      priority: 10,
      npcRecommendation: { templateId: 'administrator', level: 0 },
    },
  ],
  assassins_order: [
    {
      titleId: 'grandmaster',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 12 },
    },
    {
      titleId: 'master_assassin',
      priority: 40,
      npcRecommendation: { templateId: 'covert_operator', level: 9 },
    },
    {
      titleId: 'handler',
      priority: 30,
      npcRecommendation: { templateId: 'covert_operator', level: 6 },
    },
    {
      titleId: 'assassin',
      priority: 30,
      npcRecommendation: { templateId: 'covert_operator', level: 5 },
    },
    {
      titleId: 'operative',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    {
      titleId: 'agent',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 3 },
    },
    {
      titleId: 'initiate',
      priority: 10,
      npcRecommendation: { templateId: 'covert_operator', level: 1 },
    },
  ],
  bounty_hunters: [
    {
      titleId: 'guildmaster',
      priority: 50,
      npcRecommendation: { templateId: 'martial_officer', level: 8 },
    },
    {
      titleId: 'huntmaster',
      priority: 40,
      npcRecommendation: { templateId: 'martial_officer', level: 7 },
    },
    {
      titleId: 'bounty_hunter',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 5 },
    },
    { titleId: 'tracker', priority: 30, npcRecommendation: { templateId: 'scout', level: 4 } },
    {
      titleId: 'investigator',
      priority: 20,
      npcRecommendation: { templateId: 'investigator', level: 4 },
    },
    { titleId: 'scout', priority: 20, npcRecommendation: { templateId: 'scout', level: 3 } },
    { titleId: 'recruit', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  brewery: [
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    { titleId: 'brewmaster', priority: 40, npcRecommendation: { templateId: 'artisan', level: 0 } },
    {
      titleId: 'manager',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    { titleId: 'brewer', priority: 30, npcRecommendation: { templateId: 'artisan', level: 1 } },
    {
      titleId: 'cellarer',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    { titleId: 'cooper', priority: 20, npcRecommendation: { templateId: 'artisan', level: 1 } },
    {
      titleId: 'laborer',
      priority: 10,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
  ],
  caravan_company: [
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'caravan_master',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 4 },
    },
    {
      titleId: 'quartermaster',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    { titleId: 'guide', priority: 30, npcRecommendation: { templateId: 'scout', level: 3 } },
    { titleId: 'guard', priority: 20, npcRecommendation: { templateId: 'guard', level: 3 } },
    {
      titleId: 'driver',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    {
      titleId: 'drover',
      priority: 10,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
  ],
  charitable_foundation: [
    {
      titleId: 'director',
      priority: 50,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    {
      titleId: 'trustee',
      priority: 40,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'steward',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'administrator',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'benefactor',
      priority: 20,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'coordinator',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 1 },
    },
    { titleId: 'volunteer', priority: 10, npcRecommendation: { templateId: 'civilian', level: 0 } },
  ],
  counterfeiting_ring: [
    {
      titleId: 'ringleader',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 8 },
    },
    {
      titleId: 'master_forger',
      priority: 40,
      npcRecommendation: { templateId: 'artisan', level: 6 },
    },
    { titleId: 'engraver', priority: 30, npcRecommendation: { templateId: 'artisan', level: 2 } },
    { titleId: 'forger', priority: 30, npcRecommendation: { templateId: 'artisan', level: 3 } },
    { titleId: 'printer', priority: 20, npcRecommendation: { templateId: 'artisan', level: 2 } },
    {
      titleId: 'passer',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 2 },
    },
    {
      titleId: 'runner',
      priority: 10,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
  ],
  cult: [
    {
      titleId: 'high_priest',
      priority: 50,
      npcRecommendation: { templateId: 'divine_practitioner', level: 10 },
    },
    {
      titleId: 'hierophant',
      priority: 40,
      npcRecommendation: { templateId: 'divine_practitioner', level: 8 },
    },
    {
      titleId: 'priest',
      priority: 30,
      npcRecommendation: { templateId: 'divine_practitioner', level: 5 },
    },
    {
      titleId: 'oracle',
      priority: 30,
      npcRecommendation: { templateId: 'divine_practitioner', level: 6 },
    },
    {
      titleId: 'adept',
      priority: 20,
      npcRecommendation: { templateId: 'arcane_practitioner', level: 2 },
    },
    { titleId: 'devotee', priority: 20, npcRecommendation: { templateId: 'civilian', level: 0 } },
    {
      titleId: 'initiate',
      priority: 10,
      npcRecommendation: { templateId: 'divine_practitioner', level: 1 },
    },
  ],
  druid_circle: [
    {
      titleId: 'archdruid',
      priority: 50,
      npcRecommendation: { templateId: 'nature_practitioner', level: 14 },
    },
    {
      titleId: 'elder_druid',
      priority: 40,
      npcRecommendation: { templateId: 'nature_practitioner', level: 10 },
    },
    {
      titleId: 'druid',
      priority: 30,
      npcRecommendation: { templateId: 'nature_practitioner', level: 5 },
    },
    {
      titleId: 'warden',
      priority: 30,
      npcRecommendation: { templateId: 'nature_practitioner', level: 4 },
    },
    {
      titleId: 'keeper',
      priority: 20,
      npcRecommendation: { templateId: 'nature_practitioner', level: 3 },
    },
    {
      titleId: 'acolyte',
      priority: 20,
      npcRecommendation: { templateId: 'nature_practitioner', level: 1 },
    },
    {
      titleId: 'initiate',
      priority: 10,
      npcRecommendation: { templateId: 'nature_practitioner', level: 1 },
    },
  ],
  explorers_society: [
    {
      titleId: 'president',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'chief_cartographer',
      priority: 40,
      npcRecommendation: { templateId: 'scholar', level: 6 },
    },
    {
      titleId: 'chief_surveyor',
      priority: 40,
      npcRecommendation: { templateId: 'technical_specialist', level: 6 },
    },
    {
      titleId: 'cartographer',
      priority: 30,
      npcRecommendation: { templateId: 'scholar', level: 2 },
    },
    {
      titleId: 'surveyor',
      priority: 30,
      npcRecommendation: { templateId: 'technical_specialist', level: 3 },
    },
    { titleId: 'explorer', priority: 20, npcRecommendation: { templateId: 'scout', level: 3 } },
    { titleId: 'fellow', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'member', priority: 10, npcRecommendation: { templateId: 'civilian', level: 0 } },
  ],
  farming_cooperative: [
    { titleId: 'chair', priority: 50, npcRecommendation: { templateId: 'civic_leader', level: 0 } },
    {
      titleId: 'steward',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'farm_manager',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'farmer',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    {
      titleId: 'grower',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    { titleId: 'member', priority: 20, npcRecommendation: { templateId: 'civilian', level: 0 } },
    {
      titleId: 'laborer',
      priority: 10,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
  ],
  fencing_network: [
    {
      titleId: 'ringleader',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 8 },
    },
    {
      titleId: 'master_fence',
      priority: 40,
      npcRecommendation: { templateId: 'merchant', level: 5 },
    },
    { titleId: 'fence', priority: 30, npcRecommendation: { templateId: 'merchant', level: 3 } },
    { titleId: 'broker', priority: 30, npcRecommendation: { templateId: 'merchant', level: 2 } },
    { titleId: 'buyer', priority: 20, npcRecommendation: { templateId: 'merchant', level: 1 } },
    {
      titleId: 'runner',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    { titleId: 'lookout', priority: 10, npcRecommendation: { templateId: 'scout', level: 2 } },
  ],
  fraternal_lodge: [
    {
      titleId: 'grand_master',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 10 },
    },
    { titleId: 'master', priority: 40, npcRecommendation: { templateId: 'artisan', level: 4 } },
    {
      titleId: 'warden',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'steward',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    { titleId: 'brother', priority: 20, npcRecommendation: { templateId: 'civilian', level: 0 } },
    { titleId: 'fellow', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'initiate', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  hospital_order: [
    {
      titleId: 'grand_master',
      priority: 50,
      npcRecommendation: { templateId: 'divine_practitioner', level: 10 },
    },
    {
      titleId: 'prior',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    {
      titleId: 'master_healer',
      priority: 40,
      npcRecommendation: { templateId: 'healer', level: 8 },
    },
    { titleId: 'physician', priority: 30, npcRecommendation: { templateId: 'healer', level: 5 } },
    { titleId: 'surgeon', priority: 30, npcRecommendation: { templateId: 'healer', level: 6 } },
    { titleId: 'healer', priority: 20, npcRecommendation: { templateId: 'healer', level: 4 } },
    { titleId: 'hospitaller', priority: 20, npcRecommendation: { templateId: 'healer', level: 3 } },
    {
      titleId: 'novice',
      priority: 10,
      npcRecommendation: { templateId: 'divine_practitioner', level: 1 },
    },
  ],
  inquisition: [
    {
      titleId: 'grand_inquisitor',
      priority: 50,
      npcRecommendation: { templateId: 'investigator', level: 12 },
    },
    {
      titleId: 'high_inquisitor',
      priority: 40,
      npcRecommendation: { templateId: 'investigator', level: 9 },
    },
    {
      titleId: 'inquisitor',
      priority: 30,
      npcRecommendation: { templateId: 'investigator', level: 6 },
    },
    {
      titleId: 'examiner',
      priority: 30,
      npcRecommendation: { templateId: 'investigator', level: 4 },
    },
    {
      titleId: 'investigator',
      priority: 20,
      npcRecommendation: { templateId: 'investigator', level: 4 },
    },
    {
      titleId: 'interrogator',
      priority: 20,
      npcRecommendation: { templateId: 'investigator', level: 4 },
    },
    {
      titleId: 'agent',
      priority: 10,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
  ],
  intelligence_bureau: [
    {
      titleId: 'director',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 10 },
    },
    {
      titleId: 'deputy_director',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 8 },
    },
    {
      titleId: 'spymaster',
      priority: 40,
      npcRecommendation: { templateId: 'covert_operator', level: 9 },
    },
    {
      titleId: 'handler',
      priority: 30,
      npcRecommendation: { templateId: 'covert_operator', level: 6 },
    },
    { titleId: 'analyst', priority: 30, npcRecommendation: { templateId: 'scholar', level: 3 } },
    {
      titleId: 'agent',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    {
      titleId: 'operative',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    { titleId: 'informant', priority: 10, npcRecommendation: { templateId: 'civilian', level: 0 } },
  ],
  labor_union: [
    {
      titleId: 'president',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    { titleId: 'chair', priority: 40, npcRecommendation: { templateId: 'civic_leader', level: 0 } },
    {
      titleId: 'secretary',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'treasurer',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'organizer',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'shop_steward',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 2 },
    },
    {
      titleId: 'delegate',
      priority: 20,
      npcRecommendation: { templateId: 'administrator', level: 1 },
    },
    { titleId: 'member', priority: 10, npcRecommendation: { templateId: 'civilian', level: 0 } },
  ],
  logging_company: [
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'foreman',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'timber_master',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 4 },
    },
    {
      titleId: 'surveyor',
      priority: 30,
      npcRecommendation: { templateId: 'technical_specialist', level: 3 },
    },
    {
      titleId: 'logger',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 1 },
    },
    { titleId: 'sawyer', priority: 20, npcRecommendation: { templateId: 'artisan', level: 1 } },
    {
      titleId: 'teamster',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 1 },
    },
    {
      titleId: 'laborer',
      priority: 10,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
  ],
  mage_college: [
    {
      titleId: 'archmage',
      priority: 50,
      npcRecommendation: { templateId: 'arcane_practitioner', level: 14 },
    },
    {
      titleId: 'rector',
      priority: 50,
      npcRecommendation: { templateId: 'arcane_practitioner', level: 10 },
    },
    {
      titleId: 'master',
      priority: 40,
      npcRecommendation: { templateId: 'arcane_practitioner', level: 9 },
    },
    {
      titleId: 'professor',
      priority: 30,
      npcRecommendation: { templateId: 'arcane_practitioner', level: 6 },
    },
    {
      titleId: 'mage',
      priority: 30,
      npcRecommendation: { templateId: 'arcane_practitioner', level: 4 },
    },
    { titleId: 'researcher', priority: 20, npcRecommendation: { templateId: 'scholar', level: 3 } },
    {
      titleId: 'adept',
      priority: 20,
      npcRecommendation: { templateId: 'arcane_practitioner', level: 2 },
    },
    {
      titleId: 'apprentice',
      priority: 10,
      npcRecommendation: { templateId: 'arcane_practitioner', level: 1 },
    },
  ],
  merchant_house: [
    {
      titleId: 'patriarch',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'matriarch',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    { titleId: 'factor', priority: 40, npcRecommendation: { templateId: 'merchant', level: 3 } },
    { titleId: 'merchant', priority: 30, npcRecommendation: { templateId: 'merchant', level: 0 } },
    { titleId: 'agent', priority: 20, npcRecommendation: { templateId: 'merchant', level: 2 } },
    {
      titleId: 'clerk',
      priority: 10,
      npcRecommendation: { templateId: 'administrator', level: 0 },
    },
  ],
  militia: [
    {
      titleId: 'commander',
      priority: 50,
      npcRecommendation: { templateId: 'martial_commander', level: 7 },
    },
    {
      titleId: 'captain',
      priority: 40,
      npcRecommendation: { templateId: 'martial_officer', level: 5 },
    },
    {
      titleId: 'lieutenant',
      priority: 30,
      npcRecommendation: { templateId: 'martial_officer', level: 4 },
    },
    {
      titleId: 'sergeant',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 3 },
    },
    { titleId: 'militiaman', priority: 10, npcRecommendation: { templateId: 'guard', level: 2 } },
    { titleId: 'scout', priority: 10, npcRecommendation: { templateId: 'scout', level: 2 } },
    { titleId: 'recruit', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  mining_company: [
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'mine_captain',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 5 },
    },
    {
      titleId: 'foreman',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    {
      titleId: 'engineer',
      priority: 30,
      npcRecommendation: { templateId: 'technical_specialist', level: 4 },
    },
    {
      titleId: 'surveyor',
      priority: 30,
      npcRecommendation: { templateId: 'technical_specialist', level: 3 },
    },
    {
      titleId: 'miner',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 1 },
    },
    {
      titleId: 'prospector',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 2 },
    },
    {
      titleId: 'laborer',
      priority: 10,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
  ],
  missionary_society: [
    {
      titleId: 'president',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'mission_director',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    {
      titleId: 'minister',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 6 },
    },
    {
      titleId: 'missionary',
      priority: 20,
      npcRecommendation: { templateId: 'divine_practitioner', level: 2 },
    },
    {
      titleId: 'preacher',
      priority: 20,
      npcRecommendation: { templateId: 'divine_practitioner', level: 2 },
    },
    { titleId: 'translator', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    {
      titleId: 'lay_worker',
      priority: 10,
      npcRecommendation: { templateId: 'civilian', level: 0 },
    },
    { titleId: 'volunteer', priority: 10, npcRecommendation: { templateId: 'civilian', level: 0 } },
  ],
  navy: [
    {
      titleId: 'admiral',
      priority: 50,
      npcRecommendation: { templateId: 'martial_commander', level: 14 },
    },
    {
      titleId: 'commodore',
      priority: 40,
      npcRecommendation: { templateId: 'martial_commander', level: 11 },
    },
    {
      titleId: 'captain',
      priority: 40,
      npcRecommendation: { templateId: 'maritime_officer', level: 7 },
    },
    {
      titleId: 'lieutenant',
      priority: 30,
      npcRecommendation: { templateId: 'maritime_officer', level: 5 },
    },
    {
      titleId: 'sailing_master',
      priority: 30,
      npcRecommendation: { templateId: 'technical_specialist', level: 5 },
    },
    {
      titleId: 'boatswain',
      priority: 20,
      npcRecommendation: { templateId: 'maritime_crew', level: 3 },
    },
    {
      titleId: 'sailor',
      priority: 10,
      npcRecommendation: { templateId: 'maritime_crew', level: 2 },
    },
    { titleId: 'marine', priority: 10, npcRecommendation: { templateId: 'guard', level: 3 } },
  ],
  pirate_crew: [
    {
      titleId: 'captain',
      priority: 50,
      npcRecommendation: { templateId: 'maritime_officer', level: 7 },
    },
    {
      titleId: 'quartermaster',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 4 },
    },
    {
      titleId: 'sailing_master',
      priority: 30,
      npcRecommendation: { templateId: 'technical_specialist', level: 5 },
    },
    {
      titleId: 'boatswain',
      priority: 30,
      npcRecommendation: { templateId: 'maritime_crew', level: 3 },
    },
    {
      titleId: 'gunner',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 4 },
    },
    {
      titleId: 'pirate',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 3 },
    },
    {
      titleId: 'sailor',
      priority: 10,
      npcRecommendation: { templateId: 'maritime_crew', level: 2 },
    },
    {
      titleId: 'cabin_hand',
      priority: 10,
      npcRecommendation: { templateId: 'maritime_crew', level: 1 },
    },
  ],
  private_security_company: [
    {
      titleId: 'director',
      priority: 50,
      npcRecommendation: { templateId: 'administrator', level: 8 },
    },
    {
      titleId: 'security_chief',
      priority: 40,
      npcRecommendation: { templateId: 'martial_commander', level: 8 },
    },
    {
      titleId: 'captain',
      priority: 40,
      npcRecommendation: { templateId: 'martial_officer', level: 6 },
    },
    {
      titleId: 'supervisor',
      priority: 30,
      npcRecommendation: { templateId: 'martial_officer', level: 4 },
    },
    {
      titleId: 'bodyguard',
      priority: 20,
      npcRecommendation: { templateId: 'martial_specialist', level: 5 },
    },
    { titleId: 'guard', priority: 20, npcRecommendation: { templateId: 'guard', level: 3 } },
    {
      titleId: 'investigator',
      priority: 20,
      npcRecommendation: { templateId: 'investigator', level: 4 },
    },
    { titleId: 'recruit', priority: 10, npcRecommendation: { templateId: 'guard', level: 1 } },
  ],
  protection_racket: [
    {
      titleId: 'boss',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 8 },
    },
    {
      titleId: 'lieutenant',
      priority: 40,
      npcRecommendation: { templateId: 'covert_operator', level: 6 },
    },
    {
      titleId: 'collector',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 3 },
    },
    {
      titleId: 'enforcer',
      priority: 30,
      npcRecommendation: { templateId: 'martial_specialist', level: 5 },
    },
    {
      titleId: 'fixer',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    {
      titleId: 'runner',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    { titleId: 'lookout', priority: 10, npcRecommendation: { templateId: 'scout', level: 2 } },
  ],
  shipyard: [
    {
      titleId: 'proprietor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'shipwright_master',
      priority: 40,
      npcRecommendation: { templateId: 'artisan', level: 6 },
    },
    {
      titleId: 'yardmaster',
      priority: 40,
      npcRecommendation: { templateId: 'administrator', level: 4 },
    },
    {
      titleId: 'foreman',
      priority: 30,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    { titleId: 'shipwright', priority: 20, npcRecommendation: { templateId: 'artisan', level: 3 } },
    { titleId: 'carpenter', priority: 20, npcRecommendation: { templateId: 'artisan', level: 1 } },
    {
      titleId: 'rigger',
      priority: 20,
      npcRecommendation: { templateId: 'manual_worker', level: 1 },
    },
    {
      titleId: 'laborer',
      priority: 10,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
  ],
  spy_ring: [
    {
      titleId: 'spymaster',
      priority: 50,
      npcRecommendation: { templateId: 'covert_operator', level: 10 },
    },
    {
      titleId: 'handler',
      priority: 40,
      npcRecommendation: { templateId: 'covert_operator', level: 6 },
    },
    {
      titleId: 'case_officer',
      priority: 30,
      npcRecommendation: { templateId: 'covert_operator', level: 5 },
    },
    {
      titleId: 'agent',
      priority: 30,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    {
      titleId: 'operative',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 4 },
    },
    {
      titleId: 'courier',
      priority: 20,
      npcRecommendation: { templateId: 'covert_operator', level: 2 },
    },
    { titleId: 'informant', priority: 10, npcRecommendation: { templateId: 'civilian', level: 0 } },
  ],
  theater_troupe: [
    {
      titleId: 'company_manager',
      priority: 50,
      npcRecommendation: { templateId: 'administrator', level: 3 },
    },
    { titleId: 'director', priority: 40, npcRecommendation: { templateId: 'performer', level: 5 } },
    {
      titleId: 'playwright',
      priority: 30,
      npcRecommendation: { templateId: 'performer', level: 3 },
    },
    {
      titleId: 'lead_actor',
      priority: 30,
      npcRecommendation: { templateId: 'performer', level: 4 },
    },
    { titleId: 'actor', priority: 20, npcRecommendation: { templateId: 'performer', level: 2 } },
    { titleId: 'musician', priority: 20, npcRecommendation: { templateId: 'performer', level: 2 } },
    {
      titleId: 'stagehand',
      priority: 10,
      npcRecommendation: { templateId: 'manual_worker', level: 0 },
    },
    { titleId: 'apprentice', priority: 10, npcRecommendation: { templateId: 'artisan', level: 1 } },
  ],
  university: [
    {
      titleId: 'chancellor',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    {
      titleId: 'rector',
      priority: 50,
      npcRecommendation: { templateId: 'civic_leader', level: 0 },
    },
    { titleId: 'dean', priority: 40, npcRecommendation: { templateId: 'administrator', level: 4 } },
    { titleId: 'professor', priority: 30, npcRecommendation: { templateId: 'scholar', level: 4 } },
    { titleId: 'lecturer', priority: 30, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'researcher', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'scholar', priority: 20, npcRecommendation: { templateId: 'scholar', level: 2 } },
    { titleId: 'student', priority: 10, npcRecommendation: { templateId: 'scholar', level: 0 } },
  ],
} as const
