/**
 * @deprecated Import from `campaign-character-assignment-errors` instead.
 * Temporary aliases for invite-scoped callers during the neutral rename cutover.
 */
export {
  LEGACY_CAMPAIGN_INVITE_COMPLETION_ERROR_CODE as CAMPAIGN_INVITE_COMPLETION_ERROR_CODE,
  campaignCharacterAssignmentBuildInvalidDetailsSchema as campaignInviteCompletionBuildInvalidDetailsSchema,
  campaignCharacterAssignmentCampaignIneligibleDetailsSchema as campaignInviteCompletionCampaignIneligibleDetailsSchema,
  campaignCharacterAssignmentErrorDetailsSchema as campaignInviteCompletionErrorDetailsSchema,
  campaignCharacterAssignmentInviteUnavailableDetailsSchema as campaignInviteCompletionInviteUnavailableDetailsSchema,
  type CampaignCharacterAssignmentErrorDetails as CampaignInviteCompletionErrorDetails,
  type ResolvedCampaignCharacterAssignmentError as ResolvedCampaignInviteCompletionError,
  isCampaignCharacterAssignmentErrorCode as isCampaignInviteCompletionErrorCode,
  parseCampaignCharacterAssignmentErrorDetails as parseCampaignInviteCompletionErrorDetails,
  resolveCampaignCharacterAssignmentError as resolveCampaignInviteCompletionError,
} from './campaign-character-assignment-errors'
