import type { NamingCulture } from '@rpg/contracts/name-generator'

export const STANDALONE_NAMING_CULTURES = [
  {
    id: 'akan',
    label: 'Akan',
    origin: 'historical',
    regionIds: ['west-africa'],
    languageIds: ['common'],
    description: 'Precisely labeled Akan naming tradition.',
  },
  {
    id: 'anglo-saxon',
    label: 'Anglo-Saxon',
    origin: 'historical',
    regionIds: ['british-isles'],
    languageIds: ['common'],
    description: 'Dithematic Old English naming with settlement and landmark forms.',
  },
  {
    id: 'arabic',
    label: 'Arabic',
    origin: 'historical',
    regionIds: ['near-east'],
    languageIds: ['common'],
    description: 'Classical Arabic naming with ism, nasab, and nisba.',
  },
  {
    id: 'gaelic',
    label: 'Gaelic',
    origin: 'historical',
    regionIds: ['british-isles'],
    languageIds: ['common'],
    description: 'Gaelic naming with O/Mac versus Ni/Nic patronyms and prefix toponyms.',
  },
  {
    id: 'han-chinese',
    label: 'Han Chinese',
    origin: 'historical',
    regionIds: ['east-asia'],
    languageIds: ['common'],
    description: 'Family-first Han Chinese naming with two-morpheme given names.',
  },
  {
    id: 'japanese',
    label: 'Japanese',
    origin: 'historical',
    regionIds: ['east-asia'],
    languageIds: ['common'],
    description: 'Family-first Japanese naming with settlement and landmark forms.',
  },
  {
    id: 'norse',
    label: 'Norse',
    origin: 'historical',
    regionIds: ['scandinavia'],
    languageIds: ['common'],
    description: 'Old Norse personal naming with patronymics and bynames.',
  },
  {
    id: 'roman',
    label: 'Roman',
    origin: 'historical',
    regionIds: ['mediterranean'],
    languageIds: ['common'],
    description: 'Republican Roman tria nomina with praenomen, nomen, and cognomen.',
  },
  {
    id: 'slavic',
    label: 'Slavic',
    origin: 'historical',
    regionIds: ['eastern-europe'],
    languageIds: ['common'],
    description: 'East Slavic naming with gendered patronymics and family suffixes.',
  },
  {
    id: 'yoruba',
    label: 'Yoruba',
    origin: 'historical',
    regionIds: ['west-africa'],
    languageIds: ['common'],
    description: 'Yoruba naming with theophoric given names and prefix toponyms.',
  },
] as const satisfies readonly NamingCulture[]
