import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const angloSaxonPlaceSuffixPoolCollection = {
  id: 'anglo-saxon-place-suffix-pool',
  label: 'Anglo-Saxon settlement suffixes',
  description: 'Settlement suffixes -ton, -ham, -bury, -ford, and -wick.',
  subjectKinds: ['settlement'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placeSuffix',
        role: 'placeSuffix',
        values: ['bury', 'ford', 'ham', 'ton', 'wick'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Old English settlement suffixes: -ton, -ham, -bury, -ford, -wick.',
  },
  version: 1,
} as const satisfies NameCollection
