import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const angloSaxonBynamePoolCollection = {
  id: 'anglo-saxon-byname-pool',
  label: 'Anglo-Saxon bynames',
  description: 'Conventional Old English epithets used as personal bynames.',
  subjectKinds: ['person'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'epithet',
        role: 'epithet',
        genderStyle: 'shared',
        values: [
          'the Elder',
          'the Fair',
          'the Good',
          'the Great',
          'the Grim',
          'the Ready',
          'the Stout',
          'the Unready',
          'the Wise',
          'the Younger',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
