import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const angloSaxonLandmarkSuffixPoolCollection = {
  id: 'anglo-saxon-landmark-suffix-pool',
  label: 'Anglo-Saxon landmark suffixes',
  description: 'Landmark suffixes drawn from Old English topographic elements.',
  subjectKinds: ['landmark'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placeSuffix',
        role: 'placeSuffix',
        values: ['barrow', 'bury', 'ford', 'hurst', 'ley'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Old English landmark suffixes: -barrow, -bury, -ford, -hurst, -ley.',
  },
  version: 1,
} as const satisfies NameCollection
