import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const arabicLandmarkPrefixPoolCollection = {
  id: 'arabic-landmark-prefix-pool',
  label: 'Arabic landmark prefixes',
  description: 'Landmark prefixes drawn from Arabic topographic elements.',
  subjectKinds: ['landmark'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placePrefix',
        role: 'placePrefix',
        values: ['Ain al-', 'Birkat al-', 'Jabal al-', 'Qalat al-', 'Wadi al-'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes:
      'Attested Arabic landmark prefixes: Ain al-, Birkat al-, Jabal al-, Qalat al-, Wadi al-.',
  },
  version: 1,
} as const satisfies NameCollection
