import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const arabicNasabParticlePoolCollection = {
  id: 'arabic-nasab-particle-pool',
  label: 'Arabic nasab particles',
  description: 'Masculine ibn and feminine bint particles for Arabic nasab.',
  subjectKinds: ['person'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'patronym-masc',
        role: 'patronym',
        genderStyle: 'masculine',
        values: ['ibn'],
      },
      {
        id: 'patronym-fem',
        role: 'patronym',
        genderStyle: 'feminine',
        values: ['bint'],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
