import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const arabicPlacePrefixPoolCollection = {
  id: 'arabic-place-prefix-pool',
  label: 'Arabic settlement prefixes',
  description: 'Settlement prefixes Dar al-, Bab al-, Qasr al-, Ain al-, and Burj al-.',
  subjectKinds: ['settlement'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placePrefix',
        role: 'placePrefix',
        values: ['Ain al-', 'Bab al-', 'Burj al-', 'Dar al-', 'Qasr al-'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Arabic settlement prefixes: Ain al-, Bab al-, Burj al-, Dar al-, Qasr al-.',
  },
  version: 1,
} as const satisfies NameCollection
