import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const arabicNisbaPoolCollection = {
  id: 'arabic-nisba-pool',
  label: 'Arabic nisba epithets',
  description: 'Classical Arabic nisba adjectives used as family and personal epithets.',
  subjectKinds: ['person', 'family'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'epithet',
        role: 'epithet',
        genderStyle: 'shared',
        values: [
          'al-Andalusi',
          'al-Asqalani',
          'al-Baghdadi',
          'al-Basri',
          'al-Dimashqi',
          'al-Farsi',
          'al-Halabi',
          'al-Hijazi',
          'al-Iraqi',
          'al-Isfahani',
          'al-Iskandari',
          'al-Kufi',
          'al-Madani',
          'al-Maghribi',
          'al-Makki',
          'al-Mausili',
          'al-Misri',
          'al-Najdi',
          'al-Qahiri',
          'al-Qurashi',
          'al-Qurtubi',
          'al-Shami',
          'al-Tabari',
          'al-Yamani',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
