import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const draconicDragonbornOrgTypePoolCollection = {
  id: 'draconic-dragonborn-org-type-pool',
  label: 'Draconic dragonborn organization types',
  description: 'Flight- and clutch-flavored organization types for dragonborn factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Banner',
          'Brood',
          'Circle',
          'Clutch',
          'Cohort',
          'Compact',
          'Conclave',
          'Council',
          'Flight',
          'Flightwing',
          'Guild',
          'Host',
          'Kinband',
          'League',
          'Legion',
          'Lodge',
          'Order',
          'Regiment',
          'Scalehost',
          'Society',
          'Union',
          'Vanguard',
          'Wyrmhost',
          'Wyrmpack',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
