import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const dwarvenOrgTypePoolCollection = {
  id: 'dwarven-org-type-pool',
  label: 'Dwarven organization types',
  description: 'Guild- and hold-flavored organization types for dwarven factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Brotherhood',
          'Chapterhouse',
          'Clan',
          'Cohort',
          'Company',
          'Conclave',
          'Council',
          'Delve',
          'Forge',
          'Foundry',
          'Guild',
          'Hall',
          'Hammerhost',
          'Hold',
          'Host',
          'League',
          'Legion',
          'Lodge',
          'Muster',
          'Order',
          'Regiment',
          'Shieldwall',
          'Stonehall',
          'Union',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
