import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const elvishOrgTypePoolCollection = {
  id: 'elvish-org-type-pool',
  label: 'Elvish organization types',
  description: 'Circle- and court-flavored organization types for elven factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Accord',
          'Arbor',
          'Choir',
          'Circle',
          'Conclave',
          'Consort',
          'Coterie',
          'Council',
          'Court',
          'Covenant',
          'Grove',
          'Harmony',
          'Highcourt',
          'Kinband',
          'Litany',
          'Lyceum',
          'Moot',
          'Order',
          'Reverie',
          'Sanctum',
          'Sodality',
          'Song',
          'Starcourt',
          'Vigil',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
