import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const gaelicLandmarkPrefixPoolCollection = {
  id: 'gaelic-landmark-prefix-pool',
  label: 'Gaelic landmark prefixes',
  description: 'Landmark prefixes drawn from Gaelic topographic elements.',
  subjectKinds: ['landmark'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placePrefix',
        role: 'placePrefix',
        values: ['Ben', 'Glen', 'Knock', 'Loch', 'Slieve'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Gaelic landmark prefixes: Ben, Glen, Knock, Loch, Slieve.',
  },
  version: 1,
} as const satisfies NameCollection
