import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const gaelicPlacePrefixPoolCollection = {
  id: 'gaelic-place-prefix-pool',
  label: 'Gaelic settlement prefixes',
  description: 'Settlement prefixes Bally-, Carrick-, Dun-, Inish-, and Kil-.',
  subjectKinds: ['settlement'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placePrefix',
        role: 'placePrefix',
        values: ['Bally', 'Carrick', 'Dun', 'Inish', 'Kil'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Gaelic settlement prefixes: Bally, Carrick, Dun, Inish, Kil.',
  },
  version: 1,
} as const satisfies NameCollection
