import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const gaelicPatronymParticlePoolCollection = {
  id: 'gaelic-patronym-particle-pool',
  label: 'Gaelic patronymic particles',
  description: 'Masculine O/Mac and feminine Ni/Nic particles for Gaelic patronyms.',
  subjectKinds: ['person'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'patronym-masc',
        role: 'patronym',
        genderStyle: 'masculine',
        values: ['Mac', 'O'],
      },
      {
        id: 'patronym-fem',
        role: 'patronym',
        genderStyle: 'feminine',
        values: ['Ni', 'Nic'],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
