import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const gnomishOrgTypePoolCollection = {
  id: 'gnomish-org-type-pool',
  label: 'Gnomish organization types',
  description: 'Workshop- and invention-flavored organization types for gnomish factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Bureau',
          'Circle',
          'Clockwork',
          'Coghall',
          'Compact',
          'Conclave',
          'Contraption',
          'Enclave',
          'Fellowship',
          'Foundry',
          'Gearhall',
          'Guild',
          'Institute',
          'Invention',
          'League',
          'Lodge',
          'Lyceum',
          'Mechanism',
          'Order',
          'Society',
          'Symposium',
          'Tinkerhall',
          'Union',
          'Workshop',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
