import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const goliathOrgTypePoolCollection = {
  id: 'goliath-org-type-pool',
  label: 'Goliath organization types',
  description: 'Peak- and holdfast-flavored organization types for goliath factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Brotherhood',
          'Circle',
          'Clan',
          'Cohort',
          'Compact',
          'Conclave',
          'Council',
          'Crag',
          'Fellowship',
          'Guild',
          'Holdfast',
          'Host',
          'Kinband',
          'League',
          'Lodge',
          'Muster',
          'Order',
          'Peak',
          'Society',
          'Stonehost',
          'Summit',
          'Throng',
          'Union',
          'Watch',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
