import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const halflingOrgTypePoolCollection = {
  id: 'halfling-org-type-pool',
  label: 'Halfling organization types',
  description: 'Hearth- and harvest-flavored organization types for halfling factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Burrow',
          'Circle',
          'Compact',
          'Company',
          'Conclave',
          'Fellowship',
          'Gathering',
          'Guild',
          'Harvest',
          'Hearth',
          'Homestead',
          'Kinband',
          'League',
          'Lodge',
          'Moot',
          'Order',
          'Pantry',
          'Parish',
          'Society',
          'Supper',
          'Table',
          'Troop',
          'Union',
          'Watch',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
