import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const hanChinesePlaceSuffixPoolCollection = {
  id: 'han-chinese-place-suffix-pool',
  label: 'Han Chinese settlement suffixes',
  description: 'Settlement suffixes -cheng, -jing, and -zhou.',
  subjectKinds: ['settlement'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placeSuffix',
        role: 'placeSuffix',
        values: ['cheng', 'jing', 'zhou'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Chinese settlement suffixes: -cheng, -jing, -zhou.',
  },
  version: 1,
} as const satisfies NameCollection
