import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const hanChineseLandmarkSuffixPoolCollection = {
  id: 'han-chinese-landmark-suffix-pool',
  label: 'Han Chinese landmark suffixes',
  description: 'Landmark suffixes drawn from Chinese topographic elements.',
  subjectKinds: ['landmark'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placeSuffix',
        role: 'placeSuffix',
        values: ['he', 'ling', 'shan'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Chinese landmark suffixes: -he, -ling, -shan.',
  },
  version: 1,
} as const satisfies NameCollection
