import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const humanOrgTypePoolCollection = {
  id: 'human-org-type-pool',
  label: 'Human organization types',
  description: 'Civic- and company-flavored organization types for human factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Assembly',
          'Brotherhood',
          'Bureau',
          'Compact',
          'Company',
          'Conclave',
          'Council',
          'Court',
          'Directorate',
          'Fellowship',
          'Guild',
          'House',
          'Institute',
          'League',
          'Lodge',
          'Order',
          'Regiment',
          'Senate',
          'Society',
          'Syndicate',
          'Union',
          'Vanguard',
          'Ward',
          'Watch',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
