import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const infernalTieflingOrgTypePoolCollection = {
  id: 'infernal-tiefling-org-type-pool',
  label: 'Infernal tiefling organization types',
  description: 'Cabal- and pact-flavored organization types for tiefling factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Accord',
          'Cabal',
          'Circle',
          'Compact',
          'Conclave',
          'Coven',
          'Covenant',
          'Cult',
          'Enclave',
          'Fellowship',
          'Host',
          'League',
          'Lodge',
          'Order',
          'Pact',
          'Ring',
          'Sect',
          'Society',
          'Syndicate',
          'Synod',
          'Tribunal',
          'Veil',
          'Vigil',
          'Wing',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
