import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const japanesePlaceSuffixPoolCollection = {
  id: 'japanese-place-suffix-pool',
  label: 'Japanese settlement suffixes',
  description: 'Settlement suffixes -mura, -machi, -gawa, -yama, and -jo.',
  subjectKinds: ['settlement'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placeSuffix',
        role: 'placeSuffix',
        values: ['gawa', 'jo', 'machi', 'mura', 'yama'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Japanese settlement suffixes: -mura, -machi, -gawa, -yama, -jo.',
  },
  version: 1,
} as const satisfies NameCollection
