import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const japaneseLandmarkSuffixPoolCollection = {
  id: 'japanese-landmark-suffix-pool',
  label: 'Japanese landmark suffixes',
  description: 'Landmark suffixes drawn from Japanese topographic elements.',
  subjectKinds: ['landmark'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placeSuffix',
        role: 'placeSuffix',
        values: ['gawa', 'ji', 'jo', 'toge', 'yama'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Japanese landmark suffixes: -gawa, -ji, -jo, -toge, -yama.',
  },
  version: 1,
} as const satisfies NameCollection
