import type { NameCollectionManifestEntry } from '@rpg/contracts/name-generator'

export const COLLECTION_MANIFEST_ENTRIES = [
  {
    id: 'elvish-given-pool',
    label: 'Elvish given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'elvish-family-pool',
    label: 'Elvish family names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-family-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'elvish-place-root-pool',
    label: 'Elvish settlement roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-place-root-pool.ts',
    approximateResultCount: 7,
  },
  {
    id: 'elvish-place-suffix-pool',
    label: 'Elvish settlement suffixes',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-place-suffix-pool.ts',
    approximateResultCount: 7,
  },
  {
    id: 'draconic-dragon-given-pool',
    label: 'True dragon given names',
    subjectKinds: ['person', 'creature'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragon-given-pool.ts',
    approximateResultCount: 10,
  },
  {
    id: 'draconic-dragonborn-given-pool',
    label: 'Dragonborn given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragonborn-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'draconic-dragonborn-clan-pool',
    label: 'Dragonborn clan names',
    subjectKinds: ['person', 'clan', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragonborn-clan-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'dwarven-given-pool',
    label: 'Dwarven given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/dwarven-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'dwarven-clan-pool',
    label: 'Dwarven clan names',
    subjectKinds: ['person', 'clan', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/dwarven-clan-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'dwarven-settlement-pool',
    label: 'Dwarven settlement compounds',
    subjectKinds: ['settlement'],
    generatorKinds: ['compound'],
    assetPath: 'collections/dwarven-settlement-pool.ts',
    approximateResultCount: 36,
  },
  {
    id: 'halfling-given-pool',
    label: 'Halfling given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'halfling-family-pool',
    label: 'Halfling family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-family-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'halfling-place-root-pool',
    label: 'Halfling settlement roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-place-root-pool.ts',
    approximateResultCount: 7,
  },
  {
    id: 'halfling-place-suffix-pool',
    label: 'Halfling settlement suffixes',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-place-suffix-pool.ts',
    approximateResultCount: 7,
  },
  {
    id: 'infernal-tiefling-given-pool',
    label: 'Infernal tiefling given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/infernal-tiefling-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'infernal-tiefling-virtue-pool',
    label: 'Infernal tiefling virtue names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/infernal-tiefling-virtue-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'gnomish-given-pool',
    label: 'Gnomish given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'gnomish-family-pool',
    label: 'Gnomish family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-family-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'gnomish-place-root-pool',
    label: 'Gnomish settlement roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-place-root-pool.ts',
    approximateResultCount: 7,
  },
  {
    id: 'gnomish-place-suffix-pool',
    label: 'Gnomish settlement suffixes',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-place-suffix-pool.ts',
    approximateResultCount: 7,
  },
  {
    id: 'goliath-given-pool',
    label: 'Goliath given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'goliath-epithet-pool',
    label: 'Goliath epithets',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-epithet-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'goliath-clan-pool',
    label: 'Goliath clan names',
    subjectKinds: ['person', 'clan', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-clan-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'human-given-pool',
    label: 'Human given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/human-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'human-family-pool',
    label: 'Human family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/human-family-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'orc-given-pool',
    label: 'Orc given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/orc-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'faction-descriptor-pool',
    label: 'Faction descriptors',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/faction-descriptor-pool.ts',
    approximateResultCount: 7,
  },
  {
    id: 'faction-org-type-pool',
    label: 'Organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/faction-org-type-pool.ts',
    approximateResultCount: 6,
  },
  {
    id: 'akan-given-pool',
    label: 'Akan given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/akan-given-pool.ts',
    approximateResultCount: 12,
  },
  {
    id: 'akan-family-pool',
    label: 'Akan family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/akan-family-pool.ts',
    approximateResultCount: 6,
  },
] as const satisfies readonly NameCollectionManifestEntry[]

export const COLLECTION_MANIFEST_IDS = new Set<string>(
  COLLECTION_MANIFEST_ENTRIES.map((entry) => entry.id),
)
