import type { NameCollectionManifestEntry } from '@rpg/contracts/name-generator'

export const COLLECTION_MANIFEST_ENTRIES = [
  {
    id: 'elvish-given-pool',
    label: 'Elvish given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'elvish-family-pool',
    label: 'Elvish family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-family-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'elvish-place-root-pool',
    label: 'Elvish place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'elvish-place-suffix-pool',
    label: 'Elvish settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'elvish-landmark-suffix-pool',
    label: 'Elvish landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'elvish-org-type-pool',
    label: 'Elvish organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'elvish-high-given-pool',
    label: 'High elvish given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-high-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'elvish-wood-given-pool',
    label: 'Wood elvish given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-wood-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'elvish-drow-given-pool',
    label: 'Drow given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/elvish-drow-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'dwarven-given-pool',
    label: 'Dwarven given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/dwarven-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'dwarven-clan-pool',
    label: 'Dwarven clan names',
    subjectKinds: ['person', 'clan', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/dwarven-clan-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'dwarven-place-root-pool',
    label: 'Dwarven place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/dwarven-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'dwarven-place-suffix-pool',
    label: 'Dwarven settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/dwarven-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'dwarven-landmark-suffix-pool',
    label: 'Dwarven landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/dwarven-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'dwarven-org-type-pool',
    label: 'Dwarven organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/dwarven-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'halfling-given-pool',
    label: 'Halfling given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'halfling-family-pool',
    label: 'Halfling family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-family-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'halfling-place-root-pool',
    label: 'Halfling place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'halfling-place-suffix-pool',
    label: 'Halfling settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'halfling-landmark-suffix-pool',
    label: 'Halfling landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'halfling-org-type-pool',
    label: 'Halfling organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/halfling-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'gnomish-given-pool',
    label: 'Gnomish given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'gnomish-family-pool',
    label: 'Gnomish family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-family-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'gnomish-place-root-pool',
    label: 'Gnomish place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'gnomish-place-suffix-pool',
    label: 'Gnomish settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'gnomish-landmark-suffix-pool',
    label: 'Gnomish landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'gnomish-org-type-pool',
    label: 'Gnomish organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gnomish-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'human-given-pool',
    label: 'Human given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/human-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'human-family-pool',
    label: 'Human family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/human-family-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'human-place-root-pool',
    label: 'Human place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/human-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'human-place-suffix-pool',
    label: 'Human settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/human-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'human-landmark-suffix-pool',
    label: 'Human landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/human-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'human-org-type-pool',
    label: 'Human organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/human-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'orc-given-pool',
    label: 'Orc given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/orc-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'orc-clan-pool',
    label: 'Orc clan names',
    subjectKinds: ['person', 'clan', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/orc-clan-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'orc-place-root-pool',
    label: 'Orc place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/orc-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'orc-place-suffix-pool',
    label: 'Orc settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/orc-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'orc-landmark-suffix-pool',
    label: 'Orc landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/orc-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'orc-org-type-pool',
    label: 'Orc organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/orc-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'infernal-tiefling-given-pool',
    label: 'Infernal tiefling given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/infernal-tiefling-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'infernal-tiefling-virtue-pool',
    label: 'Infernal tiefling virtue names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/infernal-tiefling-virtue-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'infernal-tiefling-place-root-pool',
    label: 'Infernal tiefling place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/infernal-tiefling-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'infernal-tiefling-place-suffix-pool',
    label: 'Infernal tiefling settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/infernal-tiefling-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'infernal-tiefling-landmark-suffix-pool',
    label: 'Infernal tiefling landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/infernal-tiefling-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'infernal-tiefling-org-type-pool',
    label: 'Infernal tiefling organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/infernal-tiefling-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'abyssal-tiefling-given-pool',
    label: 'Abyssal tiefling given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/abyssal-tiefling-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'chthonic-tiefling-given-pool',
    label: 'Chthonic tiefling given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/chthonic-tiefling-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'draconic-dragon-given-pool',
    label: 'True dragon given names',
    subjectKinds: ['person', 'creature'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragon-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'draconic-dragonborn-given-pool',
    label: 'Dragonborn given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragonborn-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'draconic-dragonborn-clan-pool',
    label: 'Dragonborn clan names',
    subjectKinds: ['person', 'clan', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragonborn-clan-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'draconic-dragonborn-place-root-pool',
    label: 'Draconic dragonborn place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragonborn-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'draconic-dragonborn-place-suffix-pool',
    label: 'Draconic dragonborn settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragonborn-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'draconic-dragonborn-landmark-suffix-pool',
    label: 'Draconic dragonborn landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragonborn-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'draconic-dragonborn-org-type-pool',
    label: 'Draconic dragonborn organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-dragonborn-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'draconic-metallic-given-pool',
    label: 'Metallic draconic given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-metallic-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'draconic-chromatic-given-pool',
    label: 'Chromatic draconic given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/draconic-chromatic-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'goliath-given-pool',
    label: 'Goliath given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'goliath-epithet-pool',
    label: 'Goliath epithets',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-epithet-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'goliath-clan-pool',
    label: 'Goliath clan names',
    subjectKinds: ['person', 'clan', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-clan-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'goliath-place-root-pool',
    label: 'Goliath place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'goliath-place-suffix-pool',
    label: 'Goliath settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-place-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'goliath-landmark-suffix-pool',
    label: 'Goliath landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-landmark-suffix-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'goliath-org-type-pool',
    label: 'Goliath organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/goliath-org-type-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'akan-given-pool',
    label: 'Akan given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/akan-given-pool.ts',
    approximateResultCount: 48,
  },
  {
    id: 'akan-family-pool',
    label: 'Akan family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/akan-family-pool.ts',
    approximateResultCount: 60,
  },
  {
    id: 'norse-given-pool',
    label: 'Norse given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/norse-given-pool.ts',
    approximateResultCount: 44,
  },
  {
    id: 'norse-patronym-suffix-pool',
    label: 'Norse patronymic suffixes',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/norse-patronym-suffix-pool.ts',
    approximateResultCount: 2,
  },
  {
    id: 'norse-byname-pool',
    label: 'Norse bynames',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/norse-byname-pool.ts',
    approximateResultCount: 16,
  },
  {
    id: 'anglo-saxon-given-pool',
    label: 'Anglo-Saxon given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/anglo-saxon-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'anglo-saxon-byname-pool',
    label: 'Anglo-Saxon bynames',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/anglo-saxon-byname-pool.ts',
    approximateResultCount: 10,
  },
  {
    id: 'anglo-saxon-place-root-pool',
    label: 'Anglo-Saxon place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/anglo-saxon-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'anglo-saxon-place-suffix-pool',
    label: 'Anglo-Saxon settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/anglo-saxon-place-suffix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'anglo-saxon-landmark-suffix-pool',
    label: 'Anglo-Saxon landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/anglo-saxon-landmark-suffix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'japanese-family-pool',
    label: 'Japanese family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/japanese-family-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'japanese-given-pool',
    label: 'Japanese given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/japanese-given-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'japanese-place-root-pool',
    label: 'Japanese place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/japanese-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'japanese-place-suffix-pool',
    label: 'Japanese settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/japanese-place-suffix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'japanese-landmark-suffix-pool',
    label: 'Japanese landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/japanese-landmark-suffix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'gaelic-given-pool',
    label: 'Gaelic given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gaelic-given-pool.ts',
    approximateResultCount: 44,
  },
  {
    id: 'gaelic-patronym-particle-pool',
    label: 'Gaelic patronymic particles',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gaelic-patronym-particle-pool.ts',
    approximateResultCount: 4,
  },
  {
    id: 'gaelic-family-pool',
    label: 'Gaelic family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gaelic-family-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'gaelic-place-root-pool',
    label: 'Gaelic place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gaelic-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'gaelic-place-prefix-pool',
    label: 'Gaelic settlement prefixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gaelic-place-prefix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'gaelic-landmark-prefix-pool',
    label: 'Gaelic landmark prefixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/gaelic-landmark-prefix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'slavic-given-pool',
    label: 'Slavic given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/slavic-given-pool.ts',
    approximateResultCount: 44,
  },
  {
    id: 'slavic-patronym-suffix-pool',
    label: 'Slavic patronymic suffixes',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/slavic-patronym-suffix-pool.ts',
    approximateResultCount: 4,
  },
  {
    id: 'slavic-family-root-pool',
    label: 'Slavic family roots',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/slavic-family-root-pool.ts',
    approximateResultCount: 30,
  },
  {
    id: 'slavic-family-suffix-pool',
    label: 'Slavic family suffixes',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/slavic-family-suffix-pool.ts',
    approximateResultCount: 6,
  },
  {
    id: 'slavic-place-root-pool',
    label: 'Slavic place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/slavic-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'slavic-place-suffix-pool',
    label: 'Slavic settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/slavic-place-suffix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'slavic-landmark-suffix-pool',
    label: 'Slavic landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/slavic-landmark-suffix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'han-chinese-family-pool',
    label: 'Han Chinese family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/han-chinese-family-pool.ts',
    approximateResultCount: 100,
  },
  {
    id: 'han-chinese-given-pool',
    label: 'Han Chinese given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/han-chinese-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'han-chinese-place-root-pool',
    label: 'Han Chinese place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/han-chinese-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'han-chinese-place-suffix-pool',
    label: 'Han Chinese settlement suffixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/han-chinese-place-suffix-pool.ts',
    approximateResultCount: 3,
  },
  {
    id: 'han-chinese-landmark-suffix-pool',
    label: 'Han Chinese landmark suffixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/han-chinese-landmark-suffix-pool.ts',
    approximateResultCount: 3,
  },
  {
    id: 'yoruba-given-pool',
    label: 'Yoruba given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/yoruba-given-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'yoruba-family-pool',
    label: 'Yoruba family names',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/yoruba-family-pool.ts',
    approximateResultCount: 40,
  },
  {
    id: 'yoruba-place-root-pool',
    label: 'Yoruba place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/yoruba-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'yoruba-place-prefix-pool',
    label: 'Yoruba settlement prefixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/yoruba-place-prefix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'yoruba-landmark-prefix-pool',
    label: 'Yoruba landmark prefixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/yoruba-landmark-prefix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'roman-praenomen-pool',
    label: 'Roman praenomina',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/roman-praenomen-pool.ts',
    approximateResultCount: 26,
  },
  {
    id: 'roman-nomen-pool',
    label: 'Roman nomina',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/roman-nomen-pool.ts',
    approximateResultCount: 48,
  },
  {
    id: 'roman-cognomen-pool',
    label: 'Roman cognomina',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/roman-cognomen-pool.ts',
    approximateResultCount: 28,
  },
  {
    id: 'roman-place-root-pool',
    label: 'Roman place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/roman-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'roman-place-prefix-pool',
    label: 'Roman settlement prefixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/roman-place-prefix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'roman-landmark-prefix-pool',
    label: 'Roman landmark prefixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/roman-landmark-prefix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'arabic-given-pool',
    label: 'Arabic given names',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/arabic-given-pool.ts',
    approximateResultCount: 44,
  },
  {
    id: 'arabic-nasab-particle-pool',
    label: 'Arabic nasab particles',
    subjectKinds: ['person'],
    generatorKinds: ['sample'],
    assetPath: 'collections/arabic-nasab-particle-pool.ts',
    approximateResultCount: 2,
  },
  {
    id: 'arabic-nisba-pool',
    label: 'Arabic nisba epithets',
    subjectKinds: ['person', 'family'],
    generatorKinds: ['sample'],
    assetPath: 'collections/arabic-nisba-pool.ts',
    approximateResultCount: 24,
  },
  {
    id: 'arabic-place-root-pool',
    label: 'Arabic place roots',
    subjectKinds: ['settlement', 'landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/arabic-place-root-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'arabic-place-prefix-pool',
    label: 'Arabic settlement prefixes',
    subjectKinds: ['settlement'],
    generatorKinds: ['sample'],
    assetPath: 'collections/arabic-place-prefix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'arabic-landmark-prefix-pool',
    label: 'Arabic landmark prefixes',
    subjectKinds: ['landmark'],
    generatorKinds: ['sample'],
    assetPath: 'collections/arabic-landmark-prefix-pool.ts',
    approximateResultCount: 5,
  },
  {
    id: 'faction-descriptor-pool',
    label: 'Faction descriptors',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/faction-descriptor-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'faction-emblem-pool',
    label: 'Faction emblems',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/faction-emblem-pool.ts',
    approximateResultCount: 300,
  },
  {
    id: 'faction-org-type-pool',
    label: 'Organization types',
    subjectKinds: ['faction', 'organization'],
    generatorKinds: ['sample'],
    assetPath: 'collections/faction-org-type-pool.ts',
    approximateResultCount: 60,
  },
] as const satisfies readonly NameCollectionManifestEntry[]

export const COLLECTION_MANIFEST_IDS = new Set<string>(
  COLLECTION_MANIFEST_ENTRIES.map((entry) => entry.id),
)
