import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const norsePatronymSuffixPoolCollection = {
  id: 'norse-patronym-suffix-pool',
  label: 'Norse patronymic suffixes',
  description: 'Masculine -sson and feminine -sdottir suffixes for Norse patronyms.',
  subjectKinds: ['person'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'patronym-masc',
        role: 'patronym',
        genderStyle: 'masculine',
        values: ['sson'],
      },
      {
        id: 'patronym-fem',
        role: 'patronym',
        genderStyle: 'feminine',
        values: ['sdottir'],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
