import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const norseBynamePoolCollection = {
  id: 'norse-byname-pool',
  label: 'Norse bynames',
  description: 'Attested and conventional Old Norse epithets and bynames.',
  subjectKinds: ['person'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'epithet',
        role: 'epithet',
        genderStyle: 'shared',
        values: [
          'Bloodaxe',
          'Fairhair',
          'Forkbeard',
          'Ironside',
          'Longsword',
          'Skullsplitter',
          'the Bold',
          'the Deep-minded',
          'the Fair',
          'the Keen',
          'the Red',
          'the Silent',
          'the Stout',
          'the Unready',
          'the Wanderer',
          'the Wise',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
