import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const orcOrgTypePoolCollection = {
  id: 'orc-org-type-pool',
  label: 'Orc organization types',
  description: 'Warband- and horde-flavored organization types for orc factions.',
  subjectKinds: ['faction', 'organization'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'organizationType',
        role: 'organizationType',
        values: [
          'Banner',
          'Bloodpack',
          'Brotherhood',
          'Circle',
          'Clan',
          'Cohort',
          'Compact',
          'Conclave',
          'Fist',
          'Horde',
          'Hordeband',
          'Host',
          'Legion',
          'Muster',
          'Order',
          'Pack',
          'Raid',
          'Spearhost',
          'Throng',
          'Tusks',
          'Union',
          'Warband',
          'Warhost',
          'Warpack',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.fictionalOriginal,
  version: 1,
} as const satisfies NameCollection
