import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const romanPraenomenPoolCollection = {
  id: 'roman-praenomen-pool',
  label: 'Roman praenomina',
  description: 'Attested Republican Roman praenomina. The small count is historically accurate.',
  subjectKinds: ['person'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'given-masc',
        role: 'given',
        genderStyle: 'masculine',
        values: [
          'Appius',
          'Aulus',
          'Caeso',
          'Decimus',
          'Gaius',
          'Gnaeus',
          'Lucius',
          'Manius',
          'Marcus',
          'Numerius',
          'Publius',
          'Quintus',
          'Servius',
          'Sextus',
          'Spurius',
          'Tiberius',
          'Titus',
          'Vibius',
        ],
      },
      {
        id: 'given-fem',
        role: 'given',
        genderStyle: 'feminine',
        values: ['Octavia', 'Prima', 'Quarta', 'Quinta', 'Secunda', 'Septima', 'Sexta', 'Tertia'],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
