import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const romanLandmarkPrefixPoolCollection = {
  id: 'roman-landmark-prefix-pool',
  label: 'Roman landmark prefixes',
  description: 'Landmark prefixes drawn from Latin topographic elements.',
  subjectKinds: ['landmark'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placePrefix',
        role: 'placePrefix',
        values: ['Mons', 'Pons', 'Porta', 'Templum', 'Via'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Roman landmark prefixes: Mons, Pons, Porta, Templum, Via.',
  },
  version: 1,
} as const satisfies NameCollection
