import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const romanCognomenPoolCollection = {
  id: 'roman-cognomen-pool',
  label: 'Roman cognomina',
  description: 'Attested Republican Roman cognomina used as personal epithets.',
  subjectKinds: ['person'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'epithet',
        role: 'epithet',
        genderStyle: 'shared',
        values: [
          'Africanus',
          'Agricola',
          'Albinus',
          'Balbus',
          'Brutus',
          'Caesar',
          'Calvus',
          'Cicero',
          'Cincinnatus',
          'Corvus',
          'Crassus',
          'Dentatus',
          'Felix',
          'Flaccus',
          'Gallus',
          'Germanicus',
          'Longus',
          'Magnus',
          'Maximus',
          'Naso',
          'Niger',
          'Pius',
          'Rufus',
          'Scaevola',
          'Severus',
          'Strabo',
          'Varro',
          'Verrucosus',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
