import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const romanPlacePrefixPoolCollection = {
  id: 'roman-place-prefix-pool',
  label: 'Roman settlement prefixes',
  description: 'Settlement prefixes Castra, Colonia, Forum, Portus, and Villa.',
  subjectKinds: ['settlement'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placePrefix',
        role: 'placePrefix',
        values: ['Castra', 'Colonia', 'Forum', 'Portus', 'Villa'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Roman settlement prefixes: Castra, Colonia, Forum, Portus, Villa.',
  },
  version: 1,
} as const satisfies NameCollection
