import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const slavicFamilyRootPoolCollection = {
  id: 'slavic-family-root-pool',
  label: 'Slavic family roots',
  description: 'Family-name stems combined with gendered -ov/-sky suffixes.',
  subjectKinds: ['person', 'family'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'familyRoot',
        role: 'family',
        genderStyle: 'shared',
        values: [
          'Bel',
          'Berez',
          'Bogdan',
          'Chern',
          'Dobro',
          'Dub',
          'Grom',
          'Ivan',
          'Kuznet',
          'Lebed',
          'Medved',
          'Mir',
          'Moroz',
          'Moskov',
          'Novgorod',
          'Orl',
          'Petr',
          'Rad',
          'Roman',
          'Serebr',
          'Smolensk',
          'Sneg',
          'Sokol',
          'Stan',
          'Svet',
          'Vlad',
          'Volk',
          'Voron',
          'Yar',
          'Zolot',
        ],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
