import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const slavicLandmarkSuffixPoolCollection = {
  id: 'slavic-landmark-suffix-pool',
  label: 'Slavic landmark suffixes',
  description: 'Landmark suffixes drawn from Slavic topographic elements.',
  subjectKinds: ['landmark'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placeSuffix',
        role: 'placeSuffix',
        values: ['gora', 'les', 'pole', 'reka', 'yar'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Slavic landmark suffixes: -gora, -les, -pole, -reka, -yar.',
  },
  version: 1,
} as const satisfies NameCollection
