import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const slavicPlaceSuffixPoolCollection = {
  id: 'slavic-place-suffix-pool',
  label: 'Slavic settlement suffixes',
  description: 'Settlement suffixes -gorod, -grad, -ino, -ovo, and -sk.',
  subjectKinds: ['settlement'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placeSuffix',
        role: 'placeSuffix',
        values: ['gorod', 'grad', 'ino', 'ovo', 'sk'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Slavic settlement suffixes: -gorod, -grad, -ino, -ovo, -sk.',
  },
  version: 1,
} as const satisfies NameCollection
