import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const slavicPatronymSuffixPoolCollection = {
  id: 'slavic-patronym-suffix-pool',
  label: 'Slavic patronymic suffixes',
  description: 'Masculine -ovich/-evich and feminine -ovna/-evna suffixes for Slavic patronyms.',
  subjectKinds: ['person'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'patronym-masc',
        role: 'patronym',
        genderStyle: 'masculine',
        values: ['evich', 'ovich'],
      },
      {
        id: 'patronym-fem',
        role: 'patronym',
        genderStyle: 'feminine',
        values: ['evna', 'ovna'],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
