import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const slavicFamilySuffixPoolCollection = {
  id: 'slavic-family-suffix-pool',
  label: 'Slavic family suffixes',
  description: 'Gender-inflected family suffixes -ov/-sky versus -ova/-skaya.',
  subjectKinds: ['person', 'family'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'family-suffix-masc',
        role: 'family',
        genderStyle: 'masculine',
        values: ['ev', 'ov', 'sky'],
      },
      {
        id: 'family-suffix-fem',
        role: 'family',
        genderStyle: 'feminine',
        values: ['eva', 'ova', 'skaya'],
      },
    ],
  },
  provenance: FIXTURE_COLLECTION_PROVENANCE.historicalCurated,
  version: 1,
} as const satisfies NameCollection
