import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const yorubaLandmarkPrefixPoolCollection = {
  id: 'yoruba-landmark-prefix-pool',
  label: 'Yoruba landmark prefixes',
  description: 'Landmark prefixes drawn from Yoruba topographic elements.',
  subjectKinds: ['landmark'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placePrefix',
        role: 'placePrefix',
        values: ['Igbo-', 'Odo-', 'Oke-', 'Ori-', 'Osun-'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Yoruba landmark prefixes: Igbo-, Odo-, Oke-, Ori-, Osun-.',
  },
  version: 1,
} as const satisfies NameCollection
