import type { NameCollection } from '@rpg/contracts/name-generator'

import { FIXTURE_COLLECTION_PROVENANCE } from '../lib/provenance'

// Generated by tools/scripts/generate-name-pools.mjs — edit the morpheme tables there.
export const yorubaPlacePrefixPoolCollection = {
  id: 'yoruba-place-prefix-pool',
  label: 'Yoruba settlement prefixes',
  description: 'Settlement prefixes Ile-, Ita-, Ago-, Oke-, and Odo-.',
  subjectKinds: ['settlement'],
  generator: {
    type: 'sample',
    pools: [
      {
        id: 'placePrefix',
        role: 'placePrefix',
        values: ['Ago-', 'Ile-', 'Ita-', 'Odo-', 'Oke-'],
      },
    ],
  },
  provenance: {
    ...FIXTURE_COLLECTION_PROVENANCE.patternDerived,
    notes: 'Attested Yoruba settlement prefixes: Ago-, Ile-, Ita-, Odo-, Oke-.',
  },
  version: 1,
} as const satisfies NameCollection
