import type { BuildingArchetypeShardEntry } from './types'

export const BUILDING_ARCHETYPE_ENTRIES_A_C = {
  academy: {
    label: 'Academy',
    description: 'A building primarily serving education (advanced).',
    functions: ['knowledge'],
    searchTerms: ['education', 'school', 'learning'],
    specializationTerms: ['bardic college'],
  },
  adventurers_guild: {
    label: 'Adventurers Guild',
    description: 'A building primarily serving quest brokerage.',
    functions: ['assembly', 'governance'],
    searchTerms: ['quest', 'guild', 'party'],
    specializationTerms: ['bounty office'],
  },
  almshouse: {
    label: 'Almshouse',
    description: 'A building primarily serving endowed poor housing.',
    functions: ['care'],
    searchTerms: ['charity', 'poor', 'housing'],
  },
  apartment_building: {
    label: 'Apartment Building',
    description: 'A building primarily serving dwelling (multi-household).',
    functions: ['dwelling'],
    aliases: ['flats'],
    searchTerms: ['dwelling', 'residential', 'multi-family'],
  },
  apothecary: {
    label: 'Apothecary',
    description: 'A building primarily serving retail (remedies).',
    functions: ['retail', 'care'],
    aliases: ['pharmacy'],
    searchTerms: ['remedies', 'potions', 'medicine'],
    specializationTerms: ['potion shop'],
  },
  archive: {
    label: 'Archive',
    description: 'A building primarily serving document custody (restricted).',
    functions: ['knowledge'],
    searchTerms: ['documents', 'records', 'custody'],
  },
  arena: {
    label: 'Arena',
    description: 'A building primarily serving spectacle games.',
    functions: ['spectacle'],
    searchTerms: ['combat', 'games', 'spectacle'],
    specializationTerms: ['amphitheater', 'fighting pit'],
  },
  armory: {
    label: 'Armory',
    description: 'A building primarily serving arms storage/maintenance.',
    functions: ['storage', 'defense_watch'],
    searchTerms: ['weapons', 'arms', 'armor'],
    specializationTerms: ['powder magazine'],
  },
  arsenal: {
    label: 'Arsenal',
    description: 'A building primarily serving arms manufacture.',
    functions: ['storage', 'defense_watch'],
    searchTerms: ['weapons', 'arms', 'munitions'],
  },
  asylum: {
    label: 'Asylum',
    description: 'A building primarily serving custodial mental care.',
    functions: ['care'],
    searchTerms: ['mental', 'custodial', 'care'],
  },
  auction_house: {
    label: 'Auction House',
    description: 'A building primarily serving sale-event venue.',
    functions: ['retail', 'assembly'],
    searchTerms: ['auction', 'bidding', 'sale'],
  },
  audience_hall: {
    label: 'Audience Hall',
    description: 'A building primarily serving assembly.',
    functions: ['assembly', 'governance'],
    searchTerms: ['assembly', 'audience', 'court'],
  },
  bank: {
    label: 'Bank',
    description: 'A building primarily serving finance (deposit/lend).',
    functions: ['finance'],
    searchTerms: ['finance', 'money', 'deposit'],
    specializationTerms: ['counting house', 'moneylender'],
  },
  barn: {
    label: 'Barn',
    description: 'A building primarily serving farm storage and outbuildings.',
    functions: ['service', 'storage'],
    searchTerms: ['farm', 'livestock', 'storage'],
    specializationTerms: ['byre', 'dovecote', 'shearing shed', 'threshing barn', 'tithe barn'],
  },
  barracks: {
    label: 'Barracks',
    description: 'A building primarily serving garrison housing.',
    functions: ['defense_watch', 'dwelling'],
    searchTerms: ['garrison', 'soldiers', 'military'],
  },
  barber_surgeon: {
    label: 'Barber Surgeon',
    description: 'A building primarily serving surgical and bloodletting care.',
    functions: ['care', 'service'],
    searchTerms: ['surgery', 'bloodletting', 'medicine'],
  },
  basilica: {
    label: 'Basilica',
    description: 'A building primarily serving assembly hall → church.',
    functions: ['worship', 'assembly'],
    manifestationOf: 'temple',
    searchTerms: ['church', 'christian', 'basilica'],
  },
  bathhouse: {
    label: 'Bathhouse',
    description: 'A building primarily serving bathing service.',
    functions: ['care'],
    searchTerms: ['bathing', 'baths', 'hygiene'],
  },
  beacon_tower: {
    label: 'Beacon Tower',
    description: 'A building primarily serving fire signaling.',
    functions: ['defense_watch'],
    searchTerms: ['signal', 'fire', 'warning'],
  },
  bell_tower: {
    label: 'Bell Tower',
    description: 'A building primarily serving bell housing/signal.',
    functions: ['defense_watch'],
    searchTerms: ['bells', 'signal', 'campanile'],
  },
  blacksmith: {
    label: 'Blacksmith',
    description: 'A smithy or metalworking shop.',
    functions: ['service'],
    aliases: ['smithy', 'forge'],
    searchTerms: ['metal', 'ironwork', 'smithing'],
  },
  blockhouse: {
    label: 'Blockhouse',
    description: 'A building primarily serving standalone strongpoint.',
    functions: ['service'],
    searchTerms: ['fortification', 'strongpoint', 'defense'],
  },
  boathouse: {
    label: 'Boathouse',
    description: 'A building primarily serving small-craft shelter.',
    functions: ['storage'],
    searchTerms: ['boats', 'craft', 'waterfront'],
  },
  boarding_house: {
    label: 'Boarding House',
    description: 'A building primarily serving lodging (residential-term).',
    functions: ['lodging'],
    searchTerms: ['lodging', 'roomers', 'residential'],
    specializationTerms: ['flophouse'],
  },
  brewery: {
    label: 'Brewery',
    description: 'A building primarily serving beverage production.',
    functions: ['production'],
    searchTerms: ['beer', 'ale', 'brewing'],
  },
  brickworks: {
    label: 'Brickworks',
    description: 'A building primarily serving brick production.',
    functions: ['production'],
    searchTerms: ['bricks', 'kiln', 'construction'],
  },
  broch: {
    label: 'Broch',
    description: 'A building primarily serving dwelling.',
    functions: ['dwelling', 'defense_watch'],
    manifestationOf: 'house',
    searchTerms: ['celtic', 'tower', 'fortified'],
  },
  brothel: {
    label: 'Brothel',
    description: 'A building primarily serving commercial sex.',
    functions: ['service'],
    searchTerms: ['pleasure', 'courtesan', 'entertainment'],
  },
  caravanserai: {
    label: 'Caravanserai',
    description: 'A roadside inn for merchants and caravan travelers.',
    functions: ['lodging', 'retail'],
    manifestationOf: 'inn',
    searchTerms: ['caravan', 'merchant', 'roadside'],
  },
  charnel_house: {
    label: 'Charnel House',
    description: 'A building primarily serving bone/corpse holding.',
    functions: ['funerary'],
    searchTerms: ['bones', 'corpses', 'dead'],
  },
  checkpoint: {
    label: 'Checkpoint',
    description: 'A building primarily serving movement control.',
    functions: ['service'],
    searchTerms: ['border', 'control', 'inspection'],
    specializationTerms: ['tollhouse'],
  },
  clock_tower: {
    label: 'Clock Tower',
    description: 'A building primarily serving timekeeping and civic signal.',
    functions: ['defense_watch'],
    searchTerms: ['clock', 'timekeeping', 'bell'],
  },
  coaching_inn: {
    label: 'Coaching Inn',
    description: 'A building primarily serving relay lodging.',
    functions: ['lodging', 'transport_support'],
    searchTerms: ['relay', 'stagecoach', 'travel'],
  },
  coffeehouse: {
    label: 'Coffeehouse',
    description: 'A building primarily serving coffee.',
    functions: ['service'],
    searchTerms: ['coffee', 'social', 'gathering'],
  },
  command_post: {
    label: 'Command Post',
    description: 'A building primarily serving command/control.',
    functions: ['service'],
    searchTerms: ['military', 'command', 'headquarters'],
  },
  cooperage: {
    label: 'Cooperage',
    description: 'A building primarily serving barrel making.',
    functions: ['production'],
    searchTerms: ['barrels', 'cooper', 'casks'],
  },
  courthouse: {
    label: 'Courthouse',
    description: 'A building primarily serving adjudication.',
    functions: ['governance'],
    searchTerms: ['law', 'trial', 'justice'],
  },
  crannog: {
    label: 'Crannog',
    description: 'A building primarily serving dwelling.',
    functions: ['defense_watch', 'dwelling'],
    manifestationOf: 'house',
    searchTerms: ['lake', 'island', 'celtic'],
  },
  crematorium: {
    label: 'Crematorium',
    description: 'A building primarily serving cremation.',
    functions: ['service'],
    searchTerms: ['cremation', 'funeral', 'ashes'],
  },
  customs_house: {
    label: 'Customs House',
    description: 'A building primarily serving trade inspection.',
    functions: ['governance', 'retail'],
    searchTerms: ['trade', 'tariff', 'inspection'],
  },
} as const satisfies Record<string, BuildingArchetypeShardEntry>
