import type { BuildingArchetypeShardEntry } from './types'

export const BUILDING_ARCHETYPE_ENTRIES_D_G = {
  domus: {
    label: 'Domus',
    description: 'A building primarily serving dwelling.',
    functions: ['dwelling'],
    manifestationOf: 'house',
    searchTerms: ['roman', 'villa', 'domus'],
  },
  drum_tower: {
    label: 'Drum Tower',
    description: 'A building primarily serving timekeeping/signal.',
    functions: ['defense_watch'],
    manifestationOf: 'watchtower',
    searchTerms: ['timekeeping', 'clock', 'signal'],
  },
  embassy: {
    label: 'Embassy',
    description: 'A building primarily serving diplomatic mission.',
    functions: ['service'],
    searchTerms: ['diplomatic', 'ambassador', 'mission'],
  },
  exchange: {
    label: 'Exchange',
    description: 'A building primarily serving brokered trading.',
    functions: ['finance', 'assembly'],
    searchTerms: ['trading', 'brokerage', 'finance'],
  },
  factory: {
    label: 'Factory',
    description: 'A building primarily serving mass manufacturing.',
    functions: ['production'],
    searchTerms: ['manufacturing', 'industry', 'production'],
  },
  festhall: {
    label: 'Festhall',
    description: 'A building primarily serving public feasting/revelry venue.',
    functions: ['food_drink_social'],
    aliases: ['feast hall'],
    searchTerms: ['feasting', 'revelry', 'banquet'],
  },
  folly: {
    label: 'Folly',
    description: 'A building primarily serving ornament/status display only.',
    functions: ['spectacle'],
    searchTerms: ['ornament', 'decorative', 'garden'],
  },
  gambling_hall: {
    label: 'Gambling Hall',
    description: 'A building primarily serving gaming venue.',
    functions: ['service'],
    searchTerms: ['gaming', 'cards', 'dice'],
  },
  gatehouse: {
    label: 'Gatehouse',
    description: 'A building primarily serving entry control.',
    functions: ['defense_watch'],
    searchTerms: ['gate', 'entry', 'fortification'],
  },
  gladiator_school: {
    label: 'Gladiator School',
    description: 'A building primarily serving spectacle-combat training.',
    functions: ['spectacle', 'lodging'],
    searchTerms: ['gladiator', 'combat', 'training'],
  },
  glassworks: {
    label: 'Glassworks',
    description: 'A building primarily serving glass production.',
    functions: ['production'],
    searchTerms: ['glass', 'blowing', 'craft'],
  },
  godown: {
    label: 'Godown',
    description: 'A building primarily serving trade warehouse.',
    functions: ['storage'],
    manifestationOf: 'warehouse',
    searchTerms: ['trade', 'port', 'godown'],
  },
  granary: {
    label: 'Granary',
    description: 'A building primarily serving grain storage.',
    functions: ['storage'],
    searchTerms: ['grain', 'food', 'storage'],
  },
  granary_on_stilts: {
    label: 'Granary On Stilts',
    description: 'A building primarily serving raised grain store.',
    functions: ['storage'],
    manifestationOf: 'warehouse',
    searchTerms: ['raised', 'grain', 'stilts'],
  },
  greenhouse: {
    label: 'Greenhouse',
    description: 'A building primarily serving protected cultivation.',
    functions: ['service'],
    searchTerms: ['plants', 'cultivation', 'garden'],
  },
  guard_post: {
    label: 'Guard Post',
    description: 'A building primarily serving watch/public order.',
    functions: ['defense_watch'],
    searchTerms: ['guard', 'watch', 'patrol'],
  },
  guildhall: {
    label: 'Guildhall',
    description: 'The headquarters of a craft or trade guild.',
    functions: ['assembly', 'governance'],
    searchTerms: ['guild', 'craft', 'trade'],
  },
} as const satisfies Record<string, BuildingArchetypeShardEntry>
