import type { BuildingArchetypeShardEntry } from './types'

export const BUILDING_ARCHETYPE_ENTRIES_M_P = {
  machiya: {
    label: 'Machiya',
    description: 'A building primarily serving dwelling.',
    functions: ['dwelling', 'retail'],
    manifestationOf: 'house',
    searchTerms: ['japanese', 'townhouse', 'merchant'],
  },
  madrasa: {
    label: 'Madrasa',
    description: 'A building primarily serving religious education.',
    functions: ['knowledge', 'worship'],
    manifestationOf: 'academy',
    searchTerms: ['islamic', 'quran', 'religious'],
  },
  manor: {
    label: 'Manor',
    description: 'A building primarily serving dwelling.',
    functions: ['dwelling', 'governance'],
    searchTerms: ['estate', 'landowner', 'gentry'],
  },
  market: {
    label: 'Market',
    description: 'A building primarily serving retail (many sellers).',
    functions: ['retail'],
    searchTerms: ['merchant', 'vendors', 'bazaar'],
  },
  martello_tower: {
    label: 'Martello Tower',
    description: 'A building primarily serving coastal gun platform.',
    functions: ['service'],
    searchTerms: ['coastal', 'cannon', 'coast'],
  },
  mastaba: {
    label: 'Mastaba',
    description: 'A building primarily serving tomb superstructure.',
    functions: ['funerary'],
    manifestationOf: 'mausoleum',
    searchTerms: ['egyptian', 'mastaba', 'superstructure'],
  },
  mausoleum: {
    label: 'Mausoleum',
    description: 'A building primarily serving monumental interment.',
    functions: ['funerary'],
    searchTerms: ['tomb', 'burial', 'monument'],
  },
  meeting_hall: {
    label: 'Meeting Hall',
    description: 'A building primarily serving assembly (secular).',
    functions: ['assembly'],
    searchTerms: ['assembly', 'gathering', 'civic'],
  },
  memorial_hall: {
    label: 'Memorial Hall',
    description: 'A building primarily serving commemoration.',
    functions: ['funerary', 'assembly'],
    searchTerms: ['memorial', 'commemoration', 'honor'],
  },
  menagerie: {
    label: 'Menagerie',
    description: 'A building primarily serving living collection display.',
    functions: ['spectacle', 'service'],
    searchTerms: ['animals', 'exotic', 'collection'],
  },
  mill: {
    label: 'Mill',
    description: 'A building primarily serving mechanical processing.',
    functions: ['production'],
    searchTerms: ['grinding', 'flour', 'waterwheel'],
  },
  mint: {
    label: 'Mint',
    description: 'A building primarily serving coin production (state).',
    functions: ['finance', 'production'],
    searchTerms: ['coins', 'currency', 'money'],
  },
  monastery: {
    label: 'Monastery',
    description: 'A building primarily serving religious community (worship.',
    functions: ['cloistered_community'],
    searchTerms: ['monks', 'cloister', 'religious'],
  },
  moot_hall: {
    label: 'Moot Hall',
    description: 'A building primarily serving deliberative assembly.',
    functions: ['assembly', 'governance'],
    manifestationOf: 'town_hall',
    searchTerms: ['deliberation', 'council', 'moot'],
  },
  mortuary: {
    label: 'Mortuary',
    description: 'A building primarily serving body preparation.',
    functions: ['service'],
    searchTerms: ['embalming', 'funeral', 'body'],
  },
  mosque: {
    label: 'Mosque',
    description: 'A building primarily serving congregational worship.',
    functions: ['worship', 'assembly'],
    manifestationOf: 'temple',
    searchTerms: ['islamic', 'congregation', 'minaret'],
  },
  museum: {
    label: 'Museum',
    description: 'A building primarily serving collection display.',
    functions: ['spectacle'],
    searchTerms: ['collection', 'artifacts', 'exhibits'],
  },
  nuraghe: {
    label: 'Nuraghe',
    description: 'A building primarily serving contested (dwelling? fort? rite?).',
    functions: ['defense_watch', 'dwelling'],
    searchTerms: ['sardinian', 'tower', 'prehistoric'],
  },
  observatory: {
    label: 'Observatory',
    description: 'A building primarily serving sky observation.',
    functions: ['service'],
    searchTerms: ['astronomy', 'stars', 'sky'],
  },
  orphanage: {
    label: 'Orphanage',
    description: 'A building primarily serving child custodial care.',
    functions: ['care'],
    searchTerms: ['children', 'orphans', 'custodial'],
  },
  pagoda: {
    label: 'Pagoda',
    description: 'A building primarily serving relic/veneration tower.',
    functions: ['worship'],
    manifestationOf: 'temple',
    searchTerms: ['buddhist', 'tiered', 'relic'],
  },
  palace: {
    label: 'Palace',
    description: 'A grand residence of a ruler or noble house.',
    functions: ['dwelling', 'governance'],
    searchTerms: ['royal', 'ruler', 'noble'],
  },
  paladin_chapterhouse: {
    label: 'Paladin Chapterhouse',
    description: 'A building primarily serving order housing.',
    functions: ['defense_watch', 'worship'],
    searchTerms: ['paladin', 'order', 'knights'],
  },
  poorhouse: {
    label: 'Poorhouse',
    description: 'A building primarily serving pauper relief housing.',
    functions: ['service'],
    searchTerms: ['pauper', 'relief', 'workhouse'],
  },
  post_house: {
    label: 'Post House',
    description: 'A building primarily serving courier relay (horses.',
    functions: ['transport_support'],
    searchTerms: ['courier', 'relay', 'mail'],
  },
  printing_press: {
    label: 'Printing Press',
    description: 'A building primarily serving print production.',
    functions: ['production'],
    searchTerms: ['printing', 'books', 'press'],
  },
  prison: {
    label: 'Prison',
    description: 'A building primarily serving detention.',
    functions: ['governance'],
    aliases: ['jail', 'gaol'],
    searchTerms: ['detention', 'incarceration', 'cells'],
  },
} as const satisfies Record<string, BuildingArchetypeShardEntry>
