import type { BuildingArchetypeShardEntry } from './types'

export const BUILDING_ARCHETYPE_ENTRIES_Q_T = {
  records_hall: {
    label: 'Records Hall',
    description: 'A building primarily serving records custody (state).',
    functions: ['governance', 'knowledge'],
    searchTerms: ['records', 'archives', 'state'],
  },
  ribat: {
    label: 'Ribat',
    description: 'A building primarily serving frontier defense.',
    functions: ['defense_watch', 'worship'],
    manifestationOf: 'monastery',
    searchTerms: ['frontier', 'fortified', 'islamic'],
  },
  roundhouse: {
    label: 'Roundhouse',
    description: 'A building primarily serving dwelling.',
    functions: ['dwelling'],
    manifestationOf: 'house',
    searchTerms: ['celtic', 'circular', 'iron age'],
  },
  ryokan: {
    label: 'Ryokan',
    description: 'A building primarily serving traveler inn (ritualized).',
    functions: ['lodging', 'care'],
    manifestationOf: 'inn',
    searchTerms: ['japanese', 'onsen', 'ritual'],
  },
  salt_works: {
    label: 'Salt Works',
    description: 'A building primarily serving salt extraction/evaporation.',
    functions: ['production'],
    searchTerms: ['salt', 'evaporation', 'extraction'],
  },
  shipyard: {
    label: 'Shipyard',
    description: 'A building primarily serving ship construction.',
    functions: ['production', 'transport_support'],
    searchTerms: ['ships', 'boatbuilding', 'harbor'],
  },
  shop: {
    label: 'Shop',
    description: 'A building primarily serving retail (general).',
    functions: ['retail'],
    searchTerms: ['merchant', 'retail', 'store'],
    specializationTerms: [
      'bakery',
      'butcher',
      'chandler',
      'cobbler',
      'general store',
      'jeweler',
      'magic shop',
      'pawnshop',
      'tailor',
    ],
  },
  siheyuan: {
    label: 'Siheyuan',
    description: 'A building primarily serving dwelling (multi-generation).',
    functions: ['dwelling'],
    manifestationOf: 'house',
    searchTerms: ['courtyard', 'chinese', 'compound'],
  },
  slaughterhouse: {
    label: 'Slaughterhouse',
    description: 'A building primarily serving animal processing.',
    functions: ['production'],
    searchTerms: ['butchery', 'meat', 'processing'],
    specializationTerms: ['smokehouse'],
  },
  stable: {
    label: 'Stable',
    description: 'A building for housing and caring for mounts.',
    functions: ['service'],
    searchTerms: ['horses', 'mounts', 'livery'],
    specializationTerms: ['beast stable', 'coach house', 'griffon aerie', 'kennel'],
  },
  stave_church: {
    label: 'Stave Church',
    description: 'A building primarily serving worship.',
    functions: ['worship'],
    manifestationOf: 'temple',
    searchTerms: ['norse', 'wooden', 'christian'],
  },
  sweat_lodge: {
    label: 'Sweat Lodge',
    description: 'A building primarily serving ceremonial heat rite.',
    functions: ['worship'],
    manifestationOf: 'bathhouse',
    searchTerms: ['ceremonial', 'indigenous', 'purification'],
  },
  synagogue: {
    label: 'Synagogue',
    description: 'A building primarily serving worship.',
    functions: ['worship', 'knowledge'],
    manifestationOf: 'temple',
    searchTerms: ['jewish', 'congregation', 'torah'],
  },
  tannery: {
    label: 'Tannery',
    description: 'A building primarily serving hide processing.',
    functions: ['production'],
    searchTerms: ['leather', 'hides', 'tanning'],
  },
  tavern: {
    label: 'Tavern',
    description: 'A venue for food, drink, and social gathering.',
    functions: ['food_drink_social'],
    aliases: ['pub', 'alehouse'],
    searchTerms: ['drink', 'ale', 'social'],
  },
  teahouse: {
    label: 'Teahouse',
    description: 'A building primarily serving tea service.',
    functions: ['food_drink_social'],
    manifestationOf: 'tavern',
    searchTerms: ['tea', 'japanese', 'ceremony'],
  },
  temple: {
    label: 'Temple',
    description: 'A religious or ceremonial structure.',
    functions: ['worship'],
    searchTerms: ['worship', 'prayer', 'sacred'],
    specializationTerms: [
      'baptistery',
      'cathedral',
      'oracle shrine',
      'temple infirmary',
      'sea temple',
      'funerary temple',
    ],
  },
  tenement: {
    label: 'Tenement',
    description: 'A building primarily serving dwelling (multi-household).',
    functions: ['dwelling'],
    searchTerms: ['crowded', 'urban', 'workers'],
  },
  theater: {
    label: 'Theater',
    description: 'A building primarily serving staged performance.',
    functions: ['spectacle'],
    searchTerms: ['performance', 'stage', 'drama'],
    specializationTerms: ['odeon'],
  },
  tholos: {
    label: 'Tholos',
    description: 'A building primarily serving vaulted tomb chamber.',
    functions: ['funerary'],
    manifestationOf: 'mausoleum',
    searchTerms: ['vaulted', 'greek', 'tholos'],
  },
  tolbooth: {
    label: 'Tolbooth',
    description: 'A building primarily serving administration.',
    functions: ['governance'],
    manifestationOf: 'courthouse',
    searchTerms: ['scottish', 'administration', 'tax'],
  },
  tower: {
    label: 'Tower',
    description: 'A building primarily serving (varies by occupant).',
    functions: ['service'],
    searchTerms: ['tall', 'fortified', 'observation'],
    specializationTerms: ['clock tower'],
  },
  town_hall: {
    label: 'Town Hall',
    description: 'A building primarily serving civic administration.',
    functions: ['governance', 'assembly'],
    searchTerms: ['civic', 'municipal', 'administration'],
  },
  trading_factory: {
    label: 'Trading Factory',
    description: 'A building primarily serving merchant station (office.',
    functions: ['retail', 'dwelling'],
    manifestationOf: 'warehouse',
    searchTerms: ['colonial', 'merchant', 'station'],
  },
  trading_post: {
    label: 'Trading Post',
    description: 'A building primarily serving exchange.',
    functions: ['retail', 'lodging'],
    searchTerms: ['frontier', 'exchange', 'fur'],
  },
  training_hall: {
    label: 'Training Hall',
    description: 'A building primarily serving martial drill.',
    functions: ['service'],
    searchTerms: ['martial', 'drill', 'combat'],
  },
  treasury: {
    label: 'Treasury',
    description: 'A building primarily serving wealth custody (state).',
    functions: ['governance'],
    searchTerms: ['wealth', 'gold', 'state'],
  },
} as const satisfies Record<string, BuildingArchetypeShardEntry>
