/**
 * Machine-checkable corpus disposition for Model E Phase 6 (2026-08-03).
 * Every BUILDING_CORPUS_IDS entry maps to exactly one disposition.
 */

export type BuildingCorpusDispositionKind =
  | 'archetype'
  | 'manifestation'
  | 'specialization'
  | 'form_only'
  | 'interior'
  | 'site'
  | 'composite'
  | 'overlay'
  | 'not_building'

export type BuildingCorpusDisposition =
  | { readonly kind: 'archetype' }
  | { readonly kind: 'manifestation'; readonly of: string }
  | { readonly kind: 'specialization'; readonly of: string }
  | { readonly kind: 'form_only'; readonly structureType?: string }
  | { readonly kind: 'interior' }
  | { readonly kind: 'site' }
  | { readonly kind: 'composite' }
  | { readonly kind: 'overlay' }
  | { readonly kind: 'not_building' }

export const BUILDING_CORPUS_IDS = [
  'abbey',
  'academy',
  'adventurers_guild',
  'airship',
  'airship_dock',
  'almshouse',
  'amphitheater',
  'anchorhold',
  'apartment_building',
  'apiary',
  'apothecary',
  'aqueduct',
  'archive',
  'arena',
  'armory',
  'arsenal',
  'artificer_atelier',
  'asylum',
  'auction_house',
  'audience_hall',
  'bakery',
  'bank',
  'banqueting_house',
  'baptistery',
  'barber_surgeon',
  'bardic_college',
  'barn',
  'barracks',
  'barrow',
  'basilica',
  'bathhouse',
  'beacon_tower',
  'beast_stable',
  'bell_tower',
  'blacksmith',
  'blockhouse',
  'boarding_house',
  'boathouse',
  'bounty_office',
  'brewery',
  'brickworks',
  'bridge',
  'bridge_house',
  'broch',
  'brothel',
  'butcher',
  'byre',
  'cairn',
  'camp',
  'caravanserai',
  'castle',
  'catacombs',
  'cathedral',
  'cave_dwelling',
  'chandler',
  'chantry',
  'chapel',
  'chapter_house',
  'charnel_house',
  'checkpoint',
  'citadel',
  'city_gate',
  'clinic',
  'clock_tower',
  'cloister',
  'coach_house',
  'coaching_inn',
  'cobbler',
  'coffeehouse',
  'command_post',
  'cooperage',
  'cottage',
  'counting_house',
  'courthouse',
  'covered_bridge',
  'crannog',
  'crematorium',
  'crypt',
  'customs_house',
  'distillery',
  'divination_parlor',
  'domus',
  'dormitory',
  'dovecote',
  'dower_house',
  'dragon_roost',
  'drum_tower',
  'drydock',
  'dwarven_forgehold',
  'dyeworks',
  'dzong',
  'elven_tree_dwelling',
  'embassy',
  'enchanting_hall',
  'exchange',
  'factory',
  'farmhouse',
  'farmstead',
  'feast_hall',
  'ferry_house',
  'festhall',
  'fighting_pit',
  'flophouse',
  'folly',
  'forge',
  'fortress',
  'foundry',
  'fountain',
  'fulling_mill',
  'gallows',
  'gambling_hall',
  'gamekeepers_cottage',
  'gatehouse',
  'general_store',
  'gladiator_school',
  'glassworks',
  'godown',
  'golem_workshop',
  'granary',
  'granary_on_stilts',
  'greenhouse',
  'griffon_aerie',
  'guard_post',
  'guildhall',
  'gymnasium',
  'hammam',
  'harbourmaster_office',
  'haunted_manor',
  'healers_house',
  'hermitage',
  'hippodrome',
  'hobbit_burrow',
  'hof',
  'hollowed_colossus',
  'hospice',
  'hospital',
  'house',
  'houseboat',
  'hovel',
  'hunting_lodge',
  'icehouse',
  'igloo',
  'inn',
  'insula',
  'jeweler',
  'kasbah',
  'keep',
  'kennel',
  'kiln',
  'kiva',
  'ksar',
  'laboratory',
  'lamasery',
  'lazaretto',
  'leprosarium',
  'library',
  'lighthouse',
  'livery',
  'longhouse',
  'machiya',
  'madrasa',
  'mage_college',
  'mage_prison',
  'magic_shop',
  'malt_house',
  'manor',
  'marae',
  'market',
  'market_stall',
  'martello_tower',
  'mastaba',
  'mausoleum',
  'meeting_hall',
  'memorial',
  'memorial_hall',
  'menagerie',
  'mill',
  'mimic_building',
  'mint',
  'mithraeum',
  'moai',
  'monastery',
  'moneylender',
  'moot_hall',
  'mortuary',
  'mosque',
  'museum',
  'nuraghe',
  'oast_house',
  'obelisk',
  'observatory',
  'odeon',
  'onsen',
  'open_air_shrine',
  'opium_den',
  'oracle_shrine',
  'orangery',
  'orphanage',
  'ossuary',
  'pa',
  'pagoda',
  'palace',
  'palace_complex',
  'paladin_chapterhouse',
  'palaestra',
  'pawnshop',
  'pigsty',
  'planar_embassy',
  'poorhouse',
  'portal_chamber',
  'post_house',
  'potion_shop',
  'powder_magazine',
  'printing_press',
  'prison',
  'pyramid',
  'ranger_station',
  'records_hall',
  'rectory',
  'ribat',
  'ritual_chamber',
  'root_cellar',
  'ropewalk',
  'roundhouse',
  'royal_mews',
  'ryokan',
  'safe_house',
  'sail_loft',
  'salt_works',
  'sanctum',
  'schoolhouse',
  'scriptorium',
  'shearing_shed',
  'sheepfold',
  'shinto_shrine',
  'ship',
  'shipwreck_dwelling',
  'shipyard',
  'shop',
  'shrine',
  'siege_tower',
  'siheyuan',
  'silo',
  'slaughterhouse',
  'smokehouse',
  'smugglers_den',
  'souk',
  'sphinx',
  'stable',
  'staithe',
  'statue',
  'stave_church',
  'stoa',
  'stupa',
  'summoning_hall',
  'sweat_lodge',
  'synagogue',
  'tailor',
  'tannery',
  'tavern',
  'teahouse',
  'temple',
  'temple_infirmary',
  'tenement',
  'tent_pavilion',
  'theater',
  'thermae',
  'thieves_den',
  'tholos',
  'threshing_barn',
  'throne_room',
  'tipi',
  'tithe_barn',
  'tolbooth',
  'tollhouse',
  'tomb',
  'tower',
  'town_hall',
  'townhouse',
  'trading_factory',
  'trading_post',
  'training_hall',
  'treasury',
  'triumphal_arch',
  'undercroft',
  'university_college',
  'vardo_wagon',
  'wall_segment',
  'walled_town',
  'war_camp',
  'warded_vault',
  'warehouse',
  'washhouse',
  'wat',
  'watchtower',
  'water_tower',
  'watermill',
  'waystation',
  'weigh_house',
  'well_house',
  'wheelwright',
  'windmill',
  'wizard_tower',
  'workhouse',
  'workshop',
  'yamen',
  'yurt',
  'ziggurat',
] as const

export type BuildingCorpusId = (typeof BUILDING_CORPUS_IDS)[number]

export const BUILDING_CORPUS_DISPOSITIONS = {
  abbey: { kind: 'composite' },
  academy: { kind: 'archetype' },
  adventurers_guild: { kind: 'archetype' },
  airship: { kind: 'form_only', structureType: 'vessel' },
  airship_dock: { kind: 'form_only', structureType: 'infrastructure' },
  almshouse: { kind: 'archetype' },
  amphitheater: { kind: 'specialization', of: 'n' },
  anchorhold: { kind: 'interior' },
  apartment_building: { kind: 'archetype' },
  apiary: { kind: 'not_building' },
  apothecary: { kind: 'archetype' },
  aqueduct: { kind: 'form_only', structureType: 'infrastructure' },
  archive: { kind: 'archetype' },
  arena: { kind: 'archetype' },
  armory: { kind: 'archetype' },
  arsenal: { kind: 'archetype' },
  artificer_atelier: { kind: 'specialization', of: 'n' },
  asylum: { kind: 'archetype' },
  auction_house: { kind: 'archetype' },
  audience_hall: { kind: 'archetype' },
  bakery: { kind: 'specialization', of: 'n' },
  bank: { kind: 'archetype' },
  banqueting_house: { kind: 'specialization', of: 'n' },
  baptistery: { kind: 'specialization', of: 'n' },
  barber_surgeon: { kind: 'specialization', of: 'n' },
  bardic_college: { kind: 'specialization', of: 'n' },
  barn: { kind: 'archetype' },
  barracks: { kind: 'archetype' },
  barrow: { kind: 'form_only', structureType: 'monument' },
  basilica: { kind: 'manifestation', of: 'temple' },
  bathhouse: { kind: 'archetype' },
  beacon_tower: { kind: 'archetype' },
  beast_stable: { kind: 'specialization', of: 'n' },
  bell_tower: { kind: 'archetype' },
  blacksmith: { kind: 'archetype' },
  blockhouse: { kind: 'archetype' },
  boarding_house: { kind: 'archetype' },
  boathouse: { kind: 'specialization', of: 'n' },
  bounty_office: { kind: 'specialization', of: 'n' },
  brewery: { kind: 'archetype' },
  brickworks: { kind: 'archetype' },
  bridge: { kind: 'form_only', structureType: 'infrastructure' },
  bridge_house: { kind: 'interior' },
  broch: { kind: 'manifestation', of: 'house' },
  brothel: { kind: 'archetype' },
  butcher: { kind: 'specialization', of: 'n' },
  byre: { kind: 'specialization', of: 'n' },
  cairn: { kind: 'form_only', structureType: 'monument' },
  camp: { kind: 'site' },
  caravanserai: { kind: 'manifestation', of: 'inn' },
  castle: { kind: 'composite' },
  catacombs: { kind: 'interior' },
  cathedral: { kind: 'specialization', of: 'temple' },
  cave_dwelling: { kind: 'specialization', of: 'house' },
  chandler: { kind: 'specialization', of: 'n' },
  chantry: { kind: 'interior' },
  chapel: { kind: 'interior' },
  chapter_house: { kind: 'interior' },
  charnel_house: { kind: 'archetype' },
  checkpoint: { kind: 'archetype' },
  citadel: { kind: 'composite' },
  city_gate: { kind: 'interior' },
  clinic: { kind: 'specialization', of: 'n' },
  clock_tower: { kind: 'specialization', of: 'n' },
  cloister: { kind: 'interior' },
  coach_house: { kind: 'specialization', of: 'n' },
  coaching_inn: { kind: 'archetype' },
  cobbler: { kind: 'specialization', of: 'n' },
  coffeehouse: { kind: 'archetype' },
  command_post: { kind: 'archetype' },
  cooperage: { kind: 'specialization', of: 'n' },
  cottage: { kind: 'specialization', of: 'n' },
  counting_house: { kind: 'specialization', of: 'bank' },
  courthouse: { kind: 'archetype' },
  covered_bridge: { kind: 'interior' },
  crannog: { kind: 'manifestation', of: 'house' },
  crematorium: { kind: 'archetype' },
  crypt: { kind: 'interior' },
  customs_house: { kind: 'archetype' },
  distillery: { kind: 'specialization', of: 'n' },
  divination_parlor: { kind: 'specialization', of: 'n' },
  domus: { kind: 'manifestation', of: 'house' },
  dormitory: { kind: 'interior' },
  dovecote: { kind: 'specialization', of: 'n' },
  dower_house: { kind: 'specialization', of: 'manor' },
  dragon_roost: { kind: 'overlay' },
  drum_tower: { kind: 'manifestation', of: 'watchtower' },
  drydock: { kind: 'form_only', structureType: 'infrastructure' },
  dwarven_forgehold: { kind: 'composite' },
  dyeworks: { kind: 'specialization', of: 'n' },
  dzong: { kind: 'composite' },
  elven_tree_dwelling: { kind: 'specialization', of: 'house' },
  embassy: { kind: 'archetype' },
  enchanting_hall: { kind: 'specialization', of: 'n' },
  exchange: { kind: 'archetype' },
  factory: { kind: 'archetype' },
  farmhouse: { kind: 'specialization', of: 'house' },
  farmstead: { kind: 'composite' },
  feast_hall: { kind: 'interior' },
  ferry_house: { kind: 'specialization', of: 'n' },
  festhall: { kind: 'archetype' },
  fighting_pit: { kind: 'specialization', of: 'n' },
  flophouse: { kind: 'specialization', of: 'n' },
  folly: { kind: 'archetype' },
  forge: { kind: 'interior' },
  fortress: { kind: 'composite' },
  foundry: { kind: 'specialization', of: 'n' },
  fountain: { kind: 'form_only', structureType: 'infrastructure' },
  fulling_mill: { kind: 'specialization', of: 'n' },
  gallows: { kind: 'not_building' },
  gambling_hall: { kind: 'archetype' },
  gamekeepers_cottage: { kind: 'specialization', of: 'cottage' },
  gatehouse: { kind: 'archetype' },
  general_store: { kind: 'specialization', of: 'n' },
  gladiator_school: { kind: 'archetype' },
  glassworks: { kind: 'archetype' },
  godown: { kind: 'manifestation', of: 'warehouse' },
  golem_workshop: { kind: 'specialization', of: 'n' },
  granary: { kind: 'archetype' },
  granary_on_stilts: { kind: 'manifestation', of: 'warehouse' },
  greenhouse: { kind: 'archetype' },
  griffon_aerie: { kind: 'specialization', of: 'n' },
  guard_post: { kind: 'archetype' },
  guildhall: { kind: 'archetype' },
  gymnasium: { kind: 'composite' },
  hammam: { kind: 'manifestation', of: 'bathhouse' },
  harbourmaster_office: { kind: 'specialization', of: 'n' },
  haunted_manor: { kind: 'overlay' },
  healers_house: { kind: 'archetype' },
  hermitage: { kind: 'archetype' },
  hippodrome: { kind: 'form_only', structureType: 'infrastructure' },
  hobbit_burrow: { kind: 'interior' },
  hof: { kind: 'manifestation', of: 'temple' },
  hollowed_colossus: { kind: 'overlay' },
  hospice: { kind: 'archetype' },
  hospital: { kind: 'archetype' },
  house: { kind: 'archetype' },
  houseboat: { kind: 'specialization', of: 'house' },
  hovel: { kind: 'specialization', of: 'n' },
  hunting_lodge: { kind: 'archetype' },
  icehouse: { kind: 'specialization', of: 'n' },
  igloo: { kind: 'specialization', of: 'house' },
  inn: { kind: 'archetype' },
  insula: { kind: 'manifestation', of: 'apartment_building' },
  jeweler: { kind: 'specialization', of: 'n' },
  kasbah: { kind: 'composite' },
  keep: { kind: 'archetype' },
  kennel: { kind: 'specialization', of: 'n' },
  kiln: { kind: 'interior' },
  kiva: { kind: 'archetype' },
  ksar: { kind: 'composite' },
  laboratory: { kind: 'interior' },
  lamasery: { kind: 'composite' },
  lazaretto: { kind: 'archetype' },
  leprosarium: { kind: 'composite' },
  library: { kind: 'archetype' },
  lighthouse: { kind: 'archetype' },
  livery: { kind: 'specialization', of: 'n' },
  longhouse: { kind: 'manifestation', of: 'house' },
  machiya: { kind: 'manifestation', of: 'house' },
  madrasa: { kind: 'manifestation', of: 'academy' },
  mage_college: { kind: 'composite' },
  mage_prison: { kind: 'specialization', of: 'n' },
  magic_shop: { kind: 'specialization', of: 'n' },
  malt_house: { kind: 'specialization', of: 'n' },
  manor: { kind: 'archetype' },
  marae: { kind: 'site' },
  market: { kind: 'archetype' },
  market_stall: { kind: 'not_building' },
  martello_tower: { kind: 'archetype' },
  mastaba: { kind: 'manifestation', of: 'mausoleum' },
  mausoleum: { kind: 'archetype' },
  meeting_hall: { kind: 'archetype' },
  memorial: { kind: 'form_only', structureType: 'monument' },
  memorial_hall: { kind: 'archetype' },
  menagerie: { kind: 'archetype' },
  mill: { kind: 'archetype' },
  mimic_building: { kind: 'not_building' },
  mint: { kind: 'archetype' },
  mithraeum: { kind: 'interior' },
  moai: { kind: 'form_only', structureType: 'monument' },
  monastery: { kind: 'composite' },
  moneylender: { kind: 'specialization', of: 'n' },
  moot_hall: { kind: 'manifestation', of: 'town_hall' },
  mortuary: { kind: 'archetype' },
  mosque: { kind: 'manifestation', of: 'temple' },
  museum: { kind: 'archetype' },
  nuraghe: { kind: 'archetype' },
  oast_house: { kind: 'specialization', of: 'n' },
  obelisk: { kind: 'form_only', structureType: 'monument' },
  observatory: { kind: 'archetype' },
  odeon: { kind: 'specialization', of: 'n' },
  onsen: { kind: 'interior' },
  open_air_shrine: { kind: 'site' },
  opium_den: { kind: 'specialization', of: 'n' },
  oracle_shrine: { kind: 'specialization', of: 'n' },
  orangery: { kind: 'specialization', of: 'n' },
  orphanage: { kind: 'archetype' },
  ossuary: { kind: 'interior' },
  pa: { kind: 'site' },
  pagoda: { kind: 'manifestation', of: 'temple' },
  palace: { kind: 'composite' },
  palace_complex: { kind: 'composite' },
  paladin_chapterhouse: { kind: 'archetype' },
  palaestra: { kind: 'form_only', structureType: 'infrastructure' },
  pawnshop: { kind: 'specialization', of: 'n' },
  pigsty: { kind: 'not_building' },
  planar_embassy: { kind: 'specialization', of: 'n' },
  poorhouse: { kind: 'archetype' },
  portal_chamber: { kind: 'specialization', of: 'n' },
  post_house: { kind: 'archetype' },
  potion_shop: { kind: 'specialization', of: 'n' },
  powder_magazine: { kind: 'specialization', of: 'n' },
  printing_press: { kind: 'archetype' },
  prison: { kind: 'archetype' },
  pyramid: { kind: 'form_only', structureType: 'monument' },
  ranger_station: { kind: 'specialization', of: 'n' },
  records_hall: { kind: 'archetype' },
  rectory: { kind: 'specialization', of: 'house' },
  ribat: { kind: 'manifestation', of: 'monastery' },
  ritual_chamber: { kind: 'interior' },
  root_cellar: { kind: 'interior' },
  ropewalk: { kind: 'specialization', of: 'n' },
  roundhouse: { kind: 'manifestation', of: 'house' },
  royal_mews: { kind: 'composite' },
  ryokan: { kind: 'manifestation', of: 'inn' },
  safe_house: { kind: 'overlay' },
  sail_loft: { kind: 'interior' },
  salt_works: { kind: 'archetype' },
  sanctum: { kind: 'interior' },
  schoolhouse: { kind: 'specialization', of: 'n' },
  scriptorium: { kind: 'interior' },
  shearing_shed: { kind: 'specialization', of: 'n' },
  sheepfold: { kind: 'not_building' },
  shinto_shrine: { kind: 'composite' },
  ship: { kind: 'form_only', structureType: 'vessel' },
  shipwreck_dwelling: { kind: 'specialization', of: 'house' },
  shipyard: { kind: 'composite' },
  shop: { kind: 'archetype' },
  shrine: { kind: 'interior' },
  siege_tower: { kind: 'not_building' },
  siheyuan: { kind: 'manifestation', of: 'house' },
  silo: { kind: 'specialization', of: 'n' },
  slaughterhouse: { kind: 'archetype' },
  smokehouse: { kind: 'specialization', of: 'n' },
  smugglers_den: { kind: 'overlay' },
  souk: { kind: 'composite' },
  sphinx: { kind: 'form_only', structureType: 'monument' },
  stable: { kind: 'archetype' },
  staithe: { kind: 'form_only', structureType: 'infrastructure' },
  statue: { kind: 'form_only', structureType: 'monument' },
  stave_church: { kind: 'manifestation', of: 'temple' },
  stoa: { kind: 'form_only', structureType: 'infrastructure' },
  stupa: { kind: 'form_only', structureType: 'monument' },
  summoning_hall: { kind: 'specialization', of: 'n' },
  sweat_lodge: { kind: 'manifestation', of: 'bathhouse' },
  synagogue: { kind: 'manifestation', of: 'temple' },
  tailor: { kind: 'specialization', of: 'n' },
  tannery: { kind: 'archetype' },
  tavern: { kind: 'archetype' },
  teahouse: { kind: 'manifestation', of: 'tavern' },
  temple: { kind: 'archetype' },
  temple_infirmary: { kind: 'specialization', of: 'n' },
  tenement: { kind: 'archetype' },
  tent_pavilion: { kind: 'specialization', of: 'house' },
  theater: { kind: 'archetype' },
  thermae: { kind: 'composite' },
  thieves_den: { kind: 'overlay' },
  tholos: { kind: 'manifestation', of: 'mausoleum' },
  threshing_barn: { kind: 'specialization', of: 'n' },
  throne_room: { kind: 'interior' },
  tipi: { kind: 'specialization', of: 'house' },
  tithe_barn: { kind: 'specialization', of: 'n' },
  tolbooth: { kind: 'manifestation', of: 'courthouse' },
  tollhouse: { kind: 'specialization', of: 'n' },
  tomb: { kind: 'interior' },
  tower: { kind: 'archetype' },
  town_hall: { kind: 'archetype' },
  townhouse: { kind: 'specialization', of: 'n' },
  trading_factory: { kind: 'manifestation', of: 'warehouse' },
  trading_post: { kind: 'archetype' },
  training_hall: { kind: 'archetype' },
  treasury: { kind: 'archetype' },
  triumphal_arch: { kind: 'form_only', structureType: 'monument' },
  undercroft: { kind: 'interior' },
  university_college: { kind: 'composite' },
  vardo_wagon: { kind: 'not_building' },
  wall_segment: { kind: 'form_only', structureType: 'fortification' },
  walled_town: { kind: 'site' },
  war_camp: { kind: 'site' },
  warded_vault: { kind: 'interior' },
  warehouse: { kind: 'archetype' },
  washhouse: { kind: 'archetype' },
  wat: { kind: 'composite' },
  watchtower: { kind: 'archetype' },
  water_tower: { kind: 'form_only', structureType: 'infrastructure' },
  watermill: { kind: 'specialization', of: 'n' },
  waystation: { kind: 'archetype' },
  weigh_house: { kind: 'archetype' },
  well_house: { kind: 'specialization', of: 'n' },
  wheelwright: { kind: 'specialization', of: 'n' },
  windmill: { kind: 'specialization', of: 'n' },
  wizard_tower: { kind: 'archetype' },
  workhouse: { kind: 'specialization', of: 'n' },
  workshop: { kind: 'interior' },
  yamen: { kind: 'composite' },
  yurt: { kind: 'specialization', of: 'house' },
  ziggurat: { kind: 'form_only', structureType: 'monument' },
} as const satisfies Record<BuildingCorpusId, BuildingCorpusDisposition>
