import type { OrganizationDomain } from './organization-domain'
import type { OrganizationForm } from './organization-form'
import type { OrganizationFunction } from './organization-function'
import type { OrganizationPractice } from './organization-practice'

/**
 * Ephemeral familiar starting points for organization authoring.
 *
 * Presets project editable domain / form / functions / practices only. Preset identity is
 * never persisted. `discoveryTerms` are authoring discovery strings that help
 * users find a closest starting point — not lexical aliases and not the same
 * field as `OrganizationClassificationEntry.searchTerms`.
 */
export type OrganizationAuthoringPresetEntry = {
  label: string
  /** Closest-starting-point rationale shown on the picker option. */
  description: string
  /** Adjacent familiar names and search helpers for picker discovery. */
  discoveryTerms?: readonly string[]
  domain: OrganizationDomain
  form?: OrganizationForm
  functions: readonly OrganizationFunction[]
  practices: readonly OrganizationPractice[]
}

export const ORGANIZATION_AUTHORING_PRESETS = {
  academy: {
    label: 'Academy',
    description: 'Closest starting point for bardic college, seminary, and teaching bodies.',
    discoveryTerms: ['bardic college', 'seminary', 'wizard circle'],
    domain: 'academic',
    form: 'association',
    functions: ['education', 'training', 'research'],
    practices: [],
  },
  adventurers_guild: {
    label: "Adventurers' guild",
    description:
      'Closest starting point for an adventurer hall, company, or monster hunters guild.',
    discoveryTerms: ["monster hunters' guild", 'adventuring company', 'treasure hunters'],
    domain: 'occupational',
    form: 'guild',
    functions: [],
    practices: [],
  },
  army: {
    label: 'Army',
    description:
      'Closest starting point for marines, garrison, legion, and other land armed hosts.',
    discoveryTerms: [
      'marines',
      'sky fleet',
      'garrison',
      'legion',
      'crusading host',
      'royal guard',
      'warband',
    ],
    domain: 'military',
    form: 'force',
    functions: ['warfare', 'defense'],
    practices: [],
  },
  bank: {
    label: 'Bank',
    description: 'Closest starting point for moneylenders, pawnbrokers, and tax farmers.',
    discoveryTerms: ['moneylenders', 'pawnbrokers', 'tax farmers', 'insurance company'],
    domain: 'commercial',
    form: 'company',
    functions: ['finance'],
    practices: ['banking'],
  },
  church: {
    label: 'Church',
    description: 'Closest starting point for temple and gathered faith communities.',
    discoveryTerms: ['temple', 'temple organization', 'heretical sect', 'pilgrimage society'],
    domain: 'religious',
    form: 'congregation',
    functions: ['worship', 'ministry'],
    practices: [],
  },
  city_council: {
    label: 'City council',
    description: 'Closest starting point for parliament, senate, and privy council.',
    discoveryTerms: ['parliament', 'senate', 'privy council'],
    domain: 'government',
    form: 'association',
    functions: [],
    practices: [],
  },
  city_watch: {
    label: 'City watch',
    description: 'Closest starting point for civic policing and crown law enforcement.',
    discoveryTerms: ['marshals'],
    domain: 'government',
    functions: ['policing'],
    practices: ['investigation'],
  },
  craft_guild: {
    label: 'Craft guild',
    description: 'Closest starting point for scribes, alchemists, and professional trade guilds.',
    discoveryTerms: [
      'merchant guild',
      'professional college',
      'hunters lodge',
      'scribes guild',
      'entertainers guild',
      'alchemists guild',
      'cartographers guild',
      'pilots guild',
      'advocates guild',
      'apothecaries guild',
      'teamsters guild',
      'river boatmen',
      'market association',
      'shopkeepers association',
      'factors guild',
      'ranchers association',
      'surgeons college',
    ],
    domain: 'occupational',
    form: 'guild',
    functions: ['standards', 'training'],
    practices: ['apprenticeship'],
  },
  gang: {
    label: 'Gang',
    description: 'Closest starting point for street gangs, wreckers, and prison crews.',
    discoveryTerms: ['wreckers', 'prison gang'],
    domain: 'criminal',
    functions: [],
    practices: [],
  },
  government_ministry: {
    label: 'Government ministry',
    description:
      'Closest starting point for customs service, provincial administration, and executive departments.',
    discoveryTerms: [
      'royal court',
      'magistracy',
      'exchequer',
      'diplomatic corps',
      'mint',
      'postal service',
      'customs service',
      'provincial governorate',
      'colonial administration',
    ],
    domain: 'government',
    form: 'office',
    functions: ['administration'],
    practices: [],
  },
  knightly_order: {
    label: 'Knightly order',
    description: 'Chivalric membership organized around martial discipline and sworn service.',
    domain: 'military',
    form: 'order',
    functions: ['warfare', 'defense'],
    practices: [],
  },
  mercenary_company: {
    label: 'Mercenary company',
    description: 'Closest starting point for ranger company and other hired fighting enterprises.',
    discoveryTerms: ['ranger company'],
    domain: 'military',
    form: 'company',
    functions: ['warfare'],
    practices: [],
  },
  mutual_aid_society: {
    label: 'Mutual aid society',
    description:
      'Closest starting point for burial societies, civic leagues, and reciprocal support bodies.',
    discoveryTerms: [
      'orphanage society',
      'famine relief society',
      'burial society',
      'civic league',
      'festival guild',
      'sporting club',
      'hospice society',
    ],
    domain: 'community',
    form: 'association',
    functions: ['aid'],
    practices: [],
  },
  political_party: {
    label: 'Political party',
    description: 'Closest starting point for reform league and advocacy society.',
    discoveryTerms: ['reform league', 'advocacy society'],
    domain: 'political',
    form: 'association',
    functions: ['advocacy'],
    practices: [],
  },
  religious_order: {
    label: 'Religious order',
    description: 'Closest starting point for monastery and rule-bound faith communities.',
    discoveryTerms: ['monastery'],
    domain: 'religious',
    form: 'order',
    functions: ['worship', 'ministry'],
    practices: [],
  },
  scholarly_society: {
    label: 'Scholarly society',
    description:
      'Closest starting point for guild of scholars, museum society, and research institute.',
    discoveryTerms: ['guild of scholars', 'museum society', 'research institute'],
    domain: 'academic',
    form: 'association',
    functions: ['research'],
    practices: [],
  },
  shipping_company: {
    label: 'Shipping company',
    description: 'Closest starting point for coach lines and courier services.',
    discoveryTerms: ['coach line', 'courier service'],
    domain: 'commercial',
    form: 'company',
    functions: ['transport'],
    practices: ['navigation'],
  },
  smuggling_ring: {
    label: 'Smuggling ring',
    description: 'Closest starting point for criminal syndicates and covert transport networks.',
    discoveryTerms: ['criminal syndicate'],
    domain: 'criminal',
    form: 'network',
    functions: [],
    practices: ['smuggling'],
  },
  thieves_guild: {
    label: "Thieves' guild",
    description: "Closest starting point for beggars' guild and urban criminal guilds.",
    discoveryTerms: ["beggars' guild"],
    domain: 'criminal',
    form: 'guild',
    functions: [],
    practices: ['theft'],
  },
  trading_company: {
    label: 'Trading company',
    description: 'Closest starting point for chartered company and general commerce.',
    discoveryTerms: [
      'chartered company',
      'auction house',
      'warehouse combine',
      'bazaar syndicate',
      'company of merchant adventurers',
      'fur company',
      'foundry works',
      'textile manufactory',
      'glassworks',
      'fishing fleet',
    ],
    domain: 'commercial',
    form: 'company',
    functions: ['trade'],
    practices: [],
  },
  assassins_order: {
    label: "Assassins' order",
    description: 'Covert order organized around contract killing and elimination.',
    discoveryTerms: ['assassins guild', 'killers guild'],
    domain: 'criminal',
    form: 'order',
    functions: [],
    practices: ['assassination'],
  },
  bounty_hunters: {
    label: 'Bounty hunters',
    description: 'Enterprise organized around pursuing fugitives for posted rewards.',
    discoveryTerms: ["bounty hunters' guild", 'manhunters'],
    domain: 'occupational',
    form: 'company',
    functions: [],
    practices: ['bounty_hunting', 'tracking'],
  },
  brewery: {
    label: 'Brewery',
    description: 'Commercial enterprise organized around beer and ale production.',
    discoveryTerms: ['brewery company', 'distillery'],
    domain: 'commercial',
    form: 'company',
    functions: ['production'],
    practices: ['brewing'],
  },
  caravan_company: {
    label: 'Caravan company',
    description: 'Land transport company moving goods and passengers overland.',
    discoveryTerms: ['caravan operators', 'wagon train company'],
    domain: 'commercial',
    form: 'company',
    functions: ['transport'],
    practices: ['navigation'],
  },
  charitable_foundation: {
    label: 'Charitable foundation',
    description: 'Association organized around one-way charitable aid and endowment.',
    discoveryTerms: ['philanthropic foundation', 'charity'],
    domain: 'community',
    form: 'association',
    functions: ['aid'],
    practices: [],
  },
  counterfeiting_ring: {
    label: 'Counterfeiting ring',
    description: 'Criminal network producing false coin and forged documents.',
    discoveryTerms: ['forgers ring', 'false coin ring'],
    domain: 'criminal',
    form: 'network',
    functions: [],
    practices: ['counterfeiting'],
  },
  cult: {
    label: 'Cult',
    description: 'Gathered faith community organized around devotion to a sect or mystery.',
    discoveryTerms: ["witches' coven", 'mystery cult', 'heretical sect'],
    domain: 'religious',
    form: 'congregation',
    functions: ['worship', 'ministry'],
    practices: [],
  },
  druid_circle: {
    label: 'Druid circle',
    description: 'Nature-focused order organized around worship and sacred stewardship.',
    discoveryTerms: ['nature cult', 'druid order'],
    domain: 'religious',
    form: 'order',
    functions: ['worship', 'stewardship'],
    practices: [],
  },
  explorers_society: {
    label: "Explorers' society",
    description: 'Scholarly association organized around exploration, mapping, and survey.',
    discoveryTerms: ['exploration society', 'survey society'],
    domain: 'academic',
    form: 'association',
    functions: ['research'],
    practices: ['cartography', 'surveying'],
  },
  farming_cooperative: {
    label: 'Farming cooperative',
    description: 'Member-owned cooperative organized around agricultural production.',
    discoveryTerms: ['millers cooperative', 'farmers cooperative'],
    domain: 'commercial',
    form: 'cooperative',
    functions: ['production'],
    practices: ['farming'],
  },
  fencing_network: {
    label: 'Fencing network',
    description: 'Black-market network trading stolen and illicit goods.',
    discoveryTerms: ['stolen goods network', 'black market ring'],
    domain: 'criminal',
    form: 'network',
    functions: [],
    practices: ['fencing'],
  },
  fraternal_lodge: {
    label: 'Fraternal lodge',
    description: 'Fellowship association organized around shared ritual and membership.',
    discoveryTerms: ['masonic lodge', 'brotherhood lodge'],
    domain: 'community',
    form: 'association',
    functions: [],
    practices: [],
  },
  hospital_order: {
    label: 'Hospital order',
    description: 'Religious order organized around care, ministry, and clinical medicine.',
    discoveryTerms: ['knights hospitaller', 'healer order'],
    domain: 'religious',
    form: 'order',
    functions: ['care', 'ministry'],
    practices: ['medicine'],
  },
  inquisition: {
    label: 'Inquisition',
    description: 'Religious office organized around doctrinal investigation and policing.',
    discoveryTerms: ['inquisitorial office', 'holy inquisition'],
    domain: 'religious',
    form: 'office',
    functions: ['policing'],
    practices: ['investigation'],
  },
  intelligence_bureau: {
    label: 'Intelligence bureau',
    description: 'Government office organized for strategic intelligence and covert inquiry.',
    discoveryTerms: ['secret police', 'spy bureau'],
    domain: 'government',
    form: 'office',
    functions: ['intelligence'],
    practices: ['espionage', 'investigation'],
  },
  labor_union: {
    label: 'Labor union',
    description: 'Occupational association organized around worker advocacy and standards.',
    discoveryTerms: ['trade union', 'workers union'],
    domain: 'occupational',
    form: 'association',
    functions: ['advocacy', 'standards'],
    practices: [],
  },
  logging_company: {
    label: 'Logging company',
    description: 'Extractive enterprise organized around timber and lumber production.',
    discoveryTerms: ['timber company', 'lumber company'],
    domain: 'commercial',
    form: 'company',
    functions: ['production'],
    practices: ['logging'],
  },
  mage_college: {
    label: 'Mage college',
    description: 'Arcane teaching body organized around education and alchemical craft.',
    discoveryTerms: ['wizard college', 'arcane academy'],
    domain: 'academic',
    form: 'association',
    functions: ['education', 'training', 'research'],
    practices: ['alchemy'],
  },
  merchant_house: {
    label: 'Merchant house',
    description: 'Family or partnership trading house organized around commerce.',
    discoveryTerms: ['trading house', 'merchant company'],
    domain: 'commercial',
    form: 'company',
    functions: ['trade'],
    practices: [],
  },
  militia: {
    label: 'Militia',
    description: 'Local levy or citizen force organized for territorial defense.',
    discoveryTerms: ['levy', 'town militia'],
    domain: 'military',
    form: 'force',
    functions: ['defense', 'training'],
    practices: [],
  },
  mining_company: {
    label: 'Mining company',
    description: 'Extractive enterprise organized around ore and mineral production.',
    discoveryTerms: ['mine company', 'quarry company'],
    domain: 'commercial',
    form: 'company',
    functions: ['production'],
    practices: ['mining'],
  },
  missionary_society: {
    label: 'Missionary society',
    description: 'Sending body organized around missionary ministry and outreach.',
    discoveryTerms: ['mission society', 'evangelical society'],
    domain: 'religious',
    form: 'association',
    functions: ['ministry'],
    practices: [],
  },
  navy: {
    label: 'Navy',
    description: 'Sea-going armed host organized for naval warfare and defense.',
    discoveryTerms: ['maritime fleet', 'fleet'],
    domain: 'military',
    form: 'force',
    functions: ['warfare', 'defense'],
    practices: ['navigation'],
  },
  pirate_crew: {
    label: 'Pirate crew',
    description: 'Criminal sea raiders organized as a crewed host.',
    discoveryTerms: ['privateer crew', 'buccaneers'],
    domain: 'criminal',
    form: 'force',
    functions: ['warfare', 'transport'],
    practices: ['piracy', 'navigation'],
  },
  private_security_company: {
    label: 'Private security company',
    description: 'Commercial company providing close protection and security services.',
    discoveryTerms: ['security firm', 'guard company'],
    domain: 'commercial',
    form: 'company',
    functions: ['defense'],
    practices: ['bodyguarding'],
  },
  protection_racket: {
    label: 'Protection racket',
    description: 'Criminal network organized around coercion and extortion payments.',
    discoveryTerms: ['racket', 'protection money'],
    domain: 'criminal',
    form: 'network',
    functions: [],
    practices: ['extortion'],
  },
  shipyard: {
    label: 'Shipyard',
    description: 'Production company building and repairing ships and hulls.',
    discoveryTerms: ['shipyard company', 'naval yard'],
    domain: 'commercial',
    form: 'company',
    functions: ['production'],
    practices: ['shipbuilding'],
  },
  spy_ring: {
    label: 'Spy ring',
    description: 'Covert network organized for intelligence gathering and infiltration.',
    discoveryTerms: ['spy network', 'espionage ring'],
    domain: 'criminal',
    form: 'network',
    functions: ['intelligence'],
    practices: ['espionage'],
  },
  theater_troupe: {
    label: 'Theater troupe',
    description: 'Performing company organized around staged entertainment.',
    discoveryTerms: ['acting company', 'players company'],
    domain: 'occupational',
    form: 'company',
    functions: [],
    practices: ['performance'],
  },
  university: {
    label: 'University',
    description: 'Higher teaching body organized around education, training, and research.',
    discoveryTerms: ['college', 'university body'],
    domain: 'academic',
    form: 'association',
    functions: ['education', 'training', 'research'],
    practices: [],
  },
} as const satisfies Record<string, OrganizationAuthoringPresetEntry>

export type OrganizationAuthoringPresetId = keyof typeof ORGANIZATION_AUTHORING_PRESETS

export const ORGANIZATION_AUTHORING_PRESET_IDS = Object.keys(
  ORGANIZATION_AUTHORING_PRESETS,
) as OrganizationAuthoringPresetId[]

/** Returns editable canonical defaults; no preset identity is retained. */
export function applyOrganizationAuthoringPreset(id: OrganizationAuthoringPresetId): {
  organizationDomain: OrganizationDomain
  organizationForm?: OrganizationForm
  functions: OrganizationFunction[]
  practices: OrganizationPractice[]
} {
  const preset = ORGANIZATION_AUTHORING_PRESETS[id]
  return {
    organizationDomain: preset.domain,
    ...('form' in preset ? { organizationForm: preset.form } : {}),
    functions: [...preset.functions],
    practices: [...preset.practices],
  }
}
