export const tableGridHeaderCellClasses = 'text-center font-medium'
export const tableGridRowHeaderCellClasses = 'font-medium'
export const tableGridRowHeaderHeaderClasses = 'w-20'
export const tableGridValueCellClasses = 'text-center'
export const tableGridEmptyBodyCellClasses = 'py-6 text-center text-sm text-muted-foreground'
