import { narrativeCollectionSchema } from '@rpg/contracts/character-narrative'

export const foundationCollection = narrativeCollectionSchema.parse({
  revision: 'foundation-6',
  fragments: [
    {
      id: 'duty-foundation-1',
      slot: 'personalityTraits',
      text: 'Before I promise anything, I write the name, deadline, and consequence in a pocket ledger.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-2',
      slot: 'personalityTraits',
      text: 'Before a difficult conversation, I rehearse my first sentence and decide what I will not promise.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-3',
      slot: 'ideals',
      text: 'When I give my word, I write down who is counting on it and what it will cost to keep.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-4',
      slot: 'bonds',
      text: 'I carry a written promise whose unfinished terms still direct where I go.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-5',
      slot: 'flaws',
      text: 'When two crews rely on me, I tell each that their work comes first until one discovers the lie.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-6',
      slot: 'experience',
      text: 'I promised the same afternoon to a ferryman and an apothecary. The ferryman still keeps my abandoned cargo under a tarpaulin and charges me for every wet day.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-7',
      slot: 'choice',
      text: 'When the night watch abandoned its post, I took the bell rope. The watch returned at dawn and now expects me to answer every alarm they miss.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-8',
      slot: 'motivation',
      text: 'A water-stained promise names a midwife and a crossroads. I am following both clues before the ink disappears.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-1',
      slot: 'personalityTraits',
      text: 'I set out each companion’s cup the way they prefer before they ask.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-2',
      slot: 'personalityTraits',
      text: 'In new company, I wait for two other people to reveal a secret before I offer one of mine.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-3',
      slot: 'ideals',
      text: 'When a newcomer reaches our fire, I make room before asking who invited them.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-4',
      slot: 'bonds',
      text: 'I carry the key to a former home and mean to learn who lives behind that door now.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-5',
      slot: 'flaws',
      text: 'When the host stops using my name, I pack before asking whether I am still welcome.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-6',
      slot: 'experience',
      text: 'At a guild supper, I gave my seat to the porter everyone left standing. The guildmaster still keeps one chair empty when I attend.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-7',
      slot: 'choice',
      text: 'When my old companions barred a rain-soaked traveler from their fire, I carried my bedroll to the roadside. They still keep my cup behind the bar.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-8',
      slot: 'motivation',
      text: 'I want to build a company where the last bowl, the floor, and a second chance are offered without rank.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-1',
      slot: 'personalityTraits',
      text: 'For every distant goal, I mark one door to knock on before sunset.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-2',
      slot: 'personalityTraits',
      text: 'When a subject catches my interest, I ask for names, dates, and the first witness who disagreed.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-3',
      slot: 'ideals',
      text: 'I keep working after the judges leave, especially on the part they praised too quickly.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-4',
      slot: 'bonds',
      text: 'I keep the failed first draft of a project I have sworn to complete.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-5',
      slot: 'flaws',
      text: 'After any success, I raise the standard so quickly that I exhaust myself and everyone helping me.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-6',
      slot: 'experience',
      text: 'I finished a clockwork survey after the other apprentices walked out. It works, but only they know why it gains a minute every midnight.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-7',
      slot: 'choice',
      text: 'I failed the guild trial in front of three masters and stole the marked scoring sheet afterward. One of them has begun asking who took it.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-8',
      slot: 'motivation',
      text: 'I am preparing for the capital’s open trial, where I intend to win a master’s seal without hiding who trained me.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'lg-ideals',
      slot: 'ideals',
      text: 'If my promise shields a dependent, I keep it even when their patron offers me an easier bargain.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-flaws',
      slot: 'flaws',
      text: 'When someone breaks a promise to me, I keep demanding proof long after they have made amends.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-choice',
      slot: 'choice',
      text: 'I kept escorting a wounded courier after the safe road closed. We arrived owing three favors, and the courier refuses to tell me what was in the message.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-motivation',
      slot: 'motivation',
      text: 'I am mapping a chain of guarded shelters where travelers can reach the next locked door before nightfall.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'ng-ideals',
      slot: 'ideals',
      text: 'When the work is praised, I name the hands that did it before I accept my share.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-flaws',
      slot: 'flaws',
      text: 'I give away time I need for my own work, then break promises when both demands come due.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-choice',
      slot: 'choice',
      text: 'When a fevered traveler was refused medicine for lacking a seal, I gave them my dose and missed the magistrate’s inspection. The magistrate still has my license.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-motivation',
      slot: 'motivation',
      text: 'I intend to restore the dry well, broken handcart, and empty night watch in the poorest ward before winter.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'cg-ideals',
      slot: 'ideals',
      text: 'When a custom locks a servant in place, I show them where the household keeps its spare key.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-flaws',
      slot: 'flaws',
      text: 'I rush to intervene before asking the people involved what help they actually want.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-choice',
      slot: 'choice',
      text: 'When the reeve locked a debtor in the grain shed, I pried open the back wall. The debtor escaped by another route and left my crowbar where the reeve could find it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-motivation',
      slot: 'motivation',
      text: 'I am opening two escape routes from the debtors’ quarter and leaving every captive a contract copy and a hidden purse.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'ln-ideals',
      slot: 'ideals',
      text: 'I write my rules inside my shield and read them aloud before I accept an exception.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-flaws',
      slot: 'flaws',
      text: 'If the procedure gives me an answer, I stop listening to facts that do not fit its boxes.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-choice',
      slot: 'choice',
      text: 'When a watchmate asked me to hide their broken seal, I entered both our names in the duty book. They served the penalty and kept the torn page.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-motivation',
      slot: 'motivation',
      text: 'I intend to win the records post and publish its standards where neither my superior nor I can alter them in private.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'n-ideals',
      slot: 'ideals',
      text: 'When an argument turns to principles, I ask what can be repaired before nightfall.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-flaws',
      slot: 'flaws',
      text: 'I put off taking a side until others have already paid the cost of waiting.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-choice',
      slot: 'choice',
      text: 'When two shopkeepers blamed each other for a collapsed awning, I repaired it and billed them equally. Both now bring me evidence against the other.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-motivation',
      slot: 'motivation',
      text: 'I want to broker a season-long truce between two feuding market streets before their next levy comes due.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'cn-ideals',
      slot: 'ideals',
      text: 'I leave space in every plan for the road, offer, or person nobody expected.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-flaws',
      slot: 'flaws',
      text: 'The moment a useful routine becomes expected, I skip it just to prove I still can.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-choice',
      slot: 'choice',
      text: 'When my household arranged my next year without asking, I left through the kitchen yard. My aunt sends each innkeeper a new letter describing me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-motivation',
      slot: 'motivation',
      text: 'I mean to chart the unmapped road beyond the salt marsh and return before the paid notice above my bed expires.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'le-ideals',
      slot: 'ideals',
      text: 'Before I enter a bargain, I learn which clause lets me collect after everyone else thinks it is settled.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-flaws',
      slot: 'flaws',
      text: 'When a subordinate resists my plan, I add conditions until agreeing is easier than arguing.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-choice',
      slot: 'choice',
      text: 'I bound a grain factor to a contract whose penalties only they can trigger. Their clerk has begun buying copies of my earlier agreements.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-motivation',
      slot: 'motivation',
      text: 'I am building a chain of debtors in every town on the north road so I never have to bargain from weakness again.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'ne-ideals',
      slot: 'ideals',
      text: 'Before I accept an opportunity, I count what leverage remains mine if the patron withdraws.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-flaws',
      slot: 'flaws',
      text: 'When someone offers me something freely, I immediately start looking for the price they have not named.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-choice',
      slot: 'choice',
      text: 'When one promotion remained, I exposed a rival’s private mistake and took the position. The gain was real, but their knowledge of what I did has made every later meeting a negotiation.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-motivation',
      slot: 'motivation',
      text: 'I am buying warehouses, favors, and votes until no creditor can make me beg, and I drop each ally when their price rises.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ce-ideals',
      slot: 'ideals',
      text: 'When an official tells me what I may not take, I look first for the lock they trust.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-flaws',
      slot: 'flaws',
      text: 'When someone crosses me, I keep pushing long after I have already gotten what I wanted.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-choice',
      slot: 'choice',
      text: 'A customs officer mocked me in the market, so I burned the tariff ledger that kept their stall profitable. Three merchants still know who struck the spark.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-motivation',
      slot: 'motivation',
      text: 'I am collecting keys, favors, and names until no customs officer can strand me at a closed gate.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'lg-ideals-alt',
      slot: 'ideals',
      text: 'When keeping the peace requires silence about a wrong, I name it in front of the people asked to endure it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-flaws-alt',
      slot: 'flaws',
      text: 'When mercy fails once, I offer it again even while the same offender keeps causing harm.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-choice-alt',
      slot: 'choice',
      text: 'When my captain ordered me to ignore grain stolen from the poorhouse, I filed the charge under both our names. The captain was cleared and now controls my next posting.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-motivation-alt',
      slot: 'motivation',
      text: 'I want to reopen the poorhouse audit and put its missing witness before a magistrate who cannot bury the record.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'ng-ideals-alt',
      slot: 'ideals',
      text: 'I repay a kindness where its giver needs it, not where an audience can praise me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-flaws-alt',
      slot: 'flaws',
      text: 'I assume the crew can manage without me and return only after the scaffold collapses.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-choice-alt',
      slot: 'choice',
      text: 'When a mason asked me to claim her bridge design, I named her before the council. My former sponsor now funds her next commission.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-motivation-alt',
      slot: 'motivation',
      text: 'I am restoring an abandoned physic garden so the empty sickroom beside it can reopen before fever season.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'cg-ideals-alt',
      slot: 'ideals',
      text: 'When a captive refuses my escape plan, I leave the tools within reach and let them choose the hour.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-flaws-alt',
      slot: 'flaws',
      text: 'When a rule blocks me, I challenge the person enforcing it before I look for another route.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-choice-alt',
      slot: 'choice',
      text: 'When a council banned a harmless trade, I taught the sellers a route the guards had not mapped. The market survived, but the fines fell on people who trusted my plan without reading its risks.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-motivation-alt',
      slot: 'motivation',
      text: 'I want to establish a refuge where anyone can leave without permission and still find the door open when they return.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'ln-ideals-alt',
      slot: 'ideals',
      text: 'I follow the written measure after the inspector leaves, even when every other stall changes its weights.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln', 'lg'],
    },
    {
      id: 'ln-flaws-alt',
      slot: 'flaws',
      text: 'If an improvisation was not in the plan I announced, I reject it even while that plan is failing.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-choice-alt',
      slot: 'choice',
      text: 'I refused a shortcut that broke the method engraved on my commission. The client kept the reward and now displays my unfinished work as a warning.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-motivation-alt',
      slot: 'motivation',
      text: 'I am seeking an office where the standard is posted at the door and even the loudest patron must sign the same ledger.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'n-ideals-alt',
      slot: 'ideals',
      text: 'When two sides demand a verdict, I first price the repair each is willing to make.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-flaws-alt',
      slot: 'flaws',
      text: 'When everyone else chooses a side quickly, I assume I am the only one still thinking clearly.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n', 'cn'],
    },
    {
      id: 'n-choice-alt',
      slot: 'choice',
      text: 'When a mediator asked me to endorse a harsh punishment, I offered restitution instead. Neither side thanked me, but the injured party recovered enough to keep working.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-motivation-alt',
      slot: 'motivation',
      text: 'I want to negotiate one season of peace between the quarry crews before either side hires more guards.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'cn-ideals-alt',
      slot: 'ideals',
      text: 'Before I follow a new trail, I leave a note, a return hour, and my signet as a reason to come back.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-flaws-alt',
      slot: 'flaws',
      text: 'When a surprise invitation arrives, I invent a reason to ruin the plan before anyone can withdraw it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-choice-alt',
      slot: 'choice',
      text: 'When a festival locked me into a role I had outgrown, I traded costumes with a street acrobat and vanished into the crowd. The organizer still has the acrobat’s name on my contract.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-motivation-alt',
      slot: 'motivation',
      text: 'I am charting an unmarked route through the western hills and leaving supply notes at every place I might turn aside.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'le-ideals-alt',
      slot: 'ideals',
      text: 'I keep duplicate ledgers in different hands so my system keeps collecting when I am gone.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-flaws-alt',
      slot: 'flaws',
      text: 'When a loyal follower disagrees with me, I seize the duties and access I once trusted them to hold.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-choice-alt',
      slot: 'choice',
      text: 'When a rival offered a shared profit if I looked away from their smuggling, I accepted the ledger and exposed them at the audit. The profit vanished, but the route stayed licensed under my name.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-motivation-alt',
      slot: 'motivation',
      text: 'I want the post that controls travel seals, debt records, and whose petition reaches the council.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'ne-ideals-alt',
      slot: 'ideals',
      text: 'I write every bargain so the other party leaves satisfied and I keep the favor they forgot to price.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-flaws-alt',
      slot: 'flaws',
      text: 'I renegotiate every favor the moment the other person shows they still need me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-choice-alt',
      slot: 'choice',
      text: 'When a patron offered to erase my debts if I lied for them in court, I traded the lie for a slower payment plan with witnesses. I kept my freedom and still owe them interest they enjoy collecting.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-motivation-alt',
      slot: 'motivation',
      text: 'I am binding three river merchants to my venture so each loses more from abandoning me than from seeing me succeed.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ce-ideals-alt',
      slot: 'ideals',
      text: 'If someone humiliates me in public, I wait until I can embarrass them before the same crowd.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-flaws-alt',
      slot: 'flaws',
      text: 'If someone insults me before witnesses, I make sure my answer has witnesses too.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-choice-alt',
      slot: 'choice',
      text: 'When an employer withheld my pay, I sold their private schedule to a competitor. I was paid twice, and the employer has posted my description at every hiring hall.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-motivation-alt',
      slot: 'motivation',
      text: 'I look for leverage over anyone who controls my food, shelter, or passage, and I use it before they can use theirs.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'context-1',
      slot: 'bonds',
      text: 'I take the jobs everyone in {{organization.name}} leaves unsigned, and I keep the receipts.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-2',
      slot: 'bonds',
      text: 'The member who signed me into {{organization.name}} risked their post. I answer every summons bearing their seal.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-3',
      slot: 'experience',
      text: 'On my first assignment for {{organization.name}}, I found a senior member’s false total and reported it. They corrected the work, but they now check every account I submit.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-4',
      slot: 'experience',
      text: 'A shopkeeper called me {{organization.title}} and demanded that {{organization.name}} protect his store. I gave the order without authority, and my superiors still expect me to justify its cost.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.title', 'organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-5',
      slot: 'bonds',
      text: 'I keep a bed made in {{residence.name}} for the courier who vanished carrying my reply.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['residence.name'],
      conditions: ['placeRole.residence'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-6',
      slot: 'experience',
      text: 'When floodwater reached {{residence.name}}, I rationed the cellar stores by household. The family I cut off still has my tally sheet.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['residence.name'],
      conditions: ['placeRole.residence'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-hometown-1',
      slot: 'bonds',
      text: 'I owe {{hometown.name}} a service I promised before I left, and I mean to return able to provide it.',
      themeIds: ['belonging', 'duty'],
      requires: ['hometown.name'],
      conditions: ['placeRole.hometown'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-org-obligation-1',
      slot: 'ideals',
      text: 'When {{organization.name}} sends its marked summons, I answer before asking whether the duty is convenient.',
      themeIds: ['duty'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-mentor-1',
      slot: 'experience',
      text: 'I ignored {{mentor.name}}’s warning and cracked the lens we used for lessons. They kept the largest shard and have never told me why.',
      themeIds: ['duty', 'ambition', 'belonging'],
      requires: ['mentor.name'],
      conditions: ['personRole.mentor'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-child-1',
      slot: 'bonds',
      text: 'I promised {{child.name}} I would return with an answer to the question they trusted me to solve.',
      themeIds: ['duty', 'belonging'],
      requires: ['child.name'],
      conditions: ['personRole.child'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-rival-1',
      slot: 'flaws',
      text: 'Whenever {{rival.name}} succeeds, I attempt the same feat by a harder method before anyone asks me to.',
      themeIds: ['ambition', 'duty'],
      requires: ['rival.name'],
      conditions: ['personRole.rival'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-7',
      slot: 'experience',
      text: 'The examiner who certified my {{class.name}} training kept the work I ruined by rushing. They say I can reclaim it after I complete the same test without skipping a step.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['class.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-8',
      slot: 'personalityTraits',
      text: 'The instructor who first called me a {{class.name}} demanded three named steps before every attempt; I repeat them when a plan gets complicated.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['class.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-9',
      slot: 'personalityTraits',
      text: 'When strangers question what it means to be {{species.name}}, I ask which of my habits they have already mistaken.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['species.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-10',
      slot: 'experience',
      text: 'A magistrate wrote “{{species.name}}” beside my name before I spoke, then refused me a place on the survey. The same magistrate now asks me to vouch for its accuracy.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['species.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-11',
      slot: 'bonds',
      text: 'I carry an heirloom marked for the {{heritage.name}} line, but the relative who gave it to me scratched out its owner’s name.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['heritage.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-12',
      slot: 'experience',
      text: 'At a {{culture.name}} memorial, I gave the absent traveler’s place to the gravedigger barred from the table. The host still demands that I restore the old seating order.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['culture.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-13',
      slot: 'personalityTraits',
      text: 'I copy unfamiliar diagrams before their owners decide whether I am allowed to see them.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:wizard'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-14',
      slot: 'personalityTraits',
      text: 'Before I trust a borrowed weapon, I test its balance with the move most likely to expose a flaw.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:fighter'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-15',
      slot: 'personalityTraits',
      text: 'I repeat a speaker’s rhythm when I want the room to remember their exact words.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:bard'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-16',
      slot: 'personalityTraits',
      text: 'I notice paths and exits before settling into an unfamiliar place.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:ranger', 'class:rogue'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-17',
      slot: 'personalityTraits',
      text: 'Before an important task, I repeat the same breathing count my first instructor enforced.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:monk', 'class:cleric'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-18',
      slot: 'personalityTraits',
      text: 'I interrupt a journey when the birds or roadside plants stop behaving as they did the day before.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:druid'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-19',
      slot: 'flaws',
      text: 'After a difficult conversation, I rehearse better replies aloud and miss what the next person is saying.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-20',
      slot: 'flaws',
      text: 'I patch the same worn-out tool after every failure and reach for it again when the next job turns dangerous.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-21',
      slot: 'bonds',
      text: 'I left a clockmaker’s commission unfinished after the foreman mocked my hands, and I still carry its missing gear.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-22',
      slot: 'bonds',
      text: 'I carry the sealed examination my former teacher said I was not ready to open.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-23',
      slot: 'personalityTraits',
      text: 'Whenever I stop to rest, I point my boots toward the exit and sleep with the map under my left hand.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-24',
      slot: 'personalityTraits',
      text: 'During an argument, I sharpen a blade or sort coins until I know which question to ask.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-trait-pressure-1',
      slot: 'personalityTraits',
      text: 'When plans conflict, I protect the promise another person is already counting on.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-trait-pressure-2',
      slot: 'personalityTraits',
      text: 'At a new inn, camp, or hall, I find the cook, porter, or cleaner everyone else talks past.',
      themeIds: ['belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-ideal-stewardship-1',
      slot: 'ideals',
      text: 'Before I return an entrusted tool, map, or animal, I repair one weakness and mark what I changed.',
      themeIds: ['duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-ideal-hospitality-1',
      slot: 'ideals',
      text: 'When food is short, I watch who gets served last and move my bowl to their table.',
      themeIds: ['belonging', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-debt-1',
      slot: 'bonds',
      text: 'A caravan guard once paid my road toll and lost their place in line; I am following the stamped receipt to repay them.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-rivalry-1',
      slot: 'bonds',
      text: 'A rival holds the only honest measure of my best work, and I need one more contest with them.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-possession-1',
      slot: 'bonds',
      text: 'I guard a sealed parcel left by a courier who vanished before naming its destination.',
      themeIds: ['duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-witness-1',
      slot: 'bonds',
      text: 'I was the only witness when a dying soldier promised half his pay to his sister, and I still have the paymaster’s ledger.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-place-1',
      slot: 'bonds',
      text: 'The riverside shrine sheltered me during a winter storm; I send lamp oil whenever its keeper writes.',
      themeIds: ['belonging', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'relationship-org-bond-2',
      slot: 'bonds',
      text: 'I accepted unfinished work from a departed member of {{organization.name}}, and I will not let their effort disappear.',
      themeIds: ['duty', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-org-bond-3',
      slot: 'bonds',
      text: 'A vote I cast inside {{organization.name}} cost an apprentice their post. I carry the sealed minutes they were never allowed to read.',
      themeIds: ['duty', 'belonging'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-hometown-2',
      slot: 'bonds',
      text: 'The clerk in {{hometown.name}} keeps a birth register I altered, and my younger cousin is about to request a copy.',
      themeIds: ['belonging', 'duty'],
      requires: ['hometown.name'],
      conditions: ['placeRole.hometown'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-residence-1',
      slot: 'bonds',
      text: 'I hid a bloodstained signet beneath the hearth in {{residence.name}}, and the mason begins repairs next week.',
      themeIds: ['belonging', 'ambition'],
      requires: ['residence.name'],
      conditions: ['placeRole.residence'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-mentor-2',
      slot: 'bonds',
      text: 'I possess the last task {{mentor.name}} gave me, and I refuse to call our lessons finished until I attempt it.',
      themeIds: ['duty', 'ambition'],
      requires: ['mentor.name'],
      conditions: ['personRole.mentor'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-child-2',
      slot: 'bonds',
      text: 'I reserve a seat, a share, and an escape route for {{child.name}}, even when they insist they can fend for themselves.',
      themeIds: ['duty', 'belonging'],
      requires: ['child.name'],
      conditions: ['personRole.child'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-rival-2',
      slot: 'bonds',
      text: 'Only {{rival.name}} knows whether my proudest victory was fairly earned, and I need their answer.',
      themeIds: ['ambition', 'duty'],
      requires: ['rival.name'],
      conditions: ['personRole.rival'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-heritage-1',
      slot: 'bonds',
      text: 'I promised to place an account of my {{heritage.name}} heritage where the next seeker can find it.',
      themeIds: ['belonging', 'duty'],
      requires: ['heritage.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'foundation-flaw-rescue-1',
      slot: 'flaws',
      text: 'When an apprentice struggles, I seize their tools without asking and make them fight both the work and me.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-flaw-credit-1',
      slot: 'flaws',
      text: 'When my contribution goes unrecognized, I lock away the next useful draft until the foreman notices its absence.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-flaw-loyalty-1',
      slot: 'flaws',
      text: 'When a companion is accused, I attack the accuser’s story before I ask whether my companion is guilty.',
      themeIds: ['belonging', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-flaw-proof-1',
      slot: 'flaws',
      text: 'When my competence is challenged, I attempt the hardest solution before the sensible one.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-flaw-secrecy-1',
      slot: 'flaws',
      text: 'When I make a mistake under pressure, I hide it and let my companions keep relying on the false account.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-debt-1',
      slot: 'experience',
      text: 'When I could not pay the winter inn bill, a traveling cooper pledged their guild mark for me. They vanished before the debt came due, and the innkeeper still holds the mark.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-failure-1',
      slot: 'experience',
      text: 'I led the kiln firing and ignored the clay mixer’s warning. Every vessel cracked, and the mixer kept one shard bearing my maker’s mark.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-mercy-1',
      slot: 'experience',
      text: 'I caught a laundress stealing medicine from the chest I guarded and let her take one vial. I replaced it with my own coin, but she returned for the rest.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-rivalry-1',
      slot: 'experience',
      text: 'A rival and I pursued the same prize until an accident put it beyond either of us alone. I offered a temporary partnership, and sharing the result saved our work while making the next contest far more personal.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-departure-1',
      slot: 'experience',
      text: 'On the morning I was expected to stay, I packed one bag and left my brother a note instead of an answer. His unopened reply follows me from inn to inn.',
      themeIds: ['belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'relationship-org-experience-1',
      slot: 'experience',
      text: 'When {{organization.name}} divided over an urgent shipment, I backed the faster route. The cargo arrived, but the quartermaster injured on that road now holds the deciding vote on my promotion.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-org-experience-2',
      slot: 'experience',
      text: 'I broke {{organization.name}} procedure to release a ferry before inspection. The passengers crossed in time, but the unsigned manifest is now evidence in an inquiry.',
      themeIds: ['duty', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-hometown-experience-1',
      slot: 'experience',
      text: 'During a fire in {{hometown.name}}, I carried messages between the miller and the well keeper and changed each demand into a request. They cooperated, but both still possess different copies of my account.',
      themeIds: ['belonging', 'duty'],
      requires: ['hometown.name'],
      conditions: ['placeRole.hometown'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-residence-experience-1',
      slot: 'experience',
      text: 'When the roof of {{residence.name}} caught fire, I saved my lockbox before the upstairs tenant’s letters. The tenant survived and still asks what was worth carrying out first.',
      themeIds: ['belonging', 'duty'],
      requires: ['residence.name'],
      conditions: ['placeRole.residence'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-mentor-experience-2',
      slot: 'experience',
      text: 'I challenged {{mentor.name}}’s bridge survey in front of the work crew. My measurements held, but they have answered every private question with a formal note since.',
      themeIds: ['ambition', 'belonging', 'duty'],
      requires: ['mentor.name'],
      conditions: ['personRole.mentor'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-child-experience-1',
      slot: 'experience',
      text: 'When {{child.name}} copied my shortcut through a locked yard, the kennel hound bit them instead of me. They kept the broken lock and ask why my rules changed afterward.',
      themeIds: ['duty', 'belonging'],
      requires: ['child.name'],
      conditions: ['personRole.child'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-rival-experience-1',
      slot: 'experience',
      text: 'During a public trial, I hid the evidence that would have embarrassed {{rival.name}} and lost by one mark. They found the evidence later and have not decided whether I spared or underestimated them.',
      themeIds: ['ambition', 'duty'],
      requires: ['rival.name'],
      conditions: ['personRole.rival'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-class-experience-2',
      slot: 'experience',
      text: 'A village council hired me after reading “{{class.name}}” on a guild roster. The usual method failed, and the local guide who saved the work now wants their name added to my license.',
      themeIds: ['duty', 'ambition', 'belonging'],
      requires: ['class.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-culture-experience-2',
      slot: 'experience',
      text: 'I defended a {{culture.name}} burial verse from memory until an archivist produced a different final line. The page with the older ending has since disappeared from their collection.',
      themeIds: ['belonging', 'ambition'],
      requires: ['culture.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'foundation-choice-truth-1',
      slot: 'choice',
      text: 'When silence would have preserved my council seat, I admitted that the dismissed porter had designed our successful route. The porter has returned with terms the council refuses to read aloud.',
      themeIds: ['belonging', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-choice-legacy-1',
      slot: 'choice',
      text: 'I was offered credit for finishing a missing architect’s plans. I named them at the dedication, and their signature has since appeared on a building completed after they vanished.',
      themeIds: ['ambition', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-motivation-answer-1',
      slot: 'motivation',
      text: 'I am following the cartographer who trusted me with an unanswered question, and I will bring back the missing survey page rather than a comforting guess.',
      themeIds: ['duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-motivation-refuge-1',
      slot: 'motivation',
      text: 'I am bringing masons, archers, and river pilots to a flood-prone village before its new walls cut off the only escape by boat.',
      themeIds: ['belonging', 'duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'relationship-former-org-experience-1',
      slot: 'experience',
      text: 'Before I left {{organization.name}}, I accepted blame for a shared failure so another member could remain. My departure protected their position but let the false account stand, and I now carry evidence that could clear my name at their expense.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.former'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-partner-1',
      slot: 'bonds',
      text: 'I promised {{partner.name}} that one shared decision would wait for my return, even though delay may close the safest option.',
      themeIds: ['duty', 'belonging'],
      requires: ['partner.name'],
      conditions: ['personRole.partner'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-parent-1',
      slot: 'bonds',
      text: 'I have a question for {{parent.name}} that only matters if I hear the answer from them directly.',
      themeIds: ['belonging', 'duty'],
      requires: ['parent.name'],
      conditions: ['personRole.parent'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-birthplace-experience-1',
      slot: 'experience',
      text: 'On my last visit to {{birthplace.name}}, I accused the shrine keeper of neglecting a broken statue. The repair exposed a hidden boundary marker, and two families now demand that I say where it belongs.',
      themeIds: ['belonging', 'duty'],
      requires: ['birthplace.name'],
      conditions: ['placeRole.birthplace'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-property-1',
      slot: 'bonds',
      text: 'I share responsibility for {{property.name}} with a co-owner who wants it demolished, and neither signature can settle its future alone.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['property.name'],
      conditions: ['placeRole.property'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'actionable-trait-rations-1',
      slot: 'personalityTraits',
      text: 'When rations run short, I count every bowl and ask the cook who has not eaten.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-trait-secrets-1',
      slot: 'personalityTraits',
      text: 'When a door is locked, I watch who touches the key before I ask what is behind it.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-ideal-witness-1',
      slot: 'ideals',
      text: 'If a promise has no witness, I write it down and give the other person the copy.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-ideal-credit-1',
      slot: 'ideals',
      text: 'Before rewards are divided, I name the quietest contributor and ask what share they were offered.',
      themeIds: ['belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-bond-ledger-1',
      slot: 'bonds',
      text: 'The quartermaster who altered my pay ledger still has the original page, and I need it before the next audit.',
      themeIds: ['duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-bond-bell-1',
      slot: 'bonds',
      text: 'I carry the clapper from a river village’s flood bell and cannot return without explaining why it failed.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-flaw-insult-1',
      slot: 'flaws',
      text: 'When I am mocked before a crowd, I abandon the useful argument and hunt for a secret that will turn the crowd.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-flaw-authority-1',
      slot: 'flaws',
      text: 'I keep stolen copies of permits and use them before asking an official for help.',
      themeIds: ['ambition', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-experience-pay-1',
      slot: 'experience',
      text: 'I witnessed a mercenary promise half his pay to a dead companion’s family. He survived, and the paymaster says no such promise was recorded.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-choice-records-1',
      slot: 'choice',
      text: 'When the registrar barred my entry, I stole the admissions ledger instead of appealing. Every rejected name is still inside it.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-motivation-key-1',
      slot: 'motivation',
      text: 'I am looking for the locksmith who made a second key to my room and sold it before I arrived.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'actionable-motivation-promise-1',
      slot: 'motivation',
      text: 'I must deliver a soldier’s final letter before their sister accepts an offer from the officer named inside it.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
  ],
})
