import { narrativeCollectionSchema } from '@rpg/contracts/character-narrative'

export const foundationCollection = narrativeCollectionSchema.parse({
  revision: 'foundation-4',
  fragments: [
    {
      id: 'duty-foundation-1',
      slot: 'personalityTraits',
      text: 'I keep careful track of the commitments I make.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-2',
      slot: 'personalityTraits',
      text: 'I prepare for a difficult conversation before I begin it.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-3',
      slot: 'ideals',
      text: 'A commitment I choose deserves honest work, not excuses or appearances.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-4',
      slot: 'bonds',
      text: 'I carry a written promise whose unfinished terms still direct where I go.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-5',
      slot: 'flaws',
      text: 'When others rely on me, I conceal how overextended I am until something important is neglected.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-6',
      slot: 'experience',
      text: 'When two people expected my help at the same time, I tried to satisfy both and failed one of them. I began naming which duties I had actually accepted, and now I ask what must give before I promise more.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-7',
      slot: 'choice',
      text: 'When an unwanted responsibility was left unattended, I claimed it rather than watch the harm spread. The work cost me time I had reserved for myself, but it became a duty I still refuse to abandon.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-8',
      slot: 'motivation',
      text: 'I am seeking the person or place named in my unfinished promise, and I will ask for help before that duty consumes every other obligation.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-1',
      slot: 'personalityTraits',
      text: 'I remember the small habits of people I spend time with.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-2',
      slot: 'personalityTraits',
      text: 'I listen for a while before deciding how much of myself to reveal.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-3',
      slot: 'ideals',
      text: 'Belonging must be offered and renewed; no label gives one person ownership of another.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-4',
      slot: 'bonds',
      text: 'I carry the key to a former home and mean to learn who lives behind that door now.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-5',
      slot: 'flaws',
      text: 'When someone’s tone changes, I assume I am being pushed out and withdraw before asking why.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-6',
      slot: 'experience',
      text: 'At a crowded gathering, I watched a newcomer repeatedly ignored and finally made room beside me. That small invitation drew criticism from someone I trusted, and I stopped treating a group’s customs as proof that everyone was welcome.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-7',
      slot: 'choice',
      text: 'When my familiar circle demanded that I exclude someone, I sat with the outsider instead. I lost an easy welcome, but gained a clearer standard for the company I choose.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-8',
      slot: 'motivation',
      text: 'I am looking for companions who make room for disagreement, and I test a new group by noticing whom it interrupts, protects, and leaves outside.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-1',
      slot: 'personalityTraits',
      text: 'I turn distant goals into small tasks I can begin today.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-2',
      slot: 'personalityTraits',
      text: 'I ask precise questions when something catches my interest.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-3',
      slot: 'ideals',
      text: 'Worthwhile mastery is proved by difficult work completed, not praise collected.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-4',
      slot: 'bonds',
      text: 'I keep the failed first draft of a project I have sworn to complete.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-5',
      slot: 'flaws',
      text: 'After any success, I raise the standard so quickly that I exhaust myself and everyone helping me.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-6',
      slot: 'experience',
      text: 'I stayed after the others abandoned a difficult piece of work and repeated it until one small improvement finally held. Finishing alone earned me the result but cost me their help, so I now decide whether mastery or cooperation matters more before I begin.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-7',
      slot: 'choice',
      text: 'I entered a demanding trial before I felt ready and failed in front of people whose respect I wanted. I returned to practice the part I had avoided, and the next attempt proved that embarrassment could be useful evidence.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-8',
      slot: 'motivation',
      text: 'I am seeking a public test of my skill, but I will not sacrifice the people who helped me merely to claim the result alone.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'lg-ideals',
      slot: 'ideals',
      text: 'A promise matters most when keeping it protects someone who cannot repay me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-flaws',
      slot: 'flaws',
      text: 'I can be slow to forgive a broken promise, even when the person is trying to make amends.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-choice',
      slot: 'choice',
      text: 'When a promised escort became dangerous, I completed it instead of taking the safer road alone. We arrived late and indebted to those who aided us, so I no longer confuse keeping my word with carrying every burden myself.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-motivation',
      slot: 'motivation',
      text: 'I seek work that leaves vulnerable people safer, and I ask those affected what protection means before imposing my own solution.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'ng-ideals',
      slot: 'ideals',
      text: 'Helping someone matters more to me than receiving credit for it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-flaws',
      slot: 'flaws',
      text: 'I give away time I need for my own work, then break promises when both demands come due.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-choice',
      slot: 'choice',
      text: 'When a stranger was denied aid over a technicality, I shared my own supplies and missed an appointment. Their recovery mattered more than my reputation, but the cost taught me to prepare before offering what others depend on.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-motivation',
      slot: 'motivation',
      text: 'I look for neglected problems where my abilities can make a measurable difference, especially when helping earns no audience or reward.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'cg-ideals',
      slot: 'ideals',
      text: 'No custom deserves my loyalty when it is used to keep someone helpless.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-flaws',
      slot: 'flaws',
      text: 'I rush to intervene before asking the people involved what help they actually want.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-choice',
      slot: 'choice',
      text: 'When an authority barred someone from leaving, I opened a way out without permission. The person rejected the route I chose but showed me another, and their escape taught me to pair defiance with listening.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-motivation',
      slot: 'motivation',
      text: 'I seek people trapped by coercive rules and offer them options, resources, and an exit without demanding that they choose my preferred path.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'ln-ideals',
      slot: 'ideals',
      text: 'I hold myself to a chosen code even when it brings me no advantage.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-flaws',
      slot: 'flaws',
      text: 'I can mistake a clear procedure for a complete understanding of a problem.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-choice',
      slot: 'choice',
      text: 'When a friend asked me to conceal a breach I was responsible for reporting, I recorded it and shared the penalty. I kept my code but damaged their trust, so now I explain the rules I accept before others rely on my discretion.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-motivation',
      slot: 'motivation',
      text: 'I seek a responsibility with clear standards and real consequences, where I can prove my code survives inconvenience without treating judgment as disobedience.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'n-ideals',
      slot: 'ideals',
      text: 'I prefer a workable decision to a grand claim about how everyone should live.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-flaws',
      slot: 'flaws',
      text: 'I put off taking a side until others have already paid the cost of waiting.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-choice',
      slot: 'choice',
      text: 'When two neighbors demanded my support, I repaired the shared damage without endorsing either accusation. The repair held, but their feud worsened, and I saw that solving the practical problem had not made me neutral.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-motivation',
      slot: 'motivation',
      text: 'I gather facts, preserve alternatives, and commit only when delay would cost more than a mistaken choice.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'cn-ideals',
      slot: 'ideals',
      text: 'I value the freedom to change my course when a new possibility catches my attention.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-flaws',
      slot: 'flaws',
      text: 'I abandon useful routines simply because they begin to feel like expectations.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-choice',
      slot: 'choice',
      text: 'When others planned my next year without asking me, I left by an unfamiliar route before their arrangements became obligations. I gained freedom and lost reliable support, a trade I still manage rather than pretend away.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-motivation',
      slot: 'motivation',
      text: 'I pursue opportunities with room to improvise, but I name one obligation I will finish before the next novelty pulls me away.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'le-ideals',
      slot: 'ideals',
      text: 'Stable rules are valuable because careful preparation lets me benefit from them longer than force would.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-flaws',
      slot: 'flaws',
      text: 'When a plan depends on my control, I reject simpler compromises and turn small resistance into a contest of authority.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-choice',
      slot: 'choice',
      text: 'When a supplier needed certainty, I offered a long contract whose penalties protected me more than them. The arrangement secured my position without violence, but their resentment now threatens the order I meant to build.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-motivation',
      slot: 'motivation',
      text: 'I seek authority over a durable system of favors and obligations, preferring predictable leverage to wasteful cruelty or spectacle.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'ne-ideals',
      slot: 'ideals',
      text: 'I judge opportunities by the security and advantage they bring me, not by whether others consider my ambition generous.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-flaws',
      slot: 'flaws',
      text: 'I treat sincere generosity as hidden leverage and often insult the few people who meant to help freely.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-choice',
      slot: 'choice',
      text: 'When one promotion remained, I exposed a rival’s private mistake and took the position. The gain was real, but their knowledge of what I did has made every later meeting a negotiation.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-motivation',
      slot: 'motivation',
      text: 'I seek enough wealth and influence that I never have to depend on mercy, and I maintain alliances only while their price stays below their value.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ce-ideals',
      slot: 'ideals',
      text: 'No claim of authority outweighs my right to seize the life I want.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-flaws',
      slot: 'flaws',
      text: 'I let resentment turn a manageable setback into a personal vendetta.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-choice',
      slot: 'choice',
      text: 'When a gatekeeper humiliated me, I ruined something they valued instead of walking away. The retaliation ended their refusal but harmed bystanders, and I still resent being asked to repair what my anger made useful in the moment.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-motivation',
      slot: 'motivation',
      text: 'I seek enough power that no gatekeeper can corner me again, and I answer obstruction quickly before fear can look like submission.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'lg-ideals-alt',
      slot: 'ideals',
      text: 'A wrong left unspoken to keep the peace can harm the people that peace was meant to protect.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-flaws-alt',
      slot: 'flaws',
      text: 'I stay to offer mercy when leaving would stop the harm from spreading further.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-choice-alt',
      slot: 'choice',
      text: 'When a superior ordered me to ignore a theft from the poor, I reported it through the proper channel. The thief was punished and my patron lost face, so I learned that lawful correction can cost the protector I trusted.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-motivation-alt',
      slot: 'motivation',
      text: 'I look for broken arrangements where one honest witness can force correction without turning every dispute into a private crusade.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'ng-ideals-alt',
      slot: 'ideals',
      text: 'A debt repaid quietly matters as much as help offered in public.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-flaws-alt',
      slot: 'flaws',
      text: 'I assume others can manage without me and only notice my absence after something collapses.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-choice-alt',
      slot: 'choice',
      text: 'When a friend asked me to take credit for their work, I refused and named them instead. The recognition they gained cost me a sponsor, and I still choose honesty over a faster rise.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-motivation-alt',
      slot: 'motivation',
      text: 'I seek quiet work where steady care matters more than spectacle, especially when no one will applaud the result.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'cg-ideals-alt',
      slot: 'ideals',
      text: 'People deserve to refuse help as firmly as they deserve to receive it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-flaws-alt',
      slot: 'flaws',
      text: 'I treat any rule I did not choose as a personal insult and provoke avoidable confrontations.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-choice-alt',
      slot: 'choice',
      text: 'When a council banned a harmless trade, I taught the sellers a route the guards had not mapped. The market survived, but the fines fell on people who trusted my plan without reading its risks.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-motivation-alt',
      slot: 'motivation',
      text: 'I seek communities where members can leave, return, and negotiate terms without a single authority defining belonging for them.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'ln-ideals-alt',
      slot: 'ideals',
      text: 'A standard I accept should still work when no one is watching me enforce it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln', 'lg'],
    },
    {
      id: 'ln-flaws-alt',
      slot: 'flaws',
      text: 'I reject useful improvisation because it was not part of the plan I announced.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-choice-alt',
      slot: 'choice',
      text: 'When a shortcut would have met the deadline but violated the method I promised, I took the longer route and missed the reward. The work held, and I still treat the method as part of the obligation.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-motivation-alt',
      slot: 'motivation',
      text: 'I want a role with written expectations I can meet in full, where success is measured by the standard rather than by who interprets it loudest.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'n-ideals-alt',
      slot: 'ideals',
      text: 'Balance matters more to me than proving which side was morally superior from the start.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-flaws-alt',
      slot: 'flaws',
      text: 'I treat every strong opinion as suspect and withhold support until the argument exhausts itself.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n', 'cn'],
    },
    {
      id: 'n-choice-alt',
      slot: 'choice',
      text: 'When a mediator asked me to endorse a harsh punishment, I offered restitution instead. Neither side thanked me, but the injured party recovered enough to keep working.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-motivation-alt',
      slot: 'motivation',
      text: 'I look for situations where a measured compromise can hold long enough for better facts to arrive.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'cn-ideals-alt',
      slot: 'ideals',
      text: 'Curiosity deserves room to wander, but the people counting on me deserve warning before I wander away.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-flaws-alt',
      slot: 'flaws',
      text: 'I treat a surprise invitation as a trap and sabotage plans before anyone can disappoint me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-choice-alt',
      slot: 'choice',
      text: 'When a festival locked me into a role I had outgrown, I traded places with a willing stranger and vanished into the crowd. I gained a day of freedom and left an organizer to explain the missing performer.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-motivation-alt',
      slot: 'motivation',
      text: 'I chase openings that let me test a new skill or route, but I leave a note about where I can be found when the test runs longer than promised.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'le-ideals-alt',
      slot: 'ideals',
      text: 'Order I build should survive my absence, not collapse the moment I stop watching it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-flaws-alt',
      slot: 'flaws',
      text: 'I confuse loyalty with ownership and treat dissent as theft from the structure I control.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-choice-alt',
      slot: 'choice',
      text: 'When a rival offered a shared profit if I looked away from their smuggling, I accepted the ledger and exposed them at the audit. The profit vanished, but the route stayed licensed under my name.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-motivation-alt',
      slot: 'motivation',
      text: 'I seek a post where records, debts, and permissions give me leverage without needing to raise a blade.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'ne-ideals-alt',
      slot: 'ideals',
      text: 'A bargain I accept should still leave me stronger after the other party walks away satisfied.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-flaws-alt',
      slot: 'flaws',
      text: 'I renegotiate every favor the moment the other person shows they still need me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-choice-alt',
      slot: 'choice',
      text: 'When a patron offered to erase my debts if I lied for them in court, I traded the lie for a slower payment plan with witnesses. I kept my freedom and still owe them interest they enjoy collecting.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-motivation-alt',
      slot: 'motivation',
      text: 'I look for partners who profit when I succeed, so their help arrives before my need becomes visible weakness.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ce-ideals-alt',
      slot: 'ideals',
      text: 'I answer humiliation by making the offender regret the lesson, not by claiming a higher moral right.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-flaws-alt',
      slot: 'flaws',
      text: 'I escalate a slight into a spectacle so no one mistakes quiet restraint for weakness.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-choice-alt',
      slot: 'choice',
      text: 'When an employer withheld my pay, I sold their private schedule to a competitor instead of confronting them directly. I was paid twice and marked as someone who trades secrets under pressure.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-motivation-alt',
      slot: 'motivation',
      text: 'I hunt leverage over anyone who can deny me food, shelter, or passage, and I spend it quickly before they recover the advantage.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'context-1',
      slot: 'bonds',
      text: 'I have claimed a place in {{organization.name}}, and I take on overlooked work to prove I belong there.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-2',
      slot: 'bonds',
      text: 'Someone in {{organization.name}} vouched for me; I return because I intend to justify their trust.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-3',
      slot: 'experience',
      text: 'On my first difficult assignment for {{organization.name}}, I followed an experienced member’s routine and caught an error they had missed. Reporting it protected the work but strained that relationship, so I now balance loyalty to my colleagues against the purpose we share.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-4',
      slot: 'experience',
      text: 'When someone invoked my title, {{organization.title}}, to demand help from {{organization.name}}, I acted before confirming whether I had authority. The immediate problem was contained, but the reprimand forced me to decide which duties belong to the title and which I claim personally.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.title', 'organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-5',
      slot: 'bonds',
      text: 'I keep a place ready in {{residence.name}} for someone who has not yet returned.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['residence.name'],
      conditions: ['placeRole.residence'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-6',
      slot: 'experience',
      text: 'During a disruption in {{residence.name}}, I organized my neighbors around the routines and supplies I knew best. We restored ordinary life, but the effort exposed how much everyone relied on one fragile place, so I left to secure what it still lacks.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['residence.name'],
      conditions: ['placeRole.residence'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-hometown-1',
      slot: 'bonds',
      text: 'I owe {{hometown.name}} a service I promised before I left, and I mean to return able to provide it.',
      themeIds: ['belonging', 'duty'],
      requires: ['hometown.name'],
      conditions: ['placeRole.hometown'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-org-obligation-1',
      slot: 'ideals',
      text: 'I believe my place in {{organization.name}} comes with responsibilities I cannot ignore.',
      themeIds: ['duty'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-mentor-1',
      slot: 'experience',
      text: 'When I ignored {{mentor.name}}’s warning and attempted a task alone, my mistake damaged work we both valued. I helped repair it under their direction, and now I repeat that warning whenever confidence tempts me to skip preparation.',
      themeIds: ['duty', 'ambition', 'belonging'],
      requires: ['mentor.name'],
      conditions: ['personRole.mentor'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-child-1',
      slot: 'bonds',
      text: 'I promised {{child.name}} I would return with an answer to the question they trusted me to solve.',
      themeIds: ['duty', 'belonging'],
      requires: ['child.name'],
      conditions: ['personRole.child'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-rival-1',
      slot: 'flaws',
      text: 'I measure myself against {{rival.name}} more often than I admit, even when no one is watching.',
      themeIds: ['ambition', 'duty'],
      requires: ['rival.name'],
      conditions: ['personRole.rival'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-7',
      slot: 'experience',
      text: 'During my first demanding work as a {{class.name}}, I rushed the final stage and undid hours of careful preparation. Repeating the task in deliberate steps restored the result, and I still divide unfamiliar problems before urgency can dictate my pace.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['class.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-8',
      slot: 'personalityTraits',
      text: 'I explain unfamiliar problems by comparing each step to a lesson from my training as a {{class.name}}.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['class.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-9',
      slot: 'personalityTraits',
      text: 'When someone describes being {{species.name}}, I ask which daily habit outsiders misunderstand first.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['species.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-10',
      slot: 'experience',
      text: 'When someone assumed my being {{species.name}} settled what I could contribute, I took responsibility for a task they had withheld from me. Its success opened one door but made me wary of becoming anyone’s exception to a careless rule.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['species.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-11',
      slot: 'bonds',
      text: 'I possess an heirloom tied to my {{heritage.name}} heritage and intend to return it only after I learn why it was entrusted to me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['heritage.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-12',
      slot: 'experience',
      text: 'At a gathering tied to {{culture.name}}, I changed a familiar practice to include someone usually left out. The choice earned one person’s gratitude and another’s anger, leaving me responsible for explaining what I preserved and why I changed the rest.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['culture.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-13',
      slot: 'personalityTraits',
      text: 'I take notes when I have an opportunity to learn something new.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:wizard'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-14',
      slot: 'personalityTraits',
      text: 'I pay close attention to the way a tool balances in my hand.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:fighter'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-15',
      slot: 'personalityTraits',
      text: 'I remember the rhythm of a conversation as clearly as its words.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:bard'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-16',
      slot: 'personalityTraits',
      text: 'I notice paths and exits before settling into an unfamiliar place.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:ranger', 'class:rogue'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-17',
      slot: 'personalityTraits',
      text: 'I pause to collect my thoughts before beginning an important task.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:monk', 'class:cleric'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-18',
      slot: 'personalityTraits',
      text: 'I notice small changes in the plants and animals around me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:druid'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-19',
      slot: 'flaws',
      text: 'After a difficult conversation, I rehearse better replies aloud and miss what the next person is saying.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-20',
      slot: 'flaws',
      text: 'I keep using a worn-out possession until it fails at the worst moment because replacing it feels like admitting defeat.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-21',
      slot: 'bonds',
      text: 'I left a piece of work unfinished after someone said I could not complete it, and I still carry the part needed to resume.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-22',
      slot: 'bonds',
      text: 'I owe my former teacher proof that I can apply the lesson I once dismissed.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-23',
      slot: 'personalityTraits',
      text: 'I arrange my belongings the same way whenever I stop to rest.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-24',
      slot: 'personalityTraits',
      text: 'I use small tasks to give myself time to think.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-trait-pressure-1',
      slot: 'personalityTraits',
      text: 'When plans conflict, I protect the promise another person is already counting on.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-trait-pressure-2',
      slot: 'personalityTraits',
      text: 'When I enter a new place, I find the person doing necessary work without recognition.',
      themeIds: ['belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-ideal-stewardship-1',
      slot: 'ideals',
      text: 'Anything entrusted to me should be returned safer, sounder, or better understood.',
      themeIds: ['duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-ideal-hospitality-1',
      slot: 'ideals',
      text: 'A community proves its strength by how it treats the person with the least claim on it.',
      themeIds: ['belonging', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-debt-1',
      slot: 'bonds',
      text: 'A stranger once paid a cost meant for me; I am searching for them so I can repay it.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-rivalry-1',
      slot: 'bonds',
      text: 'A rival holds the only honest measure of my best work, and I need one more contest with them.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-possession-1',
      slot: 'bonds',
      text: 'I guard a sealed parcel for someone who vanished before naming its destination.',
      themeIds: ['duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-witness-1',
      slot: 'bonds',
      text: 'I was the only witness when someone made a costly promise, and I intend to see it remembered.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-bond-place-1',
      slot: 'bonds',
      text: 'A neglected meeting place once sheltered me; I send what I can to keep its door open.',
      themeIds: ['belonging', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'relationship-org-bond-2',
      slot: 'bonds',
      text: 'I accepted unfinished work from a departed member of {{organization.name}}, and I will not let their effort disappear.',
      themeIds: ['duty', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-org-bond-3',
      slot: 'bonds',
      text: 'A decision inside {{organization.name}} harmed someone who trusted me; I owe them either a reversal or the truth about my part in it.',
      themeIds: ['duty', 'belonging'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-hometown-2',
      slot: 'bonds',
      text: 'Someone in {{hometown.name}} keeps a record I need to set right before others inherit my version of the story.',
      themeIds: ['belonging', 'duty'],
      requires: ['hometown.name'],
      conditions: ['placeRole.hometown'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-residence-1',
      slot: 'bonds',
      text: 'I hid something important in {{residence.name}} and must recover it before repairs expose it to someone else.',
      themeIds: ['belonging', 'ambition'],
      requires: ['residence.name'],
      conditions: ['placeRole.residence'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-mentor-2',
      slot: 'bonds',
      text: 'I possess the last task {{mentor.name}} gave me, and I refuse to call our lessons finished until I attempt it.',
      themeIds: ['duty', 'ambition'],
      requires: ['mentor.name'],
      conditions: ['personRole.mentor'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-child-2',
      slot: 'bonds',
      text: 'I keep a place in my plans for {{child.name}}, even when protecting it costs me an easier opportunity.',
      themeIds: ['duty', 'belonging'],
      requires: ['child.name'],
      conditions: ['personRole.child'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-rival-2',
      slot: 'bonds',
      text: 'Only {{rival.name}} knows whether my proudest victory was fairly earned, and I need their answer.',
      themeIds: ['ambition', 'duty'],
      requires: ['rival.name'],
      conditions: ['personRole.rival'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-heritage-1',
      slot: 'bonds',
      text: 'I promised to place an account of my {{heritage.name}} heritage where the next seeker can find it.',
      themeIds: ['belonging', 'duty'],
      requires: ['heritage.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'foundation-flaw-rescue-1',
      slot: 'flaws',
      text: 'When someone struggles, I take over without asking and leave them fighting both the problem and me.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-flaw-credit-1',
      slot: 'flaws',
      text: 'When my contribution goes unrecognized, I withhold useful work until someone notices its absence.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-flaw-loyalty-1',
      slot: 'flaws',
      text: 'I defend people I consider mine long after the evidence says they caused the trouble.',
      themeIds: ['belonging', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-flaw-proof-1',
      slot: 'flaws',
      text: 'A challenge to my competence makes me attempt the hardest solution before the sensible one.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-flaw-secrecy-1',
      slot: 'flaws',
      text: 'Under pressure, I conceal one mistake to preserve trust and create a larger betrayal when it surfaces.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-debt-1',
      slot: 'experience',
      text: 'When I could not pay for something necessary, an acquaintance risked their standing to vouch for me. I accepted rather than go without, and their later disappearance left me carrying a debt with no obvious way to repay it.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-failure-1',
      slot: 'experience',
      text: 'I volunteered to lead familiar work and dismissed a quieter person’s warning. The failure cost us our materials, and rebuilding under their plan taught everyone exactly whose judgment had been missing.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-mercy-1',
      slot: 'experience',
      text: 'I once caught someone taking what I was responsible for guarding. I let them leave with part of it after hearing their need, and replacing it myself cost me a privilege but preserved a life I later saw restored.',
      themeIds: ['duty', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-rivalry-1',
      slot: 'experience',
      text: 'A rival and I pursued the same prize until an accident put it beyond either of us alone. I offered a temporary partnership, and sharing the result saved our work while making the next contest far more personal.',
      themeIds: ['ambition', 'belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-experience-departure-1',
      slot: 'experience',
      text: 'On the morning I was expected to stay, I packed only what I could carry and left a note instead of facing an argument. The departure won me time but denied someone an answer, and their unanswered message still travels with me.',
      themeIds: ['belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'relationship-org-experience-1',
      slot: 'experience',
      text: 'When {{organization.name}} divided over an urgent decision, I backed the proposal that protected our immediate work. It succeeded, but a colleague bore a cost I had minimized, leaving me responsible for repairing trust after winning the argument.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-org-experience-2',
      slot: 'experience',
      text: 'I once broke procedure inside {{organization.name}} to finish time-sensitive work. The result helped the people waiting for it, but the shortcut hid a weakness others now expect me to explain and correct.',
      themeIds: ['duty', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.current'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-hometown-experience-1',
      slot: 'experience',
      text: 'During a crisis in {{hometown.name}}, I carried news between people who refused to speak directly. My edited version kept them cooperating until the danger passed, but the missing truth became one reason I could not remain.',
      themeIds: ['belonging', 'duty'],
      requires: ['hometown.name'],
      conditions: ['placeRole.hometown'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-residence-experience-1',
      slot: 'experience',
      text: 'When damage threatened {{residence.name}}, I saved the possessions I thought irreplaceable before helping with the structure. We kept the place standing, but someone else lost what I had overlooked, changing what I now rescue first.',
      themeIds: ['belonging', 'duty'],
      requires: ['residence.name'],
      conditions: ['placeRole.residence'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-mentor-experience-2',
      slot: 'experience',
      text: 'I challenged {{mentor.name}}’s method during a task where others could hear us. My alternative worked, but the public challenge damaged the trust that had made disagreement safe, so I now owe them a private conversation more difficult than the original lesson.',
      themeIds: ['ambition', 'belonging', 'duty'],
      requires: ['mentor.name'],
      conditions: ['personRole.mentor'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-child-experience-1',
      slot: 'experience',
      text: 'When {{child.name}} copied a shortcut they had seen me take, the consequence fell on them instead of me. I admitted where they learned it and helped repair the harm, losing some authority but gaining a promise to speak honestly next time.',
      themeIds: ['duty', 'belonging'],
      requires: ['child.name'],
      conditions: ['personRole.child'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-rival-experience-1',
      slot: 'experience',
      text: 'I once had a clear chance to embarrass {{rival.name}} during a public test and chose to beat their work instead. I lost by a narrow margin, but the restraint earned a candid criticism that improved the skill I had meant to display.',
      themeIds: ['ambition', 'duty'],
      requires: ['rival.name'],
      conditions: ['personRole.rival'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-class-experience-2',
      slot: 'experience',
      text: 'Someone once asked me to solve a problem solely because I was a {{class.name}}. I accepted despite my doubts, adapted my training when the usual method failed, and succeeded only after admitting what help I needed.',
      themeIds: ['duty', 'ambition', 'belonging'],
      requires: ['class.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-culture-experience-2',
      slot: 'experience',
      text: 'I explained a practice tied to {{culture.name}} to someone who challenged the version I knew. I first defended it from memory, then sought another account, and returned with a more complicated answer that changed both our positions.',
      themeIds: ['belonging', 'ambition'],
      requires: ['culture.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'foundation-choice-truth-1',
      slot: 'choice',
      text: 'When silence would have preserved my place in a group, I admitted that our success depended on someone we had excluded. The truth cost me influence, but it brought that person back with terms the group could no longer ignore.',
      themeIds: ['belonging', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-choice-legacy-1',
      slot: 'choice',
      text: 'I was offered credit for finishing work begun by someone absent. I named their contribution publicly and lost sole ownership of the reward, but preserved a record that may lead me back to them.',
      themeIds: ['ambition', 'duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-motivation-answer-1',
      slot: 'motivation',
      text: 'I am following the trail of the person who trusted me with an unanswered question, and I will bring back evidence rather than a comforting guess.',
      themeIds: ['duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'foundation-motivation-refuge-1',
      slot: 'motivation',
      text: 'I am gathering allies and resources to make one threatened place defensible without turning it into a prison for the people who live there.',
      themeIds: ['belonging', 'duty', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'relationship-former-org-experience-1',
      slot: 'experience',
      text: 'Before I left {{organization.name}}, I accepted blame for a shared failure so another member could remain. My departure protected their position but let the false account stand, and I now carry evidence that could clear my name at their expense.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      conditions: ['organizationMembership.former'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-partner-1',
      slot: 'bonds',
      text: 'I promised {{partner.name}} that one shared decision would wait for my return, even though delay may close the safest option.',
      themeIds: ['duty', 'belonging'],
      requires: ['partner.name'],
      conditions: ['personRole.partner'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-parent-1',
      slot: 'bonds',
      text: 'I have a question for {{parent.name}} that only matters if I hear the answer from them directly.',
      themeIds: ['belonging', 'duty'],
      requires: ['parent.name'],
      conditions: ['personRole.parent'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-birthplace-experience-1',
      slot: 'experience',
      text: 'On my last visit to {{birthplace.name}}, I found a familiar landmark altered and accused the wrong person of neglect. Helping restore what could be saved corrected my mistake but revealed a local conflict I had been absent too long to understand.',
      themeIds: ['belonging', 'duty'],
      requires: ['birthplace.name'],
      conditions: ['placeRole.birthplace'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'relationship-property-1',
      slot: 'bonds',
      text: 'I share responsibility for {{property.name}} with someone whose plans oppose mine, and neither of us can settle its future alone.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['property.name'],
      conditions: ['placeRole.property'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
  ],
})
