import { narrativeCollectionSchema } from '@rpg/contracts/character-narrative'

export const foundationCollection = narrativeCollectionSchema.parse({
  revision: 'foundation-1',
  fragments: [
    {
      id: 'duty-foundation-1',
      slot: 'personalityTraits',
      text: 'I keep careful track of the commitments I make.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-2',
      slot: 'personalityTraits',
      text: 'I prepare for a difficult conversation before I begin it.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-3',
      slot: 'ideals',
      text: 'I want my actions to reflect the commitments I have chosen for myself.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-4',
      slot: 'bonds',
      text: 'I keep a small reminder of a commitment I have yet to fulfill.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-5',
      slot: 'flaws',
      text: 'I have trouble admitting that I have taken on more than I can manage.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-6',
      slot: 'experience',
      text: 'I learned early to pay attention to what people expected of me. Some expectations fit, and others did not, but deciding which commitments to accept became a habit that shaped the way I approached my days.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-7',
      slot: 'choice',
      text: 'I eventually faced a decision I could no longer postpone. I chose a responsibility of my own and accepted the work that came with it, knowing that I would have to discover its full cost along the way.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'duty-foundation-8',
      slot: 'motivation',
      text: 'Now I am looking for a chance to put that decision into practice. I want to discover what I can accomplish when my commitments are tested, and whether I can recognize the moment when I need to change my approach.',
      themeIds: ['duty'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-1',
      slot: 'personalityTraits',
      text: 'I remember the small habits of people I spend time with.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-2',
      slot: 'personalityTraits',
      text: 'I listen for a while before deciding how much of myself to reveal.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-3',
      slot: 'ideals',
      text: 'I want to choose where I belong instead of accepting the place others assign me.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-4',
      slot: 'bonds',
      text: 'I carry a familiar keepsake that reminds me of a place I once knew well.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-5',
      slot: 'flaws',
      text: 'I read too much into a change in someone’s tone.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-6',
      slot: 'experience',
      text: 'I became accustomed to watching how people made room for one another. I noticed the rituals that brought a group together and the silences that kept a newcomer outside, and I began to wonder where I wanted to stand.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-7',
      slot: 'choice',
      text: 'Rather than let familiarity make the decision for me, I chose to look beyond the circle I already knew. The choice gave me room to reconsider what I wanted from companionship and what I was willing to offer in return.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'belonging-foundation-8',
      slot: 'motivation',
      text: 'I am still looking for a place that fits the person I am becoming. Each new acquaintance gives me another chance to decide which connections to deepen, which expectations to question, and how much of my past I want to carry forward.',
      themeIds: ['belonging'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-1',
      slot: 'personalityTraits',
      text: 'I turn distant goals into small tasks I can begin today.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-2',
      slot: 'personalityTraits',
      text: 'I ask precise questions when something catches my interest.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-3',
      slot: 'ideals',
      text: 'I want to measure my progress against a goal I have chosen for myself.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-4',
      slot: 'bonds',
      text: 'I have kept a record of a project I am determined to finish.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-5',
      slot: 'flaws',
      text: 'I struggle to enjoy a success before setting myself another challenge.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-6',
      slot: 'experience',
      text: 'I discovered that an ordinary task could hold my attention long after everyone else had put it aside. Repetition taught me to notice small improvements, and the satisfaction of learning something difficult made me wonder what else I could attempt.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-7',
      slot: 'choice',
      text: 'I chose to pursue a goal that required more than the routines I already knew. I set aside time to practice and accepted that progress would be uneven, even when admitting how much I still had to learn was uncomfortable.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'ambition-foundation-8',
      slot: 'motivation',
      text: 'Now I am seeking experiences that will test what I have learned. I want to turn an uncertain ambition into something tangible, while finding out which sacrifices I am willing to make and which parts of my life I intend to keep.',
      themeIds: ['ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: true,
    },
    {
      id: 'lg-ideals',
      slot: 'ideals',
      text: 'A promise matters most when keeping it protects someone who cannot repay me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-flaws',
      slot: 'flaws',
      text: 'I can be slow to forgive a broken promise, even when the person is trying to make amends.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-choice',
      slot: 'choice',
      text: 'I chose to keep my word when doing so meant taking on inconvenient work. I wanted my commitments to offer someone else a little certainty, and I learned that accepting help could make that responsibility easier to carry.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'lg-motivation',
      slot: 'motivation',
      text: 'I seek work where discipline and compassion can support each other. I want to leave people safer than I found them, while learning how to honor a promise without assuming that my first idea of what is right must be the only one.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['lg'],
    },
    {
      id: 'ng-ideals',
      slot: 'ideals',
      text: 'Helping someone matters more to me than receiving credit for it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-flaws',
      slot: 'flaws',
      text: 'I give away time I should reserve for my own needs.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-choice',
      slot: 'choice',
      text: 'I chose to help someone whose difficulty I could understand, even though I had no obligation to get involved. The experience taught me to look first at what a person needed and only afterward at what custom expected of me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'ng-motivation',
      slot: 'motivation',
      text: 'I want to put my abilities where they can make a useful difference. I am willing to work with others or find a different approach when necessary, so long as the people affected have a better chance than they had before.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ng'],
    },
    {
      id: 'cg-ideals',
      slot: 'ideals',
      text: 'No custom deserves my loyalty when it is used to keep someone helpless.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-flaws',
      slot: 'flaws',
      text: 'I rush to intervene before asking the people involved what help they actually want.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-choice',
      slot: 'choice',
      text: 'I chose to act on my conscience instead of waiting for someone else to grant permission. I found that helping well required more than defiance: I also had to listen to the people whose freedom I wanted to defend.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'cg-motivation',
      slot: 'motivation',
      text: 'I am looking for chances to help people claim more control over their own lives. I want room to act on my judgment, and I am learning that freedom means making space for other people’s choices as well as my own.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cg'],
    },
    {
      id: 'ln-ideals',
      slot: 'ideals',
      text: 'I hold myself to a chosen code even when it brings me no advantage.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-flaws',
      slot: 'flaws',
      text: 'I can mistake a clear procedure for a complete understanding of a problem.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-choice',
      slot: 'choice',
      text: 'I chose a rule of conduct and kept to it when taking an exception would have been easier. Making that choice gave my days a structure I could rely on, though I still had to learn how to apply it carefully.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'ln-motivation',
      slot: 'motivation',
      text: 'I seek responsibilities that will test the consistency of my chosen code. I want to know that I can carry a decision through without being pulled in a new direction by every appeal, temptation, or change in the mood around me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ln'],
    },
    {
      id: 'n-ideals',
      slot: 'ideals',
      text: 'I prefer a workable decision to a grand claim about how everyone should live.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-flaws',
      slot: 'flaws',
      text: 'I put off taking a side until others have already paid the cost of waiting.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-choice',
      slot: 'choice',
      text: 'I chose the course that seemed most workable instead of committing myself to either side of an argument. It settled my immediate difficulty, but it also made me consider when staying out of a dispute becomes a decision of its own.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'n-motivation',
      slot: 'motivation',
      text: 'I want enough independence to judge each situation on its own terms. I am looking for experiences that will broaden my options, without tying every choice I make to someone else’s cause or a principle I have not examined for myself.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['n'],
    },
    {
      id: 'cn-ideals',
      slot: 'ideals',
      text: 'I value the freedom to change my course when a new possibility catches my attention.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-flaws',
      slot: 'flaws',
      text: 'I abandon useful routines simply because they begin to feel like expectations.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-choice',
      slot: 'choice',
      text: 'I chose an unfamiliar path because I wanted the decision to be mine. Leaving a predictable routine brought uncertainty as well as relief, and I discovered that independence still required me to deal with the consequences of my own choices.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'cn-motivation',
      slot: 'motivation',
      text: 'I am following opportunities that promise discovery and room to maneuver. I want to keep my options open, try things I have not attempted before, and learn how to remain independent without letting every passing impulse decide my direction.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['cn'],
    },
    {
      id: 'le-ideals',
      slot: 'ideals',
      text: 'A bargain is most useful when its terms secure my advantage.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-flaws',
      slot: 'flaws',
      text: 'I become so concerned with maintaining control that I overlook a simpler opportunity.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-choice',
      slot: 'choice',
      text: 'I chose to bind an arrangement to terms that favored me, knowing someone else would bear the harder part of it. I preferred a dependable advantage to a quick reward, and learned how patiently a useful position could be built.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'le-motivation',
      slot: 'motivation',
      text: 'I seek a position whose rules I can understand and use to my advantage. I am prepared to make others bear costs I would rather avoid, provided I can preserve the order and reliable obligations that make my influence durable.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['le'],
    },
    {
      id: 'ne-ideals',
      slot: 'ideals',
      text: 'I will put my advancement ahead of another person’s comfort when the two conflict.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-flaws',
      slot: 'flaws',
      text: 'I assume other people are calculating an advantage as carefully as I am.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-choice',
      slot: 'choice',
      text: 'I chose an opportunity that benefited me despite the difficulty it left for someone else. I did not find a principle that made the choice noble; I found a result I wanted and decided that its cost to another person was acceptable.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ne-motivation',
      slot: 'motivation',
      text: 'I am looking for opportunities to improve my position, and I will judge them by what they offer me. Rules and alliances can be useful, but I do not intend to let either prevent an advantage merely because someone else would pay for it.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ne'],
    },
    {
      id: 'ce-ideals',
      slot: 'ideals',
      text: 'I would rather force an opening than accept a limit imposed on me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-flaws',
      slot: 'flaws',
      text: 'I let resentment turn a manageable setback into a personal vendetta.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-choice',
      slot: 'choice',
      text: 'I chose to lash out at an obstacle rather than accept it, even knowing the consequences could fall on others. The satisfaction was immediate, but it left me with new difficulties and a determination not to let anyone else choose my course.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'ce-motivation',
      slot: 'motivation',
      text: 'I seek the means to act on my desires without submitting to restraint. I am quick to turn frustration into hostility, and I want enough strength to break through whatever stands in my way, regardless of who must deal with the aftermath.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
      alignmentIds: ['ce'],
    },
    {
      id: 'context-1',
      slot: 'bonds',
      text: 'I want to make a place for myself in {{organization.name}}.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-2',
      slot: 'bonds',
      text: 'My connection to {{organization.name}} gives me a reason to keep returning.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-3',
      slot: 'experience',
      text: 'My connection to {{organization.name}} gave me a new routine and people whose habits I could learn. I began to notice which tasks held my attention, which expectations I questioned, and what I wanted that connection to mean in my life.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-4',
      slot: 'experience',
      text: 'I have spent time considering what my title, {{organization.title}}, means to me within {{organization.name}}. The words alone do not settle how I should act, but they give me a starting point for deciding which responsibilities I want to make my own.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['organization.title', 'organization.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-5',
      slot: 'bonds',
      text: 'I keep thinking about the life I am building in {{residence.name}}.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['residence.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-6',
      slot: 'experience',
      text: 'Living in {{residence.name}}, I developed familiar routines and learned which surroundings helped me think. Ordinary days gave me time to consider what I wanted from my life, and eventually familiarity itself became a reason to look for a new challenge.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['residence.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-7',
      slot: 'experience',
      text: 'My work as a {{class.name}} taught me to approach a difficult task in stages. Practice made some things easier, but it also showed me how much I had yet to learn and which parts of the work mattered most to me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['class.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-8',
      slot: 'personalityTraits',
      text: 'I relate unfamiliar problems to my training as a {{class.name}}.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['class.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-9',
      slot: 'personalityTraits',
      text: 'I take an interest in how other people describe being {{species.name}}.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['species.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-10',
      slot: 'experience',
      text: 'Being {{species.name}} is part of how I describe myself, but it has never answered every question about who I want to become. I have learned to pay attention to the experiences I share with others and to the choices that are distinctly my own.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['species.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-11',
      slot: 'bonds',
      text: 'My {{heritage.name}} heritage is something I want to understand on my own terms.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['heritage.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-12',
      slot: 'experience',
      text: 'My connection to {{culture.name}} gave me questions as well as familiar points of reference. I began comparing my own experiences with those of the people around me, deciding what I wanted to carry forward and what I needed to understand more carefully.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: ['culture.name'],
      affinities: [],
      conflictTags: [],
      weight: 3,
      fallback: false,
    },
    {
      id: 'context-13',
      slot: 'personalityTraits',
      text: 'I take notes when I have an opportunity to learn something new.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:wizard'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-14',
      slot: 'personalityTraits',
      text: 'I pay close attention to the way a tool balances in my hand.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:fighter'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-15',
      slot: 'personalityTraits',
      text: 'I remember the rhythm of a conversation as clearly as its words.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:bard'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-16',
      slot: 'personalityTraits',
      text: 'I notice paths and exits before settling into an unfamiliar place.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:ranger', 'class:rogue'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-17',
      slot: 'personalityTraits',
      text: 'I pause to collect my thoughts before beginning an important task.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:monk', 'class:cleric'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-18',
      slot: 'personalityTraits',
      text: 'I notice small changes in the plants and animals around me.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: ['class:druid'],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-19',
      slot: 'flaws',
      text: 'I rehearse what I should have said long after a conversation has ended.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-20',
      slot: 'flaws',
      text: 'I keep a worn-out possession because replacing it feels like admitting defeat.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-21',
      slot: 'bonds',
      text: 'I want to finish a piece of work I once set aside.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-22',
      slot: 'bonds',
      text: 'I keep an old lesson in mind whenever I face a familiar difficulty.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-23',
      slot: 'personalityTraits',
      text: 'I arrange my belongings the same way whenever I stop to rest.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
    {
      id: 'context-24',
      slot: 'personalityTraits',
      text: 'I use small tasks to give myself time to think.',
      themeIds: ['duty', 'belonging', 'ambition'],
      requires: [],
      affinities: [],
      conflictTags: [],
      weight: 1,
      fallback: false,
    },
  ],
})
